import type { Equipment } from "@/lib/equipment";

export type ExerciseCategory = "warmup" | "activation" | "main" | "cooldown";

export type Exercise = {
  id: string;
  name: string;
  category: ExerciseCategory;
  equipment: Equipment[];
  movementPattern: string[];
  muscleGroups: string[];
  focusTags?: string[];
  swapOptions?: string[];
  phaseMin?: "activation" | "skill" | "growth";
  movementIntensity?: "pattern" | "load" | "mobility";
  difficultyTier?: "easy" | "moderate" | "hard";
  loadType: "weighted" | "bodyweight" | "timed" | "assisted";
  durationOrReps: string;
  cues: string[];
  mistakes: string[];
  contraindications?: string[];
  videoUrl: string;
  tags: string[];
};

const rawExercises: Exercise[] = [
  {
    id: "cat-cow",
    name: "Cat-Cow Flow",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["spine", "core"],
    loadType: "bodyweight",
    durationOrReps: "6-8 reps",
    cues: ["Move through full spine", "Breathe with each rep"],
    mistakes: ["Rushing the range", "Letting shoulders collapse"],
    contraindications: ["Acute wrist pain (use fists or forearms)"],
    videoUrl: "https://example.com/video/cat-cow",
    tags: ["t-spine", "hips", "breath"],
  },
  {
    id: "wall-slides",
    name: "Wall Slides",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "scapular"],
    muscleGroups: ["upper back", "shoulders"],
    loadType: "bodyweight",
    durationOrReps: "8-10 reps",
    cues: ["Keep neck long", "Ribs stay down"],
    mistakes: ["Arching low back", "Shrugging shoulders"],
    contraindications: ["Shoulder impingement (reduce range)"],
    videoUrl: "https://example.com/video/wall-slides",
    tags: ["scap", "t-spine", "shoulders"],
  },
  {
    id: "foam-roll-upper-back",
    name: "Foam Roll Upper Back",
    category: "warmup",
    equipment: ["foam_roller"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "timed",
    durationOrReps: "60 sec",
    cues: ["Avoid rolling low back", "Pause on tight spots"],
    mistakes: ["Holding breath", "Rolling too fast"],
    contraindications: ["Osteoporosis (avoid direct pressure)"],
    videoUrl: "https://example.com/video/foam-roll-upper-back",
    tags: ["t-spine", "mobility"],
  },
  {
    id: "glute-bridges",
    name: "Glute Bridges",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["hinge", "glute"],
    muscleGroups: ["glutes", "hamstrings"],
    loadType: "bodyweight",
    durationOrReps: "10-12 reps",
    cues: ["Ribs stacked over hips", "Press through heels"],
    mistakes: ["Overextending low back", "Feet too far away"],
    contraindications: ["Acute low-back pain (shorten range)"],
    videoUrl: "https://example.com/video/glute-bridges",
    tags: ["glutes", "hips", "tva"],
  },
  {
    id: "band-pull-aparts",
    name: "Band Pull-Aparts",
    category: "activation",
    equipment: ["bands"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Keep neck long", "Squeeze shoulder blades"],
    mistakes: ["Shrugging shoulders", "Bending elbows"],
    contraindications: ["Shoulder irritation (use lighter band)"],
    videoUrl: "https://example.com/video/band-pull-aparts",
    tags: ["scap", "upper-back"],
  },
  {
    id: "scapular-pushups",
    name: "Scapular Push-Ups",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["push", "scapular"],
    muscleGroups: ["serratus", "upper back"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Straight arms", "Push the floor away"],
    mistakes: ["Bending elbows", "Head dropping"],
    contraindications: ["Wrist pain (use fists)"],
    videoUrl: "https://example.com/video/scapular-pushups",
    tags: ["scap", "core"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["core", "anti-extension"],
    muscleGroups: ["core", "hip flexors"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Ribs down", "Slow controlled reach"],
    mistakes: ["Arching low back", "Holding breath"],
    contraindications: ["Acute low-back pain (reduce range)"],
    videoUrl: "https://example.com/video/dead-bug",
    tags: ["tva", "core"],
  },
  {
    id: "dumbbell-rows",
    name: "Dumbbell Rows",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats", "biceps"],
    loadType: "weighted",
    durationOrReps: "8-12 reps",
    cues: ["Spine neutral", "Squeeze mid-back"],
    mistakes: ["Rotating torso", "Pulling with arm only"],
    contraindications: ["Low-back strain (support torso)"],
    videoUrl: "https://example.com/video/dumbbell-rows",
    tags: ["upper-back", "scap"],
  },
  {
    id: "prone-ytw",
    name: "Prone Y-T-W Raises",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "bodyweight",
    durationOrReps: "6-8 each",
    cues: ["Small range", "Control the tempo"],
    mistakes: ["Lifting with neck", "Winging shoulders"],
    contraindications: ["Shoulder pain (reduce range)"],
    videoUrl: "https://example.com/video/prone-ytw",
    tags: ["scap", "upper-back"],
  },
  {
    id: "split-stance-row",
    name: "Split Stance Row",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Brace core", "Pull elbow to hip"],
    mistakes: ["Shrugging", "Rotating hips"],
    contraindications: ["Acute shoulder pain"],
    videoUrl: "https://example.com/video/split-stance-row",
    tags: ["scap", "core"],
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    category: "main",
    equipment: ["dumbbells", "bench"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps", "shoulders"],
    loadType: "weighted",
    durationOrReps: "6-12 reps",
    cues: ["Shoulders down and back", "Press in a slight arc"],
    mistakes: ["Flaring elbows", "Bouncing at bottom"],
    contraindications: ["Shoulder pain (use neutral grip)"],
    videoUrl: "https://example.com/video/dumbbell-bench-press",
    tags: ["push", "chest", "upper"],
  },
  {
    id: "dumbbell-floor-press",
    name: "Dumbbell Floor Press",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps", "shoulders"],
    loadType: "weighted",
    durationOrReps: "6-12 reps",
    cues: ["Ribs down", "Pause elbows softly on floor"],
    mistakes: ["Overarching low back", "Pressing unevenly"],
    contraindications: ["Acute shoulder pain (reduce load)"],
    videoUrl: "https://example.com/video/dumbbell-floor-press",
    tags: ["push", "chest", "core"],
  },
  {
    id: "dumbbell-chest-fly",
    name: "Dumbbell Chest Fly",
    category: "main",
    equipment: ["dumbbells", "bench"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "shoulders"],
    loadType: "weighted",
    durationOrReps: "8-15 reps",
    cues: ["Soft elbows", "Stretch with control"],
    mistakes: ["Dropping too deep", "Shrugging shoulders"],
    contraindications: ["Shoulder instability (shorten range)"],
    videoUrl: "https://example.com/video/dumbbell-chest-fly",
    tags: ["push", "chest", "shoulders"],
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["push"],
    muscleGroups: ["shoulders"],
    loadType: "weighted",
    durationOrReps: "10-15 reps",
    cues: ["Lead with elbows", "Pause at shoulder height"],
    mistakes: ["Swinging torso", "Shrugging traps"],
    contraindications: ["Shoulder pain (reduce ROM)"],
    videoUrl: "https://example.com/video/dumbbell-lateral-raise",
    tags: ["push", "shoulders", "upper"],
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["push"],
    muscleGroups: ["shoulders", "triceps", "upper chest"],
    loadType: "weighted",
    durationOrReps: "6-12 reps",
    cues: ["Brace core", "Press straight up"],
    mistakes: ["Overarching back", "Uneven lockout"],
    contraindications: ["Shoulder pain (use neutral grip)"],
    videoUrl: "https://example.com/video/dumbbell-shoulder-press",
    tags: ["push", "shoulders", "upper"],
  },
  {
    id: "incline-pushup",
    name: "Incline Push-Up",
    category: "main",
    equipment: ["bench"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps", "shoulders"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Body in straight line", "Elbows at 45 degrees"],
    mistakes: ["Sagging hips", "Flaring elbows"],
    contraindications: ["Wrist pain (use handles)"],
    videoUrl: "https://example.com/video/incline-pushup",
    tags: ["chest", "core"],
  },
  {
    id: "hip-flexor-stretch",
    name: "Hip Flexor Stretch",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "hips"],
    muscleGroups: ["hip flexors"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Tuck tailbone slightly", "Keep ribs down"],
    mistakes: ["Overarching low back", "Leaning forward"],
    contraindications: ["Knee pain (use padding)"],
    videoUrl: "https://example.com/video/hip-flexor-stretch",
    tags: ["hips"],
  },
  {
    id: "thread-the-needle",
    name: "Thread-the-Needle",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "bodyweight",
    durationOrReps: "5-6 per side",
    cues: ["Breathe into mid-back", "Rotate from upper spine"],
    mistakes: ["Forcing the twist", "Holding breath"],
    contraindications: ["Shoulder pain (reduce range)"],
    videoUrl: "https://example.com/video/thread-the-needle",
    tags: ["t-spine", "scap"],
  },
  {
    id: "chin-tucks",
    name: "Chin Tucks",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "neck"],
    muscleGroups: ["neck"],
    loadType: "bodyweight",
    durationOrReps: "8-10 reps",
    cues: ["Lengthen back of neck", "Keep jaw relaxed"],
    mistakes: ["Tucking too hard", "Looking down"],
    contraindications: ["Cervical pain (light range)"],
    videoUrl: "https://example.com/video/chin-tucks",
    tags: ["neck"],
  },
  {
    id: "doorway-pec-stretch",
    name: "Doorway Pec Stretch",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "chest"],
    muscleGroups: ["chest", "shoulders"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Gentle stretch", "Keep ribs down"],
    mistakes: ["Overextending shoulder", "Arching back"],
    contraindications: ["Shoulder impingement"],
    videoUrl: "https://example.com/video/doorway-pec-stretch",
    tags: ["chest", "shoulders"],
  },
  {
    id: "thoracic-rotation",
    name: "Thoracic Rotation",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Rotate from upper spine", "Keep hips stacked"],
    mistakes: ["Twisting low back", "Rushing"],
    contraindications: ["Acute back pain (small range)"],
    videoUrl: "https://example.com/video/thoracic-rotation",
    tags: ["t-spine"],
  },
  {
    id: "wall-angel-hold",
    name: "Wall Angel Hold",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["mobility", "scapular"],
    muscleGroups: ["upper back", "shoulders"],
    loadType: "timed",
    durationOrReps: "20-30 sec",
    cues: ["Back of arms on wall", "Chin tucked"],
    mistakes: ["Ribs flaring", "Shrugging"],
    contraindications: ["Shoulder pain (shorter hold)"],
    videoUrl: "https://example.com/video/wall-angel-hold",
    tags: ["scap", "t-spine"],
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["core", "anti-rotation"],
    muscleGroups: ["core", "obliques"],
    loadType: "assisted",
    durationOrReps: "8-10 per side",
    cues: ["Brace core", "Hands move straight out"],
    mistakes: ["Rotating torso", "Leaning"],
    contraindications: ["Acute low-back pain (light band)"],
    videoUrl: "https://example.com/video/pallof-press",
    tags: ["core", "tva"],
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["core", "anti-extension"],
    muscleGroups: ["core", "glutes"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Reach long", "Keep hips level"],
    mistakes: ["Arching back", "Twisting hips"],
    contraindications: ["Wrist pain (use forearms)"],
    videoUrl: "https://example.com/video/bird-dog",
    tags: ["core", "tva"],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Elbows high", "Squeeze between shoulder blades"],
    mistakes: ["Leaning back", "Shrugging"],
    contraindications: ["Shoulder irritation (light band)"],
    videoUrl: "https://example.com/video/face-pull",
    tags: ["scap", "upper-back"],
  },
  {
    id: "hamstring-stretch",
    name: "Hamstring Stretch",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "hinge"],
    muscleGroups: ["hamstrings"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Keep spine long", "Soft knee bend"],
    mistakes: ["Rounding back", "Locking knee"],
    contraindications: ["Sciatic pain (gentle range)"],
    videoUrl: "https://example.com/video/hamstring-stretch",
    tags: ["hips", "hamstrings"],
  },
  {
    id: "banded-rows-seated",
    name: "Seated Band Row",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Tall spine", "Pull elbows back"],
    mistakes: ["Rounding shoulders", "Jerking"],
    contraindications: ["Low-back pain (sit on support)"],
    videoUrl: "https://example.com/video/seated-band-row",
    tags: ["upper-back", "scap"],
  },
  {
    id: "side-lying-open-book",
    name: "Side-Lying Open Book",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Knees stacked", "Breathe into the stretch"],
    mistakes: ["Letting knees drift", "Holding breath"],
    contraindications: ["Shoulder pain (short range)"],
    videoUrl: "https://example.com/video/open-book",
    tags: ["t-spine"],
  },
  {
    id: "ankle-mobility",
    name: "Ankle Mobility Rocks",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "ankles"],
    muscleGroups: ["ankles", "calves"],
    loadType: "bodyweight",
    durationOrReps: "8-10 per side",
    cues: ["Heel stays down", "Knee tracks over toes"],
    mistakes: ["Heel lifting", "Collapsing arch"],
    contraindications: ["Acute ankle pain"],
    videoUrl: "https://example.com/video/ankle-mobility",
    tags: ["ankles", "hips"],
  },
  {
    id: "banded-lat-stretch",
    name: "Banded Lat Stretch",
    category: "cooldown",
    equipment: ["bands"],
    movementPattern: ["mobility", "lats"],
    muscleGroups: ["lats", "upper back"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Hips back", "Reach long through arm"],
    mistakes: ["Twisting torso", "Shrugging"],
    contraindications: ["Shoulder pain (gentle range)"],
    videoUrl: "https://example.com/video/banded-lat-stretch",
    tags: ["lats", "t-spine"],
  },
  {
    id: "breathing-90-90",
    name: "90/90 Breathing",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["breath", "core"],
    muscleGroups: ["core", "diaphragm"],
    loadType: "timed",
    durationOrReps: "4-6 breaths",
    cues: ["Low ribs soften", "Long exhale"],
    mistakes: ["Chest breathing", "Neck tension"],
    contraindications: ["None"],
    videoUrl: "https://example.com/video/90-90-breathing",
    tags: ["breath", "tva"],
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    category: "main",
    equipment: ["none"],
    movementPattern: ["squat"],
    muscleGroups: ["quads", "glutes"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Sit between hips", "Knees track over toes"],
    mistakes: ["Heels lifting", "Collapsing knees"],
    contraindications: ["Knee pain (reduce depth)"],
    videoUrl: "https://example.com/video/bodyweight-squat",
    tags: ["legs", "squat"],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["squat"],
    muscleGroups: ["quads", "glutes", "core"],
    loadType: "weighted",
    durationOrReps: "6-12 reps",
    cues: ["Hold dumbbell close to chest", "Brace core and sit between hips"],
    mistakes: ["Collapsing chest", "Knees caving in"],
    contraindications: ["Knee pain (reduce range)"],
    videoUrl: "https://example.com/video/goblet-squat",
    tags: ["legs", "squat", "core"],
  },
  {
    id: "split-squat",
    name: "Split Squat",
    category: "main",
    equipment: ["none"],
    movementPattern: ["squat", "single-leg"],
    muscleGroups: ["quads", "glutes"],
    loadType: "bodyweight",
    durationOrReps: "6-10 per side",
    cues: ["Tall torso", "Soft back knee"],
    mistakes: ["Front knee caves in", "Leaning forward"],
    contraindications: ["Knee pain (shorten range)"],
    videoUrl: "https://example.com/video/split-squat",
    tags: ["legs", "squat"],
  },
  {
    id: "hip-hinge-drill",
    name: "Hip Hinge Drill",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["hinge"],
    muscleGroups: ["glutes", "hamstrings"],
    loadType: "bodyweight",
    durationOrReps: "8-10 reps",
    cues: ["Push hips back", "Spine long"],
    mistakes: ["Rounding back", "Bending knees too much"],
    contraindications: ["Low-back pain (shorten range)"],
    videoUrl: "https://example.com/video/hip-hinge-drill",
    tags: ["hinge", "posterior"],
  },
  {
    id: "bodyweight-good-morning",
    name: "Bodyweight Good Morning",
    category: "main",
    equipment: ["none"],
    movementPattern: ["hinge"],
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    loadType: "bodyweight",
    durationOrReps: "8-15 reps",
    cues: ["Soft knees", "Hinge hips back with long spine"],
    mistakes: ["Rounding back", "Collapsing chest"],
    contraindications: ["Acute low-back pain (regress)"],
    videoUrl: "https://example.com/video/bodyweight-good-morning",
    tags: ["hinge", "posterior", "control"],
  },
  {
    id: "db-rdl",
    name: "Dumbbell Romanian Deadlift",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["hinge"],
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    loadType: "weighted",
    durationOrReps: "6-12 reps",
    cues: ["Hinge at hips with soft knees", "Keep dumbbells close to legs"],
    mistakes: ["Rounding low back", "Turning it into a squat"],
    contraindications: ["Acute low-back pain (reduce load/range)"],
    videoUrl: "https://example.com/video/db-rdl",
    tags: ["hinge", "posterior", "glutes"],
  },
  {
    id: "back-extension",
    name: "Back Extension",
    category: "main",
    equipment: ["none"],
    movementPattern: ["hinge"],
    muscleGroups: ["lower back", "glutes", "hamstrings"],
    loadType: "bodyweight",
    durationOrReps: "10-15 reps",
    cues: ["Lift chest with neutral spine", "Squeeze glutes at the top"],
    mistakes: ["Overextending low back", "Using momentum"],
    contraindications: ["Acute low-back pain (shorten range)"],
    videoUrl: "https://example.com/video/back-extension",
    tags: ["hinge", "posterior", "lower-back"],
  },
  {
    id: "single-leg-rdl",
    name: "Single-Leg RDL (Bodyweight)",
    category: "main",
    equipment: ["none"],
    movementPattern: ["hinge", "single-leg"],
    muscleGroups: ["glutes", "hamstrings", "core"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Hips square", "Reach long"],
    mistakes: ["Opening hips", "Rounding back"],
    contraindications: ["Balance issues (use support)"],
    videoUrl: "https://example.com/video/single-leg-rdl",
    tags: ["hinge", "balance"],
  },
  {
    id: "pushup",
    name: "Push-Up",
    category: "main",
    equipment: ["none"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps", "shoulders"],
    loadType: "bodyweight",
    durationOrReps: "6-12 reps",
    cues: ["Body in one line", "Elbows 30-45°"],
    mistakes: ["Sagging hips", "Flaring elbows"],
    contraindications: ["Wrist pain (use handles)"],
    videoUrl: "https://example.com/video/pushup",
    tags: ["push", "upper"],
  },
  {
    id: "pike-pushup",
    name: "Pike Push-Up",
    category: "main",
    equipment: ["none"],
    movementPattern: ["push"],
    muscleGroups: ["shoulders", "triceps"],
    loadType: "bodyweight",
    durationOrReps: "6-10 reps",
    cues: ["Hips high", "Head between arms"],
    mistakes: ["Shrugging shoulders", "Partial range"],
    contraindications: ["Shoulder pain (reduce range)"],
    videoUrl: "https://example.com/video/pike-pushup",
    tags: ["push", "shoulders"],
  },
  {
    id: "archer-pushup",
    name: "Archer Push-Up",
    category: "main",
    equipment: ["none"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps", "shoulders", "core"],
    loadType: "bodyweight",
    durationOrReps: "5-8 per side",
    cues: ["Shift weight with control", "Keep ribs and hips aligned"],
    mistakes: ["Dropping chest too fast", "Twisting torso"],
    contraindications: ["Wrist pain (use handles or regress)"],
    videoUrl: "https://example.com/video/archer-pushup",
    tags: ["push", "advanced", "unilateral"],
  },
  {
    id: "pseudo-planche-pushup",
    name: "Pseudo Planche Push-Up",
    category: "main",
    equipment: ["none"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "shoulders", "triceps", "core"],
    loadType: "bodyweight",
    durationOrReps: "4-8 reps",
    cues: ["Lean shoulders forward", "Keep hollow body tension"],
    mistakes: ["Losing lean", "Sagging low back"],
    contraindications: ["Wrist/shoulder pain (regress)"],
    videoUrl: "https://example.com/video/pseudo-planche-pushup",
    tags: ["push", "advanced", "strength"],
  },
  {
    id: "cossack-squat",
    name: "Cossack Squat",
    category: "main",
    equipment: ["none"],
    movementPattern: ["squat", "single-leg", "mobility"],
    muscleGroups: ["quads", "adductors", "glutes"],
    loadType: "bodyweight",
    durationOrReps: "6-10 per side",
    cues: ["Keep heel down", "Sit into one hip with control"],
    mistakes: ["Collapsing chest", "Knee caving"],
    contraindications: ["Knee pain (reduce depth)"],
    videoUrl: "https://example.com/video/cossack-squat",
    tags: ["legs", "advanced", "mobility"],
  },
  {
    id: "shrimp-squat",
    name: "Shrimp Squat",
    category: "main",
    equipment: ["none"],
    movementPattern: ["squat", "single-leg"],
    muscleGroups: ["quads", "glutes", "core"],
    loadType: "bodyweight",
    durationOrReps: "4-8 per side",
    cues: ["Stay tall", "Control the bottom position"],
    mistakes: ["Dropping fast", "Losing balance"],
    contraindications: ["Knee pain (regress)"],
    videoUrl: "https://example.com/video/shrimp-squat",
    tags: ["legs", "advanced", "balance"],
  },
  {
    id: "single-leg-hip-thrust",
    name: "Single-Leg Hip Thrust",
    category: "main",
    equipment: ["none"],
    movementPattern: ["hinge", "single-leg"],
    muscleGroups: ["glutes", "hamstrings", "core"],
    loadType: "bodyweight",
    durationOrReps: "8-12 per side",
    cues: ["Drive through heel", "Keep pelvis level"],
    mistakes: ["Overextending low back", "Dropping hip"],
    contraindications: ["Acute low-back pain"],
    videoUrl: "https://example.com/video/single-leg-hip-thrust",
    tags: ["hinge", "advanced", "posterior"],
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    category: "main",
    equipment: ["none"],
    movementPattern: ["core", "anti-extension"],
    muscleGroups: ["core", "hip flexors"],
    loadType: "timed",
    durationOrReps: "20-40 sec",
    cues: ["Press low back to floor", "Reach long through arms and legs"],
    mistakes: ["Arching back", "Neck strain"],
    contraindications: ["Low-back pain (regress)"],
    videoUrl: "https://example.com/video/hollow-body-hold",
    tags: ["core", "advanced", "stability"],
  },
  {
    id: "side-plank-star",
    name: "Side Plank Star",
    category: "main",
    equipment: ["none"],
    movementPattern: ["core", "anti-rotation", "single-leg"],
    muscleGroups: ["obliques", "glute med", "shoulders"],
    loadType: "timed",
    durationOrReps: "15-30 sec per side",
    cues: ["Stack shoulders/hips", "Lift top leg without rotating"],
    mistakes: ["Dropping hips", "Shrugging shoulder"],
    contraindications: ["Shoulder pain (regress)"],
    videoUrl: "https://example.com/video/side-plank-star",
    tags: ["core", "advanced", "balance"],
  },
  {
    id: "prone-swimmer",
    name: "Prone Swimmer",
    category: "main",
    equipment: ["none"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts", "rotator cuff"],
    loadType: "bodyweight",
    durationOrReps: "6-10 reps",
    cues: ["Lift lightly, then sweep arms overhead with control", "Keep neck long"],
    mistakes: ["Shrugging up", "Rushing through sweep"],
    contraindications: ["Shoulder pain (shorten range)"],
    videoUrl: "https://example.com/video/prone-swimmer",
    tags: ["pull", "scap", "advanced"],
  },
  {
    id: "back-widow",
    name: "Back Widow Pulls",
    category: "main",
    equipment: ["none"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "lats", "rear delts"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Drive elbows into floor", "Lift chest with control"],
    mistakes: ["Pushing through neck", "Using momentum"],
    contraindications: ["Neck pain (reduce range)"],
    videoUrl: "https://example.com/video/back-widow",
    tags: ["pull", "upper-back", "strength"],
  },
  {
    id: "heels-elevated-squat",
    name: "Heels-Elevated Tempo Squat",
    category: "main",
    equipment: ["none"],
    movementPattern: ["squat"],
    muscleGroups: ["quads", "glutes", "core"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Slow 3-second lower", "Stay tall with knees tracking"],
    mistakes: ["Bouncing at bottom", "Collapsing knees"],
    contraindications: ["Knee pain (reduce depth)"],
    videoUrl: "https://example.com/video/heels-elevated-tempo-squat",
    tags: ["legs", "strength", "control"],
  },
  {
    id: "single-leg-glute-bridge-hold",
    name: "Single-Leg Glute Bridge Hold",
    category: "main",
    equipment: ["none"],
    movementPattern: ["hinge", "single-leg"],
    muscleGroups: ["glutes", "hamstrings", "core"],
    loadType: "timed",
    durationOrReps: "20-35 sec per side",
    cues: ["Keep hips level", "Push through heel and brace abs"],
    mistakes: ["Low-back arching", "Hip drop"],
    contraindications: ["Acute low-back pain"],
    videoUrl: "https://example.com/video/single-leg-glute-bridge-hold",
    tags: ["hinge", "balance", "stability"],
  },
  {
    id: "reverse-snow-angel",
    name: "Reverse Snow Angels",
    category: "main",
    equipment: ["none"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Thumbs up", "Sweep wide"],
    mistakes: ["Shrugging", "Rushing"],
    contraindications: ["Shoulder pain (short range)"],
    videoUrl: "https://example.com/video/reverse-snow-angel",
    tags: ["pull", "scap"],
  },
  {
    id: "plank",
    name: "Plank",
    category: "main",
    equipment: ["none"],
    movementPattern: ["core", "anti-extension"],
    muscleGroups: ["core", "shoulders"],
    loadType: "timed",
    durationOrReps: "30-45 sec",
    cues: ["Ribs down", "Glutes tight"],
    mistakes: ["Sagging hips", "Holding breath"],
    contraindications: ["Shoulder pain (shorten)"],
    videoUrl: "https://example.com/video/plank",
    tags: ["core", "stability"],
  },
  {
    id: "band-chest-press",
    name: "Band Chest Press",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps"],
    loadType: "assisted",
    durationOrReps: "8-12 reps",
    cues: ["Brace core", "Press straight"],
    mistakes: ["Ribs flaring", "Shoulders shrugging"],
    contraindications: ["Shoulder pain (light band)"],
    videoUrl: "https://example.com/video/band-chest-press",
    tags: ["push", "band"],
  },
  {
    id: "band-overhead-press",
    name: "Band Overhead Press",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["push"],
    muscleGroups: ["shoulders", "triceps", "upper chest"],
    loadType: "assisted",
    durationOrReps: "6-12 reps",
    cues: ["Brace core", "Press straight up without leaning back"],
    mistakes: ["Overarching low back", "Shrugging shoulders"],
    contraindications: ["Shoulder pain (light band)"],
    videoUrl: "https://example.com/video/band-overhead-press",
    tags: ["push", "band", "shoulders"],
  },
  {
    id: "band-lat-pulldown",
    name: "Band Lat Pulldown",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull"],
    muscleGroups: ["lats", "upper back", "biceps"],
    loadType: "assisted",
    durationOrReps: "8-14 reps",
    cues: ["Keep ribs stacked", "Drive elbows down to sides"],
    mistakes: ["Leaning back", "Pulling with neck tension"],
    contraindications: ["Shoulder pain (reduce ROM)"],
    videoUrl: "https://example.com/video/band-lat-pulldown",
    tags: ["pull", "band", "lats"],
  },
  {
    id: "band-rdl",
    name: "Band Romanian Deadlift",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["hinge"],
    muscleGroups: ["hamstrings", "glutes", "lower back"],
    loadType: "assisted",
    durationOrReps: "8-12 reps",
    cues: ["Push hips back", "Keep shins mostly vertical"],
    mistakes: ["Rounding back", "Bending knees too much"],
    contraindications: ["Acute low-back pain (light tension)"],
    videoUrl: "https://example.com/video/band-rdl",
    tags: ["hinge", "band", "posterior"],
  },
  {
    id: "band-front-squat",
    name: "Band Front Squat",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["squat"],
    muscleGroups: ["quads", "glutes", "core"],
    loadType: "assisted",
    durationOrReps: "8-15 reps",
    cues: ["Stay tall", "Knees track over toes"],
    mistakes: ["Collapsing chest", "Knees caving in"],
    contraindications: ["Knee pain (reduce depth)"],
    videoUrl: "https://example.com/video/band-front-squat",
    tags: ["squat", "band", "legs"],
  },
  {
    id: "band-woodchop",
    name: "Band Woodchop",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["core", "anti-rotation"],
    muscleGroups: ["obliques", "core", "shoulders"],
    loadType: "assisted",
    durationOrReps: "8-12 per side",
    cues: ["Rotate through torso with control", "Keep hips stable"],
    mistakes: ["Twisting knees", "Using momentum"],
    contraindications: ["Acute low-back pain (light band)"],
    videoUrl: "https://example.com/video/band-woodchop",
    tags: ["core", "band", "rotation"],
  },
  {
    id: "band-row",
    name: "Band Row",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Elbows back", "Tall spine"],
    mistakes: ["Leaning back", "Shrugging"],
    contraindications: ["Shoulder pain (light band)"],
    videoUrl: "https://example.com/video/band-row",
    tags: ["pull", "band"],
  },
  {
    id: "db-biceps-curl",
    name: "Dumbbell Biceps Curl",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["curl"],
    muscleGroups: ["biceps"],
    loadType: "weighted",
    durationOrReps: "10-15 reps",
    cues: ["Elbows by sides", "Curl with control and full range"],
    mistakes: ["Swinging torso", "Elbows drifting forward"],
    contraindications: ["Elbow pain (use lighter load)"],
    videoUrl: "https://example.com/video/db-biceps-curl",
    tags: ["biceps", "isolation", "arms"],
  },
  {
    id: "band-biceps-curl",
    name: "Band Biceps Curl",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["curl"],
    muscleGroups: ["biceps"],
    loadType: "assisted",
    durationOrReps: "12-20 reps",
    cues: ["Keep wrists neutral", "Control the lowering phase"],
    mistakes: ["Shrugging shoulders", "Using momentum"],
    contraindications: ["Elbow pain (reduce tension)"],
    videoUrl: "https://example.com/video/band-biceps-curl",
    tags: ["biceps", "isolation", "arms", "band"],
  },
  {
    id: "towel-biceps-curl-hold",
    name: "Towel Biceps Curl Hold",
    category: "main",
    equipment: ["none"],
    movementPattern: ["curl"],
    muscleGroups: ["biceps", "forearms"],
    loadType: "timed",
    durationOrReps: "20-35 sec",
    cues: ["Create steady self-resistance", "Keep elbows tucked"],
    mistakes: ["Neck tension", "Jerky effort"],
    contraindications: ["Elbow pain (shorten hold)"],
    videoUrl: "https://example.com/video/towel-biceps-curl-hold",
    tags: ["biceps", "isolation", "arms"],
  },
  {
    id: "db-triceps-extension",
    name: "Dumbbell Triceps Extension",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["extension"],
    muscleGroups: ["triceps"],
    loadType: "weighted",
    durationOrReps: "10-15 reps",
    cues: ["Upper arms steady", "Extend fully without locking hard"],
    mistakes: ["Flaring elbows", "Arching low back"],
    contraindications: ["Elbow pain (use lighter load)"],
    videoUrl: "https://example.com/video/db-triceps-extension",
    tags: ["triceps", "isolation", "arms"],
  },
  {
    id: "band-triceps-pressdown",
    name: "Band Triceps Pressdown",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["extension"],
    muscleGroups: ["triceps"],
    loadType: "assisted",
    durationOrReps: "12-20 reps",
    cues: ["Lock elbows near ribs", "Drive hands down with control"],
    mistakes: ["Shoulders rolling forward", "Using body sway"],
    contraindications: ["Elbow pain (reduce tension)"],
    videoUrl: "https://example.com/video/band-triceps-pressdown",
    tags: ["triceps", "isolation", "arms", "band"],
  },
  {
    id: "bodyweight-triceps-extension",
    name: "Bodyweight Triceps Extension",
    category: "main",
    equipment: ["none"],
    movementPattern: ["extension", "push"],
    muscleGroups: ["triceps", "shoulders"],
    loadType: "bodyweight",
    durationOrReps: "8-15 reps",
    cues: ["Body stays rigid", "Bend/extend mainly at elbows"],
    mistakes: ["Sagging hips", "Flaring elbows"],
    contraindications: ["Wrist pain (elevate hands)"],
    videoUrl: "https://example.com/video/bodyweight-triceps-extension",
    tags: ["triceps", "isolation", "arms"],
  },
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    category: "main",
    equipment: ["none"],
    movementPattern: ["calf"],
    muscleGroups: ["calves"],
    loadType: "bodyweight",
    durationOrReps: "12-20 reps",
    cues: ["Rise through big toe", "Pause briefly at top"],
    mistakes: ["Bouncing", "Ankles collapsing inward"],
    contraindications: ["Acute Achilles pain (shorten range)"],
    videoUrl: "https://example.com/video/standing-calf-raise",
    tags: ["calves", "isolation", "lower"],
  },
  {
    id: "single-leg-calf-raise",
    name: "Single-Leg Calf Raise",
    category: "main",
    equipment: ["none"],
    movementPattern: ["calf", "single-leg"],
    muscleGroups: ["calves"],
    loadType: "bodyweight",
    durationOrReps: "10-15 per side",
    cues: ["Use full range", "Control both up and down"],
    mistakes: ["Using momentum", "Hip shift"],
    contraindications: ["Acute Achilles pain (regress)"],
    videoUrl: "https://example.com/video/single-leg-calf-raise",
    tags: ["calves", "isolation", "lower"],
  },
  {
    id: "band-calf-raise",
    name: "Band Calf Raise",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["calf"],
    muscleGroups: ["calves"],
    loadType: "assisted",
    durationOrReps: "12-20 reps",
    cues: ["Keep tension through full range", "Pause at peak contraction"],
    mistakes: ["Band slack at bottom", "Rushing reps"],
    contraindications: ["Acute Achilles pain (light tension)"],
    videoUrl: "https://example.com/video/band-calf-raise",
    tags: ["calves", "isolation", "band", "lower"],
  },
  {
    id: "db-calf-raise",
    name: "Dumbbell Calf Raise",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["calf"],
    muscleGroups: ["calves"],
    loadType: "weighted",
    durationOrReps: "10-18 reps",
    cues: ["Hold load steady", "Drive straight up through forefoot"],
    mistakes: ["Bouncing bottom range", "Losing balance"],
    contraindications: ["Acute Achilles pain (reduce load)"],
    videoUrl: "https://example.com/video/db-calf-raise",
    tags: ["calves", "isolation", "lower"],
  },
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["carry", "core", "anti-rotation"],
    muscleGroups: ["grip", "traps", "core"],
    loadType: "timed",
    durationOrReps: "20-45 sec",
    cues: ["Stand tall", "Walk with short, controlled steps"],
    mistakes: ["Shrugging shoulders", "Leaning side to side"],
    contraindications: ["Acute low-back pain (reduce load)"],
    videoUrl: "https://example.com/video/farmers-carry",
    tags: ["carry", "core", "posture"],
  },
  {
    id: "suitcase-carry",
    name: "Suitcase Carry",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["carry", "core", "anti-rotation"],
    muscleGroups: ["obliques", "core", "grip"],
    loadType: "timed",
    durationOrReps: "20-40 sec per side",
    cues: ["Keep torso square", "Resist side bend"],
    mistakes: ["Leaning into load", "Walking too fast"],
    contraindications: ["Acute low-back pain (reduce load)"],
    videoUrl: "https://example.com/video/suitcase-carry",
    tags: ["carry", "core", "anti-rotation"],
  },
  {
    id: "band-suitcase-march",
    name: "Band Suitcase March",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["carry", "core", "anti-rotation"],
    muscleGroups: ["obliques", "core", "hips"],
    loadType: "assisted",
    durationOrReps: "20-40 sec per side",
    cues: ["Hold tension and march slowly", "Keep ribcage stacked over pelvis"],
    mistakes: ["Twisting torso", "Rushing steps"],
    contraindications: ["Acute low-back pain (light tension)"],
    videoUrl: "https://example.com/video/band-suitcase-march",
    tags: ["carry", "core", "anti-rotation", "band"],
  },
  {
    id: "suitcase-hold-march",
    name: "Suitcase Hold March",
    category: "main",
    equipment: ["none"],
    movementPattern: ["carry", "core", "anti-rotation"],
    muscleGroups: ["obliques", "core", "hips"],
    loadType: "timed",
    durationOrReps: "20-40 sec per side",
    cues: ["Brace and march in place", "Keep shoulders level"],
    mistakes: ["Rib flare", "Losing balance"],
    contraindications: ["Acute low-back pain (shorten duration)"],
    videoUrl: "https://example.com/video/suitcase-hold-march",
    tags: ["carry", "core", "anti-rotation"],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "main",
    equipment: ["none"],
    movementPattern: ["core", "anti-rotation"],
    muscleGroups: ["obliques", "core", "shoulders"],
    loadType: "timed",
    durationOrReps: "20-40 sec per side",
    cues: ["Stack hips and shoulders", "Drive floor away with forearm"],
    mistakes: ["Dropping hips", "Rotating chest down"],
    contraindications: ["Shoulder pain (regress to knees)"],
    videoUrl: "https://example.com/video/side-plank",
    tags: ["core", "anti-rotation", "stability"],
  },
];

const pickSwapOptions = (exercise: Exercise, list: Exercise[]) => {
  const matches = list.filter((candidate) => {
    if (candidate.id === exercise.id) return false;
    const patternOverlap = candidate.movementPattern.some((tag) =>
      exercise.movementPattern.includes(tag)
    );
    const tagOverlap = candidate.tags.some((tag) =>
      exercise.tags.includes(tag)
    );
    const loadCompatible =
      candidate.loadType === exercise.loadType ||
      (exercise.loadType !== "weighted" && candidate.loadType !== "weighted");
    return (patternOverlap || tagOverlap) && loadCompatible;
  });
  return matches.slice(0, 5).map((item) => item.id);
};

export const exercises: Exercise[] = rawExercises.map((exercise) => ({
  ...exercise,
  focusTags: exercise.focusTags ?? exercise.tags ?? [],
  swapOptions:
    exercise.swapOptions && exercise.swapOptions.length
      ? exercise.swapOptions
      : pickSwapOptions(exercise, rawExercises),
}));

const normalizeId = (id?: string) => (id ?? "").trim().toLowerCase();

export const exerciseById = (id?: string) => {
  const normalized = normalizeId(id);
  if (!normalized) return undefined;
  return exercises.find((exercise) => normalizeId(exercise.id) === normalized);
};

const historyLineageGroups: string[][] = [
  ["incline-pushup", "pushup", "band-chest-press", "dumbbell-floor-press", "dumbbell-bench-press", "dumbbell-chest-fly"],
  ["dumbbell-rows", "split-stance-row", "band-row", "band-lat-pulldown", "back-widow", "prone-ytw", "face-pull", "band-pull-aparts"],
  ["dead-bug", "bird-dog", "plank", "side-plank-star", "pallof-press", "band-woodchop"],
  [
    "glute-bridges",
    "single-leg-hip-thrust",
    "single-leg-rdl",
    "bodyweight-good-morning",
    "back-extension",
    "band-rdl",
    "hip-hinge-drill",
  ],
  ["bodyweight-squat", "split-squat", "heels-elevated-squat", "cossack-squat", "band-front-squat"],
  ["scapular-pushups", "wall-slides", "reverse-snow-angel"],
  ["band-overhead-press", "dumbbell-shoulder-press", "dumbbell-lateral-raise", "pike-pushup"],
];

const historyNeighborsByExerciseId: Map<string, Set<string>> = (() => {
  const map = new Map<string, Set<string>>();
  const connect = (left: string, right: string) => {
    if (!map.has(left)) map.set(left, new Set());
    map.get(left)?.add(right);
  };

  for (const exercise of exercises) {
    for (const swapId of exercise.swapOptions ?? []) {
      if (!exerciseById(swapId)) continue;
      connect(exercise.id, swapId);
      connect(swapId, exercise.id);
    }
  }

  for (const group of historyLineageGroups) {
    const existing = group.filter((id) => Boolean(exerciseById(id)));
    for (let i = 0; i < existing.length; i += 1) {
      for (let j = i + 1; j < existing.length; j += 1) {
        connect(existing[i], existing[j]);
        connect(existing[j], existing[i]);
      }
    }
  }

  return map;
})();

export const resolveExerciseHistoryIds = (exerciseId?: string, maxHops = 1) => {
  const seed = normalizeId(exerciseId);
  if (!seed) return [];
  const normalizedExercise = exerciseById(seed);
  const rootId = normalizedExercise?.id ?? seed;

  const visited = new Set<string>([rootId]);
  let frontier = new Set<string>([rootId]);

  for (let hop = 0; hop < maxHops; hop += 1) {
    const next = new Set<string>();
    for (const id of frontier) {
      const neighbors = historyNeighborsByExerciseId.get(id);
      if (!neighbors) continue;
      for (const neighborId of neighbors) {
        if (visited.has(neighborId)) continue;
        visited.add(neighborId);
        next.add(neighborId);
      }
    }
    if (!next.size) break;
    frontier = next;
  }

  return Array.from(visited);
};
