import type { Equipment } from "@/lib/equipment";

export type ExerciseCategory = "warmup" | "activation" | "main" | "cooldown";

export type Exercise = {
  id: string;
  name: string;
  category: ExerciseCategory;
  equipment: Equipment[];
  movementPattern: string[];
  muscleGroups: string[];
  loadType: "weighted" | "bodyweight" | "timed" | "assisted";
  durationOrReps: string;
  cues: string[];
  mistakes: string[];
  contraindications?: string[];
  videoUrl: string;
  tags: string[];
};

export const exercises: Exercise[] = [
  {
    id: "cat-cow",
    name: "Cat-Cow Flow",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["spine", "core"],
    loadType: "bodyweight",
    durationOrReps: "6-8 reps",
    cues: ["Move through full spine", "Breathe with each rep"],
    mistakes: ["Rushing the range", "Letting shoulders collapse"],
    contraindications: ["Acute wrist pain (use fists or forearms)"],
    videoUrl: "https://example.com/video/cat-cow",
    tags: ["t-spine", "hips", "breath"],
  },
  {
    id: "wall-slides",
    name: "Wall Slides",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "scapular"],
    muscleGroups: ["upper back", "shoulders"],
    loadType: "bodyweight",
    durationOrReps: "8-10 reps",
    cues: ["Keep neck long", "Ribs stay down"],
    mistakes: ["Arching low back", "Shrugging shoulders"],
    contraindications: ["Shoulder impingement (reduce range)"],
    videoUrl: "https://example.com/video/wall-slides",
    tags: ["scap", "t-spine", "shoulders"],
  },
  {
    id: "foam-roll-upper-back",
    name: "Foam Roll Upper Back",
    category: "warmup",
    equipment: ["foam_roller"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "timed",
    durationOrReps: "60 sec",
    cues: ["Avoid rolling low back", "Pause on tight spots"],
    mistakes: ["Holding breath", "Rolling too fast"],
    contraindications: ["Osteoporosis (avoid direct pressure)"],
    videoUrl: "https://example.com/video/foam-roll-upper-back",
    tags: ["t-spine", "mobility"],
  },
  {
    id: "glute-bridges",
    name: "Glute Bridges",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["hinge", "glute"],
    muscleGroups: ["glutes", "hamstrings"],
    loadType: "bodyweight",
    durationOrReps: "10-12 reps",
    cues: ["Ribs stacked over hips", "Press through heels"],
    mistakes: ["Overextending low back", "Feet too far away"],
    contraindications: ["Acute low-back pain (shorten range)"],
    videoUrl: "https://example.com/video/glute-bridges",
    tags: ["glutes", "hips", "tva"],
  },
  {
    id: "band-pull-aparts",
    name: "Band Pull-Aparts",
    category: "activation",
    equipment: ["bands"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Keep neck long", "Squeeze shoulder blades"],
    mistakes: ["Shrugging shoulders", "Bending elbows"],
    contraindications: ["Shoulder irritation (use lighter band)"],
    videoUrl: "https://example.com/video/band-pull-aparts",
    tags: ["scap", "upper-back"],
  },
  {
    id: "scapular-pushups",
    name: "Scapular Push-Ups",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["push", "scapular"],
    muscleGroups: ["serratus", "upper back"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Straight arms", "Push the floor away"],
    mistakes: ["Bending elbows", "Head dropping"],
    contraindications: ["Wrist pain (use fists)"],
    videoUrl: "https://example.com/video/scapular-pushups",
    tags: ["scap", "core"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["core", "anti-extension"],
    muscleGroups: ["core", "hip flexors"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Ribs down", "Slow controlled reach"],
    mistakes: ["Arching low back", "Holding breath"],
    contraindications: ["Acute low-back pain (reduce range)"],
    videoUrl: "https://example.com/video/dead-bug",
    tags: ["tva", "core"],
  },
  {
    id: "dumbbell-rows",
    name: "Dumbbell Rows",
    category: "main",
    equipment: ["dumbbells"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats", "biceps"],
    loadType: "weighted",
    durationOrReps: "8-12 reps",
    cues: ["Spine neutral", "Squeeze mid-back"],
    mistakes: ["Rotating torso", "Pulling with arm only"],
    contraindications: ["Low-back strain (support torso)"],
    videoUrl: "https://example.com/video/dumbbell-rows",
    tags: ["upper-back", "scap"],
  },
  {
    id: "prone-ytw",
    name: "Prone Y-T-W Raises",
    category: "main",
    equipment: ["none"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "bodyweight",
    durationOrReps: "6-8 each",
    cues: ["Small range", "Control the tempo"],
    mistakes: ["Lifting with neck", "Winging shoulders"],
    contraindications: ["Shoulder pain (reduce range)"],
    videoUrl: "https://example.com/video/prone-ytw",
    tags: ["scap", "upper-back"],
  },
  {
    id: "split-stance-row",
    name: "Split Stance Row",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Brace core", "Pull elbow to hip"],
    mistakes: ["Shrugging", "Rotating hips"],
    contraindications: ["Acute shoulder pain"],
    videoUrl: "https://example.com/video/split-stance-row",
    tags: ["scap", "core"],
  },
  {
    id: "incline-pushup",
    name: "Incline Push-Up",
    category: "main",
    equipment: ["bench"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps", "shoulders"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Body in straight line", "Elbows at 45 degrees"],
    mistakes: ["Sagging hips", "Flaring elbows"],
    contraindications: ["Wrist pain (use handles)"],
    videoUrl: "https://example.com/video/incline-pushup",
    tags: ["chest", "core"],
  },
  {
    id: "hip-flexor-stretch",
    name: "Hip Flexor Stretch",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "hips"],
    muscleGroups: ["hip flexors"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Tuck tailbone slightly", "Keep ribs down"],
    mistakes: ["Overarching low back", "Leaning forward"],
    contraindications: ["Knee pain (use padding)"],
    videoUrl: "https://example.com/video/hip-flexor-stretch",
    tags: ["hips"],
  },
  {
    id: "thread-the-needle",
    name: "Thread-the-Needle",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "bodyweight",
    durationOrReps: "5-6 per side",
    cues: ["Breathe into mid-back", "Rotate from upper spine"],
    mistakes: ["Forcing the twist", "Holding breath"],
    contraindications: ["Shoulder pain (reduce range)"],
    videoUrl: "https://example.com/video/thread-the-needle",
    tags: ["t-spine", "scap"],
  },
  {
    id: "chin-tucks",
    name: "Chin Tucks",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "neck"],
    muscleGroups: ["neck"],
    loadType: "bodyweight",
    durationOrReps: "8-10 reps",
    cues: ["Lengthen back of neck", "Keep jaw relaxed"],
    mistakes: ["Tucking too hard", "Looking down"],
    contraindications: ["Cervical pain (light range)"],
    videoUrl: "https://example.com/video/chin-tucks",
    tags: ["neck"],
  },
  {
    id: "doorway-pec-stretch",
    name: "Doorway Pec Stretch",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "chest"],
    muscleGroups: ["chest", "shoulders"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Gentle stretch", "Keep ribs down"],
    mistakes: ["Overextending shoulder", "Arching back"],
    contraindications: ["Shoulder impingement"],
    videoUrl: "https://example.com/video/doorway-pec-stretch",
    tags: ["chest", "shoulders"],
  },
  {
    id: "thoracic-rotation",
    name: "Thoracic Rotation",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Rotate from upper spine", "Keep hips stacked"],
    mistakes: ["Twisting low back", "Rushing"],
    contraindications: ["Acute back pain (small range)"],
    videoUrl: "https://example.com/video/thoracic-rotation",
    tags: ["t-spine"],
  },
  {
    id: "wall-angel-hold",
    name: "Wall Angel Hold",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["mobility", "scapular"],
    muscleGroups: ["upper back", "shoulders"],
    loadType: "timed",
    durationOrReps: "20-30 sec",
    cues: ["Back of arms on wall", "Chin tucked"],
    mistakes: ["Ribs flaring", "Shrugging"],
    contraindications: ["Shoulder pain (shorter hold)"],
    videoUrl: "https://example.com/video/wall-angel-hold",
    tags: ["scap", "t-spine"],
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["core", "anti-rotation"],
    muscleGroups: ["core", "obliques"],
    loadType: "assisted",
    durationOrReps: "8-10 per side",
    cues: ["Brace core", "Hands move straight out"],
    mistakes: ["Rotating torso", "Leaning"],
    contraindications: ["Acute low-back pain (light band)"],
    videoUrl: "https://example.com/video/pallof-press",
    tags: ["core", "tva"],
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["core", "anti-extension"],
    muscleGroups: ["core", "glutes"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Reach long", "Keep hips level"],
    mistakes: ["Arching back", "Twisting hips"],
    contraindications: ["Wrist pain (use forearms)"],
    videoUrl: "https://example.com/video/bird-dog",
    tags: ["core", "tva"],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Elbows high", "Squeeze between shoulder blades"],
    mistakes: ["Leaning back", "Shrugging"],
    contraindications: ["Shoulder irritation (light band)"],
    videoUrl: "https://example.com/video/face-pull",
    tags: ["scap", "upper-back"],
  },
  {
    id: "hamstring-stretch",
    name: "Hamstring Stretch",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "hinge"],
    muscleGroups: ["hamstrings"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Keep spine long", "Soft knee bend"],
    mistakes: ["Rounding back", "Locking knee"],
    contraindications: ["Sciatic pain (gentle range)"],
    videoUrl: "https://example.com/video/hamstring-stretch",
    tags: ["hips", "hamstrings"],
  },
  {
    id: "banded-rows-seated",
    name: "Seated Band Row",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Tall spine", "Pull elbows back"],
    mistakes: ["Rounding shoulders", "Jerking"],
    contraindications: ["Low-back pain (sit on support)"],
    videoUrl: "https://example.com/video/seated-band-row",
    tags: ["upper-back", "scap"],
  },
  {
    id: "side-lying-open-book",
    name: "Side-Lying Open Book",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["mobility", "spine"],
    muscleGroups: ["upper back"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Knees stacked", "Breathe into the stretch"],
    mistakes: ["Letting knees drift", "Holding breath"],
    contraindications: ["Shoulder pain (short range)"],
    videoUrl: "https://example.com/video/open-book",
    tags: ["t-spine"],
  },
  {
    id: "ankle-mobility",
    name: "Ankle Mobility Rocks",
    category: "warmup",
    equipment: ["none"],
    movementPattern: ["mobility", "ankles"],
    muscleGroups: ["ankles", "calves"],
    loadType: "bodyweight",
    durationOrReps: "8-10 per side",
    cues: ["Heel stays down", "Knee tracks over toes"],
    mistakes: ["Heel lifting", "Collapsing arch"],
    contraindications: ["Acute ankle pain"],
    videoUrl: "https://example.com/video/ankle-mobility",
    tags: ["ankles", "hips"],
  },
  {
    id: "banded-lat-stretch",
    name: "Banded Lat Stretch",
    category: "cooldown",
    equipment: ["bands"],
    movementPattern: ["mobility", "lats"],
    muscleGroups: ["lats", "upper back"],
    loadType: "timed",
    durationOrReps: "30 sec per side",
    cues: ["Hips back", "Reach long through arm"],
    mistakes: ["Twisting torso", "Shrugging"],
    contraindications: ["Shoulder pain (gentle range)"],
    videoUrl: "https://example.com/video/banded-lat-stretch",
    tags: ["lats", "t-spine"],
  },
  {
    id: "breathing-90-90",
    name: "90/90 Breathing",
    category: "cooldown",
    equipment: ["none"],
    movementPattern: ["breath", "core"],
    muscleGroups: ["core", "diaphragm"],
    loadType: "timed",
    durationOrReps: "4-6 breaths",
    cues: ["Low ribs soften", "Long exhale"],
    mistakes: ["Chest breathing", "Neck tension"],
    contraindications: ["None"],
    videoUrl: "https://example.com/video/90-90-breathing",
    tags: ["breath", "tva"],
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    category: "main",
    equipment: ["none"],
    movementPattern: ["squat"],
    muscleGroups: ["quads", "glutes"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Sit between hips", "Knees track over toes"],
    mistakes: ["Heels lifting", "Collapsing knees"],
    contraindications: ["Knee pain (reduce depth)"],
    videoUrl: "https://example.com/video/bodyweight-squat",
    tags: ["legs", "squat"],
  },
  {
    id: "split-squat",
    name: "Split Squat",
    category: "main",
    equipment: ["none"],
    movementPattern: ["squat", "single-leg"],
    muscleGroups: ["quads", "glutes"],
    loadType: "bodyweight",
    durationOrReps: "6-10 per side",
    cues: ["Tall torso", "Soft back knee"],
    mistakes: ["Front knee caves in", "Leaning forward"],
    contraindications: ["Knee pain (shorten range)"],
    videoUrl: "https://example.com/video/split-squat",
    tags: ["legs", "squat"],
  },
  {
    id: "hip-hinge-drill",
    name: "Hip Hinge Drill",
    category: "activation",
    equipment: ["none"],
    movementPattern: ["hinge"],
    muscleGroups: ["glutes", "hamstrings"],
    loadType: "bodyweight",
    durationOrReps: "8-10 reps",
    cues: ["Push hips back", "Spine long"],
    mistakes: ["Rounding back", "Bending knees too much"],
    contraindications: ["Low-back pain (shorten range)"],
    videoUrl: "https://example.com/video/hip-hinge-drill",
    tags: ["hinge", "posterior"],
  },
  {
    id: "single-leg-rdl",
    name: "Single-Leg RDL (Bodyweight)",
    category: "main",
    equipment: ["none"],
    movementPattern: ["hinge", "single-leg"],
    muscleGroups: ["glutes", "hamstrings", "core"],
    loadType: "bodyweight",
    durationOrReps: "6-8 per side",
    cues: ["Hips square", "Reach long"],
    mistakes: ["Opening hips", "Rounding back"],
    contraindications: ["Balance issues (use support)"],
    videoUrl: "https://example.com/video/single-leg-rdl",
    tags: ["hinge", "balance"],
  },
  {
    id: "pushup",
    name: "Push-Up",
    category: "main",
    equipment: ["none"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps", "shoulders"],
    loadType: "bodyweight",
    durationOrReps: "6-12 reps",
    cues: ["Body in one line", "Elbows 30-45°"],
    mistakes: ["Sagging hips", "Flaring elbows"],
    contraindications: ["Wrist pain (use handles)"],
    videoUrl: "https://example.com/video/pushup",
    tags: ["push", "upper"],
  },
  {
    id: "pike-pushup",
    name: "Pike Push-Up",
    category: "main",
    equipment: ["none"],
    movementPattern: ["push"],
    muscleGroups: ["shoulders", "triceps"],
    loadType: "bodyweight",
    durationOrReps: "6-10 reps",
    cues: ["Hips high", "Head between arms"],
    mistakes: ["Shrugging shoulders", "Partial range"],
    contraindications: ["Shoulder pain (reduce range)"],
    videoUrl: "https://example.com/video/pike-pushup",
    tags: ["push", "shoulders"],
  },
  {
    id: "reverse-snow-angel",
    name: "Reverse Snow Angels",
    category: "main",
    equipment: ["none"],
    movementPattern: ["pull", "scapular"],
    muscleGroups: ["upper back", "rear delts"],
    loadType: "bodyweight",
    durationOrReps: "8-12 reps",
    cues: ["Thumbs up", "Sweep wide"],
    mistakes: ["Shrugging", "Rushing"],
    contraindications: ["Shoulder pain (short range)"],
    videoUrl: "https://example.com/video/reverse-snow-angel",
    tags: ["pull", "scap"],
  },
  {
    id: "plank",
    name: "Plank",
    category: "main",
    equipment: ["none"],
    movementPattern: ["core", "anti-extension"],
    muscleGroups: ["core", "shoulders"],
    loadType: "timed",
    durationOrReps: "30-45 sec",
    cues: ["Ribs down", "Glutes tight"],
    mistakes: ["Sagging hips", "Holding breath"],
    contraindications: ["Shoulder pain (shorten)"],
    videoUrl: "https://example.com/video/plank",
    tags: ["core", "stability"],
  },
  {
    id: "band-chest-press",
    name: "Band Chest Press",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["push"],
    muscleGroups: ["chest", "triceps"],
    loadType: "assisted",
    durationOrReps: "8-12 reps",
    cues: ["Brace core", "Press straight"],
    mistakes: ["Ribs flaring", "Shoulders shrugging"],
    contraindications: ["Shoulder pain (light band)"],
    videoUrl: "https://example.com/video/band-chest-press",
    tags: ["push", "band"],
  },
  {
    id: "band-row",
    name: "Band Row",
    category: "main",
    equipment: ["bands"],
    movementPattern: ["pull"],
    muscleGroups: ["upper back", "lats"],
    loadType: "assisted",
    durationOrReps: "10-12 reps",
    cues: ["Elbows back", "Tall spine"],
    mistakes: ["Leaning back", "Shrugging"],
    contraindications: ["Shoulder pain (light band)"],
    videoUrl: "https://example.com/video/band-row",
    tags: ["pull", "band"],
  },
];

const normalizeId = (id?: string) => (id ?? "").trim().toLowerCase();

export const exerciseById = (id?: string) => {
  const normalized = normalizeId(id);
  if (!normalized) return undefined;
  return exercises.find((exercise) => normalizeId(exercise.id) === normalized);
};
