import { describe, expect, it } from "vitest";
import {
  PRODUCTION_LONGITUDINAL_ACTIONS,
  PRODUCTION_LONGITUDINAL_ACTION_OWNERS,
  PRODUCTION_LONGITUDINAL_ADAPTATION_ACTIVATION_STATUS,
  PRODUCTION_LONGITUDINAL_ADAPTATION_CONTRACT_REFERENCE,
  PRODUCTION_LONGITUDINAL_ADAPTATION_KERNEL_STATUS,
  PRODUCTION_LONGITUDINAL_OUTCOME_SOURCE_CONTRACT_REFERENCE,
  PRODUCTION_LONGITUDINAL_PRESCRIPTION_DIMENSIONS,
  PRODUCTION_LONGITUDINAL_REALIZATION_DIFFERENCES,
  PRODUCTION_LONGITUDINAL_STATES,
  PRODUCTION_LONGITUDINAL_TARGET_SCOPES,
} from "../../src/longitudinalAdaptation";
import {
  CAGT_EFFECTIVE_AUTHORITY_REGISTRY_V6,
  validateEffectiveAuthorityRegistryV6,
} from "../cagt/effectiveAuthorityRegistryV6";

describe("production Longitudinal contracts", () => {
  it("locks version, inactive status, and Registry V6 authority", () => {
    expect(PRODUCTION_LONGITUDINAL_ADAPTATION_CONTRACT_REFERENCE).toEqual({
      contractId: "PRODUCTION_LONGITUDINAL_ADAPTATION_KERNEL", contractVersion: "1.0.0",
    });
    expect(PRODUCTION_LONGITUDINAL_OUTCOME_SOURCE_CONTRACT_REFERENCE).toEqual({
      contractId: "PRODUCTION_LONGITUDINAL_OUTCOME_SOURCE_CONTRACT", contractVersion: "1.0.0",
    });
    expect(PRODUCTION_LONGITUDINAL_ADAPTATION_KERNEL_STATUS)
      .toBe("PRODUCTION_LONGITUDINAL_ADAPTATION_KERNEL_IMPLEMENTED_NOT_ACTIVATED");
    expect(PRODUCTION_LONGITUDINAL_ADAPTATION_ACTIVATION_STATUS).toBe("NOT_ACTIVATED");
    expect(validateEffectiveAuthorityRegistryV6(CAGT_EFFECTIVE_AUTHORITY_REGISTRY_V6)).toEqual([]);
    expect(CAGT_EFFECTIVE_AUTHORITY_REGISTRY_V6.gates.gate_16_longitudinal_adaptation.exactAuthority)
      .toBe("PRODUCTION_KERNEL_AUTHORITY");
  });

  it("uses closed target, state, action, owner, dimension, and difference vocabularies", () => {
    expect(PRODUCTION_LONGITUDINAL_TARGET_SCOPES).toHaveLength(10);
    expect(PRODUCTION_LONGITUDINAL_STATES).toHaveLength(17);
    expect(PRODUCTION_LONGITUDINAL_ACTIONS).toHaveLength(14);
    expect(PRODUCTION_LONGITUDINAL_ACTION_OWNERS).toHaveLength(8);
    expect(PRODUCTION_LONGITUDINAL_PRESCRIPTION_DIMENSIONS).toHaveLength(20);
    expect(PRODUCTION_LONGITUDINAL_REALIZATION_DIFFERENCES).toHaveLength(20);
  });
});
