import { defineCuratedEntry, fact } from "./shared";

const entry = defineCuratedEntry;

export const LOWER_BODY_ACCESSORY_KNOWLEDGE_ENTRIES = Object.freeze([
  entry({
    exerciseId: "goblet-squat", canonicalName: "Goblet Squat",
    legacySummary: "Dumbbell-loaded squat pattern.",
    focus: fact("Use only the squat range you can control with the dumbbell held securely.", { compact: "Use range you can own" }),
    cues: [fact("Keep pressure across the whole foot through the squat.", { compact: "Keep pressure through whole foot" }), fact("Keep the dumbbell close to the front of the torso.")],
    setup: [fact("Stand in a stable stance and hold one dumbbell securely at the front of the torso."), fact("Choose the prescribed stance and clear the space before descending."), fact("A dumbbell and stable standing surface are required; this is not a bodyweight-squat identity.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Lower through the hips and knees while maintaining the selected foot pressure."), fact("Stand by driving through the feet without changing the dumbbell hold.")],
    pattern: "A goblet squat is a dumbbell-loaded bilateral squat with the implement held in front of the torso.",
    watchFor: [fact("Watch for the dumbbell drifting away from its secure front position."), fact("Watch for depth increasing after foot pressure or trunk control changes.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing", "resistance.free-implement", "path.bilateral-squat"], roles: ["squat", "knee_dominant"], actions: [], stress: ["heavy_axial_loading"], painTopics: ["knee-response-context", "hip-response-context"], unresolvedClaims: ["Supported and box-target goblet realizations require explicit production metadata before Knowledge overrides are admitted."],
  }),
  entry({
    exerciseId: "leg-press", canonicalName: "Leg Press",
    legacySummary: "Machine-guided bilateral squat pattern.",
    focus: fact("Control the platform through the selected depth.", { compact: "Control depth" }),
    cues: [fact("Keep the load within the range you can control.", { compact: "Do not chase load past owned range" }), fact("Keep the feet in consistent contact with the platform.")],
    setup: [fact("Adjust the seat, back support, platform position, and start mechanism for the exact leg-press machine."), fact("Set the load and place both feet securely before releasing the machine stops."), fact("An exact leg-press machine capability is required; it is not interchangeable with a squat.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Bend the hips and knees through the prescribed range while the pelvis remains supported."), fact("Press the platform away and re-engage the machine stop only from a controlled position.", { kind: "safety_boundary" })],
    pattern: "A leg press is a supported machine-guided bilateral knee-dominant task with machine-specific geometry.",
    watchFor: [fact("Watch for the pelvis lifting or sliding as depth increases."), fact("Watch for uncontrolled contact with the machine stops or end range.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.seated-machine", "resistance.machine-guided", "fit.machine-specific"], roles: ["knee_dominant"], actions: [], stress: [], painTopics: ["knee-response-context", "hip-response-context"], unresolvedClaims: ["No alternate leg-press geometry is accepted without an exact machine capability review."],
  }),
  entry({
    exerciseId: "bodyweight-box-squat", canonicalName: "Bodyweight Box Squat",
    legacySummary: "Supported squat pattern to a box.",
    focus: fact("Reach the same controlled box target on each repetition.", { compact: "Sit to a consistent target" }),
    cues: [fact("Stand while maintaining pressure across the whole foot.", { compact: "Stand with whole-foot pressure" }), fact("Touch the box without collapsing onto it.")],
    setup: [fact("Place a stable box at the prescribed height on a clear floor."), fact("Stand in front of the box with the selected stance and confirm its location before descending."), fact("A stable box is part of this identity; free bodyweight squatting is not implied.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Lower under control until the box contact confirms the target."), fact("Reverse from the box without rocking or using a drop-and-bounce.")],
    pattern: "A bodyweight box squat is a bilateral squat in which controlled box contact provides the required target.",
    watchFor: [fact("Watch for dropping the last part of the descent onto the box."), fact("Watch for rocking backward before standing.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing-to-box", "resistance.bodyweight", "path.bilateral-squat"], roles: ["squat", "knee_dominant"], actions: [], stress: [], painTopics: ["knee-response-context", "hip-response-context"], unresolvedClaims: ["The identity boundary between box contact and a free bodyweight squat remains deferred for owner review."],
  }),
  entry({
    exerciseId: "dumbbell-romanian-deadlift", canonicalName: "Dumbbell Romanian Deadlift",
    legacySummary: "Loaded hinge emphasizing hamstrings and glutes.",
    focus: fact("Send the hips backward to begin the hinge.", { compact: "Hips back" }),
    cues: [fact("Keep the dumbbells close to the body.", { compact: "Keep load close" }), fact("End the lowering range before the selected trunk position changes.", { compact: "Stop before spine position changes" })],
    setup: [fact("Stand with one dumbbell in each hand and enough clear space to hinge."), fact("Set a stable bilateral stance with the dumbbells controlled beside the thighs."), fact("This loaded hinge requires dumbbells; reaching the floor is not an equipment or range requirement.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Move the hips back while the dumbbells travel close to the legs."), fact("Return to standing by extending the hips without adding a backward lean.")],
    pattern: "A dumbbell Romanian deadlift is a loaded bilateral hinge whose range is bounded by maintained control.",
    watchFor: [fact("Watch for the dumbbells drifting forward away from the body."), fact("Watch for turning the lowering phase into a squat or reaching farther after the hinge changes.")],
    compactCoachingRefs: ["focus", "cue.1", "cue.2"], mechanics: ["support.standing", "resistance.free-implement", "path.hinge"], roles: ["hinge"], actions: [], stress: ["loaded_hinge"], painTopics: ["hip-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "cable-pull-through", canonicalName: "Cable Pull-Through",
    legacySummary: "Cable hinge pattern with posterior loading.",
    focus: fact("Let the hips travel backward against the cable line.", { compact: "Let hips move back" }),
    cues: [fact("Finish standing without leaning past upright.", { compact: "Finish tall without overextending" }), fact("Keep the rope path clear between the legs.")],
    setup: [fact("Attach a rope to a low cable and face away from the stack."), fact("Take the rope between the legs, step forward under control, and establish a stable stance."), fact("A cable stack with a low rope path is required; cable load is not converted to another implement.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Hinge back while the cable remains behind the body."), fact("After the final repetition, walk the rope back toward the stack before releasing it.", { kind: "safety_boundary" })],
    pattern: "A cable pull-through is a bilateral hinge loaded from a low cable behind the body.",
    watchFor: [fact("Watch for bending mainly through the knees until the movement becomes a squat."), fact("Watch for stepping or releasing the rope while the cable is still pulling strongly.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing", "resistance.cable-anchored", "path.posterior-hinge"], roles: ["hinge"], actions: [], stress: ["loaded_hinge"], painTopics: ["hip-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "split-squat", canonicalName: "Split Squat",
    legacySummary: "Unilateral lower-body squat pattern.",
    focus: fact("Use stable support when balance would otherwise replace the leg task.", { compact: "Use support if balance dominates" }),
    cues: [fact("Control the selected depth before adding load.", { compact: "Own depth before load" }), fact("Keep the stationary split stance through the repetition.")],
    setup: [fact("Establish the prescribed split stance and working side before descending."), fact("Set any support contact or dumbbell load before the first repetition."), fact("The base identity is a stationary split stance; a backward step is not a split-squat realization.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Lower through both knees while keeping the feet in their established positions."), fact("Stand through the prescribed side without turning the repetition into a step.")],
    pattern: "A split squat is a stationary side-specific lower-body squat pattern with modifiable support and load.",
    watchFor: [fact("Watch for the stance shortening or widening during the set."), fact("Watch for balance corrections replacing the intended lowering and standing path.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "supported", realizationId: "stable-support", facts: [
        { suffix: "setup", category: "setup", statement: "For the supported realization, place the hand on a stable surface before loading the stance." },
        { suffix: "during", category: "during", statement: "Use the support for balance without pushing through it to create the repetition." },
      ] },
      { id: "dumbbell", realizationId: "dumbbell-loaded", facts: [
        { suffix: "setup", category: "setup", statement: "For the dumbbell-loaded realization, establish the split stance before lifting or settling the dumbbells." },
        { suffix: "watch", category: "watchFor", statement: "Watch for the dumbbells pulling the stance out of its selected position." },
      ] },
    ], mechanics: ["support.split-stance", "support.prescription-modifiable", "laterality.prescription-side"], roles: ["single_leg", "knee_dominant"], actions: [], stress: [], painTopics: ["knee-response-context", "hip-response-context"], unresolvedClaims: ["Reverse lunge remains a separate unresolved identity boundary rather than a split-squat override."],
  }),
  entry({
    exerciseId: "step-up", canonicalName: "Step-Up",
    legacySummary: "Unilateral lower-body step pattern.",
    focus: fact("Control the return from the step instead of dropping to the floor.", { compact: "Control the descent" }),
    cues: [fact("Use a step height that keeps the full repetition controlled.", { compact: "Match box height to owned range" }), fact("Keep the working foot securely on the step.")],
    setup: [fact("Place a stable step or box on a clear non-slip surface."), fact("Set the working foot fully on the step and establish any support or load before moving."), fact("A stable step or box is required; height is a prescription fact rather than a universal target.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Step up through the working side while keeping the foot connected to the surface."), fact("Return to the floor under control without relying on a push from the trailing leg.")],
    pattern: "A step-up is a dynamic side-specific lower-body task defined by stepping onto and returning from a stable surface.",
    watchFor: [fact("Watch for the trailing leg supplying most of the upward push."), fact("Watch for the foot losing full contact or the box shifting.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "supported", realizationId: "stable-support", facts: [
        { suffix: "setup", category: "setup", statement: "For the supported realization, establish a secure hand contact before stepping up." },
        { suffix: "during", category: "during", statement: "Use the hand contact for balance while the working leg performs the step." },
      ] },
      { id: "dumbbell", realizationId: "dumbbell-loaded", facts: [
        { suffix: "setup", category: "setup", statement: "For the dumbbell-loaded realization, control the implements before placing the working foot on the step." },
        { suffix: "watch", category: "watchFor", statement: "Watch for the implements swinging as direction changes at the top or floor." },
      ] },
    ], mechanics: ["support.step-surface", "support.prescription-modifiable", "laterality.prescription-side"], roles: ["single_leg", "knee_dominant"], actions: [], stress: [], painTopics: ["knee-response-context", "hip-response-context"],
  }),
  entry({
    exerciseId: "lying-leg-curl", canonicalName: "Lying Leg Curl",
    legacySummary: "Machine hamstring knee-flexion isolation.",
    focus: fact("Control the machine through the full return.", { compact: "Control the return" }),
    cues: [fact("Keep the hips settled against the support.", { compact: "Keep hips settled" }), fact("Maintain the lower-leg pad contact through the curl.")],
    setup: [fact("Adjust the lying leg-curl machine so the knee and lower-leg pad match its fit controls."), fact("Set the load and start range before lying into the support."), fact("An exact lying leg-curl machine is required; machine geometries are not generalized.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Bend the knees to move the pad through the selected range."), fact("Lower the pad under control without letting the stack or plates drop.")],
    pattern: "A lying leg curl is a supported machine-guided direct knee-flexion accessory.",
    watchFor: [fact("Watch for the hips lifting from the pad to finish the curl."), fact("Watch for losing lower-leg contact or dropping the return.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.prone-machine", "resistance.machine-guided", "action.knee-flexion"], roles: ["accessory"], actions: ["knee_flexion"], stress: [], painTopics: ["knee-response-context"],
  }),
  entry({
    exerciseId: "glute-bridge", canonicalName: "Glute Bridge",
    legacySummary: "Supine hip-extension glute exercise.",
    focus: fact("Finish the bridge through hip extension without leaning into the low back.", { compact: "Finish with glutes, not low back" }),
    cues: [fact("Keep both feet planted through the prescribed range."), fact("Lower the pelvis under control before the next repetition.")],
    setup: [fact("Lie on the back with both feet placed securely on the floor."), fact("Set the bilateral foot position and any approved load before lifting the pelvis."), fact("The base identity is a bilateral floor-supported bridge; single-leg support is not yet accepted.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Extend the hips until the selected bridge position is reached."), fact("Return the pelvis to the floor without shifting onto one side.")],
    pattern: "A glute bridge is a bilateral floor-supported hip-extension accessory with optional reviewed resistance.",
    watchFor: [fact("Watch for the pelvis tipping or rotating as it rises."), fact("Watch for extending farther by arching the trunk after hip motion has finished.")],
    compactCoachingRefs: ["focus"], overrides: [
      { id: "dumbbell", realizationId: "dumbbell-loaded", facts: [
        { suffix: "setup", category: "setup", statement: "For the dumbbell-loaded realization, position and hold the dumbbell securely across the front of the pelvis before lifting." },
        { suffix: "watch", category: "watchFor", statement: "Watch for the dumbbell shifting during the lift or lowering phase." },
      ] },
      { id: "loop-band", realizationId: "loop-band-loaded", facts: [
        { suffix: "setup", category: "setup", statement: "For the loop-band realization, place the intact band at the prescribed position before setting the feet." },
        { suffix: "during", category: "during", statement: "Maintain the prescribed band path without changing the bilateral bridge task." },
      ] },
    ], mechanics: ["support.supine-floor", "resistance.bodyweight-or-approved-load", "action.hip-extension"], roles: ["accessory"], actions: ["hip_extension"], stress: [], painTopics: ["hip-response-context", "lumbar-response-context"], unresolvedClaims: ["A unilateral glute-bridge identity or realization remains deferred for owner review."],
  }),
  entry({
    exerciseId: "dumbbell-lateral-raise", canonicalName: "Dumbbell Lateral Raise",
    legacySummary: "Dumbbell side-delt isolation.",
    focus: fact("Lead the outward arm path with a soft elbow position.", { compact: "Lead with elbows softly" }),
    cues: [fact("Stay within a shoulder range that remains comfortable and controlled.", { compact: "Stay in comfortable range" }), fact("Keep the dumbbells from gaining momentum.")],
    setup: [fact("Stand in clear space with one dumbbell in each hand."), fact("Choose a small consistent elbow bend and the prescribed start position."), fact("Dumbbells are required; no fixed thumb orientation or exact arm angle is implied.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Raise the arms outward through the selected range without changing the elbow bend."), fact("Lower the dumbbells under control to the same start position.")],
    pattern: "A dumbbell lateral raise is a free-implement shoulder-abduction accessory.",
    watchFor: [fact("Watch for trunk swing starting the arm movement."), fact("Watch for an early shoulder shrug replacing the outward path.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing", "resistance.free-implement", "action.shoulder-abduction"], roles: ["accessory"], actions: ["shoulder_abduction"], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "reverse-pec-deck", canonicalName: "Reverse Pec Deck",
    legacySummary: "Machine-supported rear-delt and upper-back isolation.",
    focus: fact("Move through the rear-delt and shoulder-blade path without using the neck.", { compact: "Move shoulder blades and rear delts, not neck" }),
    cues: [fact("Keep the chest connected to the machine support."), fact("Use a consistent elbow position as the arms open.")],
    setup: [fact("Adjust the seat, chest support, and handles for the exact reverse-pec-deck machine."), fact("Set the load and reviewed start position before taking both handles."), fact("An exact reverse-pec-deck capability is required; this is not a row machine.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Open the arms through the machine path while the torso remains supported."), fact("Return under control without letting the machine arms or stack drop.")],
    pattern: "A reverse pec deck is a machine-supported shoulder horizontal-abduction and rear-delt accessory, not a row.",
    watchFor: [fact("Watch for bending the elbows further until the task becomes a pull."), fact("Watch for the shoulders lifting toward the neck to finish the range.")],
    compactCoachingRefs: ["focus"], mechanics: ["support.seated-machine", "resistance.machine-guided", "action.shoulder-horizontal-abduction"], roles: ["scapular_control"], actions: ["shoulder_horizontal_abduction", "scapular_retraction"], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "band-face-pull", canonicalName: "Band Face Pull",
    legacySummary: "Anchored-band rear-delt and scapular-control exercise.",
    focus: fact("Pull toward the face without lifting the shoulders.", { compact: "Pull toward face without shrugging" }),
    cues: [fact("Keep the anchor line and band path steady."), fact("Control the hands forward as the band lengthens.")],
    setup: [fact("Attach an intact band to the prescribed anchor height and face the line of pull."), fact("Take a stable stance with equal initial band tension in both hands."), fact("A secure environmental anchor is required; no anchorless face-pull path is implied.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Draw the hands toward the face along the reviewed line without turning the task into a row."), fact("Return the band under control while keeping its path away from the face.", { kind: "safety_boundary" })],
    pattern: "A band face pull is an anchored rear-delt and shoulder-control accessory with a face-directed line of pull.",
    watchFor: [fact("Watch for the anchor or stance moving under tension."), fact("Watch for the elbows dropping until the movement becomes a horizontal row.")],
    compactCoachingRefs: ["focus"], mechanics: ["support.standing", "resistance.band-anchored", "action.scapular-retraction-external-rotation"], roles: ["scapular_control"], actions: ["scapular_retraction", "shoulder_external_rotation"], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "dumbbell-curl", canonicalName: "Dumbbell Curl",
    legacySummary: "Dumbbell elbow-flexion accessory.",
    focus: fact("Lower the dumbbells under control after each curl.", { compact: "Control the lowering" }),
    cues: [fact("Keep the torso from swinging to move the dumbbells.", { compact: "Do not swing" }), fact("Keep the upper-arm path steady through the repetition.")],
    setup: [fact("Stand in clear space with the prescribed dumbbell count held securely."), fact("Set the wrist and upper-arm position before bending the elbows."), fact("Dumbbells are required; bilateral or alternating timing follows Prescription rather than a new identity.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Bend the elbows to raise the dumbbells without moving the shoulders forward."), fact("Return to the start under control before beginning the next repetition.")],
    pattern: "A dumbbell curl is a free-implement direct elbow-flexion accessory.",
    watchFor: [fact("Watch for trunk swing creating the first part of the curl."), fact("Watch for the upper arms drifting forward to finish the movement.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing", "resistance.free-implement", "action.elbow-flexion"], roles: ["accessory"], actions: ["elbow_flexion"], stress: [], painTopics: ["elbow-response-context", "wrist-response-context"],
  }),
  entry({
    exerciseId: "cable-triceps-pressdown", canonicalName: "Cable Triceps Pressdown",
    legacySummary: "Cable elbow-extension accessory.",
    focus: fact("Keep the upper arm steady while the elbow straightens.", { compact: "Keep upper arm still" }),
    cues: [fact("Finish the pressdown without rolling the shoulder forward.", { compact: "Finish without shoulder roll" }), fact("Control the attachment back to the start.")],
    setup: [fact("Set a high cable anchor and the reviewed pressdown attachment."), fact("Take a stable stance and bring the attachment to the start position before loading the repetition."), fact("A cable stack with a high anchor is required; no attachment is treated as universally superior.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Straighten the elbows while the upper arms remain in their selected position."), fact("Bend the elbows under control without letting the stack drop.")],
    pattern: "A cable triceps pressdown is a high-cable direct elbow-extension accessory.",
    watchFor: [fact("Watch for the shoulders moving forward to finish the pressdown."), fact("Watch for bodyweight pushing the attachment down instead of elbow extension.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing", "resistance.cable-anchored", "action.elbow-extension"], roles: ["accessory"], actions: ["elbow_extension"], stress: [], painTopics: ["elbow-response-context", "shoulder-response-context"],
  }),
  entry({
    exerciseId: "standing-calf-raise", canonicalName: "Standing Calf Raise",
    legacySummary: "Equipment-neutral standing ankle plantar-flexion accessory exercise.",
    focus: fact("Rise through the ball of the foot with a controlled ankle path.", { compact: "Rise through the ball of the foot" }),
    cues: [fact("Return through the selected range under control.", { compact: "Control the full return" }), fact("Keep any support contact light enough to preserve the calf-raise task.")],
    setup: [fact("Stand on a stable surface with the prescribed stance and foot position."), fact("Establish any hand support or dumbbell load before rising."), fact("Bodyweight is the base realization; external load and support require their prescribed setup.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Raise the heels without bouncing at the bottom or top."), fact("Lower until the prescribed range is complete and the next repetition can begin steadily.")],
    pattern: "A standing calf raise is a standing ankle plantar-flexion accessory with explicit support and load realizations.",
    watchFor: [fact("Watch for bouncing to reverse direction."), fact("Watch for the ankles rolling away from the selected foot path.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "supported", realizationId: "stable-support", facts: [
        { suffix: "setup", category: "setup", statement: "For the supported realization, establish a stable hand contact before rising." },
        { suffix: "during", category: "during", statement: "Use the support for balance without lifting the body through the arms." },
      ] },
      { id: "dumbbell", realizationId: "dumbbell-loaded", facts: [
        { suffix: "setup", category: "setup", statement: "For the dumbbell-loaded realization, secure the implement and support plan before beginning." },
        { suffix: "watch", category: "watchFor", statement: "Watch for the dumbbell changing the selected stance or ankle path." },
      ] },
    ], mechanics: ["support.standing", "support.prescription-modifiable", "action.ankle-plantar-flexion"], roles: ["accessory"], actions: ["ankle_plantar_flexion"], stress: ["grip_loading"], painTopics: ["ankle-response-context"], unresolvedClaims: ["A unilateral realization remains unadmitted until side ownership is explicit in production metadata."],
  }),
]);
