import { defineCuratedEntry, fact } from "./shared";

const entry = defineCuratedEntry;

export const PREPARATION_PRESSING_PULLING_KNOWLEDGE_ENTRIES = Object.freeze([
  entry({
    exerciseId: "ninety-ninety-breathing", canonicalName: "90/90 Breathing",
    legacySummary: "Supine breathing drill for ribcage and pelvis position.",
    focus: fact("Complete a relaxed exhale without forcing the next breath.", { compact: "Exhale fully" }),
    cues: [fact("Let the ribs settle over the pelvis as you breathe.", { compact: "Keep ribs stacked over pelvis" }), fact("Keep the face and neck relaxed while air moves.")],
    setup: [fact("Lie on your back with the hips and knees supported in a comfortable bent position."), fact("Rest the head, back, and pelvis on the floor before beginning the breath cycle."), fact("Use open floor space; no external load is part of this breathing position.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Breathe out smoothly and allow the next inhale to arrive without a forced count."), fact("Keep the supported position quiet through each prescribed breath cycle.")],
    pattern: "This is a supported breath-cycle task that coordinates breathing with a steady supine position.",
    watchFor: [fact("Watch for straining through the neck or face."), fact("Watch for rushing the breath or losing the supported position.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.supine", "support.substantial", "dose.breath-cycles"], roles: ["breathing_position", "anti_extension_core"], actions: [], stress: [],
  }),
  entry({
    exerciseId: "serratus-wall-slide", canonicalName: "Serratus Wall Slide",
    legacySummary: "Wall-supported scapular upward-rotation and serratus control drill.",
    focus: fact("Reach upward along the wall without turning the movement into a shrug.", { compact: "Reach without shrugging" }),
    cues: [fact("Keep the trunk quiet as the arms slide.", { compact: "Keep ribs quiet" }), fact("Use only the arm range that stays smooth against the wall.")],
    setup: [fact("Stand facing the wall with both feet stable and the forearms or hands placed for the reviewed wall-slide path."), fact("Start with light wall contact and enough space to slide upward."), fact("A stable wall is required for this supported drill.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Slide upward while allowing the shoulder blades to rotate with the reach."), fact("Return along the wall under control without forcing the lowest position.")],
    pattern: "A wall slide coordinates arm elevation with controlled shoulder-blade upward rotation and reach.",
    watchFor: [fact("Watch for the shoulders lifting early toward the ears."), fact("Watch for the trunk leaning back to create extra arm range.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing", "support.wall", "scapular.upward-rotation"], roles: ["scapular_control"], actions: ["scapular_upward_rotation"], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "dead-bug", canonicalName: "Dead Bug",
    legacySummary: "Supine anti-extension core drill.",
    focus: fact("Move the prescribed limbs while keeping the chosen trunk position steady.", { compact: "Move limbs without losing spine position" }),
    cues: [fact("Reach only as far as the trunk position stays controlled."), fact("Return each limb before beginning the next prescribed reach.")],
    setup: [fact("Lie on your back and bring the arms and legs to the prescribed start position."), fact("Set a comfortable trunk position without forcing the back flat."), fact("Use clear floor space without external load.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Move the selected arm, leg, or opposite pair away from the body with control."), fact("Bring the limbs back without using momentum or changing the chosen trunk position.")],
    pattern: "Dead bug is a floor-supported anti-extension task in which limb motion increases the trunk-control demand.",
    watchFor: [fact("Watch for reaching farther after the trunk position begins to change."), fact("Watch for rushing the return or holding the breath unintentionally.")],
    compactCoachingRefs: ["focus"], mechanics: ["support.supine", "resistance.bodyweight", "trunk.anti-extension"], roles: ["anti_extension_core"], actions: [], stress: ["long_lever_core"], painTopics: ["lumbar-response-context"],
  }),
  entry({
    exerciseId: "push-up", canonicalName: "Push-Up",
    legacySummary: "Bodyweight horizontal push.",
    focus: fact("Push the support away until the body returns to the selected start position.", { compact: "Press the floor away" }),
    cues: [fact("Keep the trunk organized as one supported line.", { compact: "Keep trunk organized" }), fact("Use a hand position and depth that keep the press controlled.")],
    setup: [fact("Place both hands securely on the selected floor, wall, or elevated support."), fact("Choose the approved support height or knee position before loading the arms."), fact("The support surface must be stable and match the prescribed realization.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Lower the body toward the support through the prescribed range."), fact("Press back without letting one side leave the support early.")],
    pattern: "A push-up is a bodyweight horizontal press whose lever and support height can change within approved realizations.",
    watchFor: [fact("Watch for the support shifting under the hands."), fact("Watch for the trunk losing its selected line before the arms finish the repetition.")],
    compactCoachingRefs: ["focus", "cue.1"],
    overrides: [
      { id: "wall", realizationId: "wall-supported", facts: [
        { suffix: "setup", category: "setup", statement: "For the wall realization, place both hands on a stable wall and step back to the prescribed body angle." },
        { suffix: "during", category: "during", statement: "Move the body toward and away from the wall as one controlled line." },
      ] },
      { id: "elevated", realizationId: "elevated-support", facts: [
        { suffix: "setup", category: "setup", statement: "For the elevated realization, verify the raised support cannot slide or tip before loading it." },
        { suffix: "watch", category: "watchFor", statement: "Watch for the torso contacting an edge or the support moving during the repetition." },
      ] },
      { id: "knees", realizationId: "knee-supported", facts: [
        { suffix: "setup", category: "setup", statement: "For the knee-supported realization, place the knees comfortably and establish the shortened body line before lowering." },
        { suffix: "during", category: "during", statement: "Move from the knees through the trunk and shoulders as one shortened lever." },
      ] },
    ],
    mechanics: ["support.prone", "support.prescription-modifiable", "resistance.bodyweight"], roles: ["horizontal_push", "anti_extension_core"], actions: [], stress: ["long_lever_core"], painTopics: ["shoulder-response-context", "wrist-response-context"], unresolvedClaims: ["External-load push-up realization remains outside the current accepted production boundary."],
  }),
  entry({
    exerciseId: "dumbbell-bench-press", canonicalName: "Dumbbell Bench Press",
    legacySummary: "Bench-supported horizontal press with external loading.",
    focus: fact("Lower the dumbbells only through the range you can control against the bench.", { compact: "Control the bottom range" }),
    cues: [fact("Press without the shoulders sliding toward the end of the bench.", { compact: "Press without shoulder glide" }), fact("Keep each dumbbell balanced over its forearm.")],
    setup: [fact("Set a stable flat or approved adjustable bench before picking up the dumbbells."), fact("Sit, position the dumbbells securely, and establish head, upper-back, and foot support before pressing."), fact("This identity requires dumbbells and a proven bench; it is not a floor or barbell press.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Lower both dumbbells with control while keeping the forearms organized under them."), fact("Finish the set by bringing the dumbbells to a controlled supported position before sitting up.", { kind: "safety_boundary" })],
    pattern: "A dumbbell bench press is a bench-supported free-implement horizontal press.",
    watchFor: [fact("Watch for one dumbbell descending faster than the other."), fact("Watch for a rushed start or finish that leaves either dumbbell uncontrolled.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [{ id: "incline", realizationId: "adjustable-bench-incline", facts: [
      { suffix: "setup", category: "setup", statement: "For an approved inclined realization, lock the adjustable bench at the prescribed angle before handling the dumbbells." },
      { suffix: "during", category: "during", statement: "Follow the angled press path without treating bench angle as a separate exercise identity." },
    ] }],
    mechanics: ["support.supine-bench", "resistance.free-implement", "path.horizontal-press"], roles: ["horizontal_push"], actions: [], stress: [], painTopics: ["shoulder-response-context", "elbow-response-context"],
  }),
  entry({
    exerciseId: "machine-chest-press", canonicalName: "Machine Chest Press",
    legacySummary: "Machine-guided horizontal press.",
    focus: fact("Adjust the seat so the handles begin on a comfortable controlled press path.", { compact: "Set seat to comfortable shoulder path" }),
    cues: [fact("Keep the back connected to the selected support."), fact("Press and return without striking the machine stops.")],
    setup: [fact("Adjust the seat and start position for the exact chest-press machine."), fact("Select the load and place both feet securely before taking the handles."), fact("An exact chest-press machine capability is required; machine geometries are not interchangeable.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Press through the machine path without leaving the chosen support position."), fact("Return the handles under control to the reviewed start range.")],
    pattern: "A machine chest press is a supported horizontal press constrained by the specific machine path.",
    watchFor: [fact("Watch for a seat position that starts the handles outside the intended range."), fact("Watch for the torso lifting away from the support to finish the press.")],
    compactCoachingRefs: ["focus"], overrides: [{ id: "fixed-incline-machine", realizationId: "fixed-machine-incline", facts: [
      { suffix: "setup", category: "setup", statement: "For the fixed incline realization, verify the exact incline-chest-press capability and adjust its seat and start position before loading." },
      { suffix: "during", category: "during", statement: "Follow the fixed inclined machine path without treating its angle as another exercise identity or an upper-chest guarantee." },
    ] }], mechanics: ["support.seated-machine", "resistance.machine-guided", "fit.machine-specific"], roles: ["horizontal_push"], actions: [], stress: [], painTopics: ["shoulder-response-context"], unresolvedClaims: ["Only the exact fixed-machine-incline realization is accepted; other selectorized or plate-loaded geometries still require review."],
  }),
  entry({
    exerciseId: "cable-chest-fly", canonicalName: "Cable Chest Fly",
    legacySummary: "Cable chest isolation with adjustable line of pull.",
    focus: fact("Use a range that stays comfortable and controlled at the shoulder.", { compact: "Keep range shoulder-friendly" }),
    cues: [fact("Bring the arms through the fly path without turning the movement into a press.", { compact: "Move through chest, not front shoulder" }), fact("Keep a small consistent bend at the elbows.")],
    setup: [fact("Set both cable anchors and handles to the prescribed fly path before stepping into position."), fact("Take a balanced stance with clear space behind and between the cable lines."), fact("A cable stack with a reviewed two-sided path is required.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Sweep the arms toward one another through the selected range."), fact("Open the arms under control without chasing a deeper stretch.")],
    pattern: "A cable chest fly is a shoulder horizontal-adduction accessory with an adjustable cable line of pull.",
    watchFor: [fact("Watch for the elbows bending further until the movement becomes a press."), fact("Watch for the cable load pulling the torso out of the selected stance.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["resistance.cable-anchored", "path.adjustable-line-of-pull", "shoulder.horizontal-adduction"], roles: ["accessory"], actions: ["shoulder_horizontal_adduction"], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "chest-supported-dumbbell-row", canonicalName: "Chest-Supported Dumbbell Row",
    legacySummary: "Bench-supported horizontal pull with low lumbar stabilization demand.",
    focus: fact("Draw the elbows back along the selected row path.", { compact: "Pull elbows toward hips" }),
    cues: [fact("Keep the chest connected to the bench support.", { compact: "Keep chest supported" }), fact("Let the arms return without lifting the torso from the bench.")],
    setup: [fact("Set a stable bench angle that supports the chest and leaves room for both dumbbells."), fact("Position the chest on the bench and take one dumbbell in each hand before beginning."), fact("This row requires dumbbells and a stable bench; unsupported rowing is a different identity.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Pull both dumbbells while the bench continues to support the trunk."), fact("Lower the dumbbells under control until the next pull can begin without reaching the floor.")],
    pattern: "This is a bench-supported free-implement horizontal pull with limited trunk-position demand.",
    watchFor: [fact("Watch for lifting the chest from the bench to create more range."), fact("Watch for forcing the shoulder blades into a hard pinched position.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.prone-bench", "resistance.free-implement", "path.horizontal-pull"], roles: ["horizontal_pull"], actions: [], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "one-arm-dumbbell-row", canonicalName: "One-Arm Dumbbell Row",
    legacySummary: "Unsupported or lightly supported dumbbell horizontal pull with more trunk demand.",
    focus: fact("Use the prescribed support so the row remains the main task.", { compact: "Support as needed" }),
    cues: [fact("Keep the selected torso position steady while the dumbbell moves.", { compact: "Keep torso position steady" }), fact("Guide the dumbbell along the reviewed side-specific row path.")],
    setup: [fact("Take one dumbbell and establish the prescribed stance, working side, and support surface."), fact("Place the supporting hand or body contact securely before loading the rowing arm."), fact("A dumbbell is required; bench support is optional only when that realization is prescribed.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Pull the dumbbell without using trunk rotation to finish the repetition."), fact("Lower the dumbbell under control while maintaining the selected support and stance.")],
    pattern: "A one-arm dumbbell row is a unilateral horizontal pull whose support and stance are realization facts.",
    watchFor: [fact("Watch for the torso rotating as the dumbbell approaches the body."), fact("Watch for the support hand or stance shifting under load.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "bench", realizationId: "bench-supported", facts: [
        { suffix: "setup", category: "setup", statement: "For bench support, place the supporting contact fully on a stable bench before lifting the dumbbell." },
        { suffix: "watch", category: "watchFor", statement: "Watch for the bench or support contact shifting during the row." },
      ] },
      { id: "unsupported", realizationId: "unsupported-split-stance", facts: [
        { suffix: "setup", category: "setup", statement: "For the unsupported realization, establish a stable split stance before the dumbbell leaves its start position." },
        { suffix: "during", category: "during", statement: "Hold the unsupported hinge position without adding a torso swing." },
      ] },
    ], mechanics: ["support.partial-or-unsupported", "resistance.free-implement", "laterality.unilateral"], roles: ["horizontal_pull"], actions: [], stress: ["loaded_hinge"], painTopics: ["shoulder-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "machine-row", canonicalName: "Machine Row",
    legacySummary: "Machine-based horizontal pull with machine-specific path and fit constraints.",
    focus: fact("Adjust the support so the machine row starts from a clean handle path.", { compact: "Set pad height cleanly" }),
    cues: [fact("Pull without lifting the shoulders toward the neck.", { compact: "Pull without neck tension" }), fact("Stay connected to the machine support through the return.")],
    setup: [fact("Adjust the seat, chest pad, and handles for the exact row machine."), fact("Select the load and establish both foot and torso support before pulling."), fact("An exact row-machine capability is required; no other machine label proves the same path.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Pull through the guided path while the torso remains supported."), fact("Return the handles under control without letting the stack or arms drop.")],
    pattern: "A machine row is a supported horizontal pull whose path and fit remain machine-specific.",
    watchFor: [fact("Watch for a pad or seat setting that blocks the intended handle path."), fact("Watch for leaving the support or shrugging to finish the pull.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.seated-machine", "resistance.machine-guided", "fit.machine-specific"], roles: ["horizontal_pull"], actions: [], stress: [], painTopics: ["shoulder-response-context"], unresolvedClaims: ["Attachment, grip, and machine-geometry variants require exact review before Knowledge overrides are added."],
  }),
  entry({
    exerciseId: "seated-cable-row", canonicalName: "Seated Cable Row",
    legacySummary: "Cable-anchored horizontal pull with setup-dependent line of pull.",
    focus: fact("Let the arms reach forward only while the seated base stays controlled.", { compact: "Own the reach" }),
    cues: [fact("Finish the row with a smooth shoulder-blade path.", { compact: "Finish with shoulder blades moving cleanly" }), fact("Keep the torso from swinging to move the cable.")],
    setup: [fact("Set the cable, attachment, seat, and foot support for the reviewed row path."), fact("Sit far enough from the stack to begin with tension and a stable base."), fact("A cable stack and explicit seated support are required; attachments are not assumed equivalent.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Pull the attachment toward the selected endpoint without rocking backward."), fact("Return the arms and shoulder blades under control while maintaining foot support.")],
    pattern: "A seated cable row is a supported horizontal pull with a setup-dependent cable line.",
    watchFor: [fact("Watch for body swing replacing the horizontal pull."), fact("Watch for losing foot support or letting the stack drop between repetitions.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.seated", "resistance.cable-anchored", "path.horizontal-pull"], roles: ["horizontal_pull"], actions: [], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "band-row", canonicalName: "Band Row",
    legacySummary: "Anchored-band horizontal pull.",
    focus: fact("Confirm the band and mid-height anchor are secure before pulling.", { compact: "Anchor securely" }),
    cues: [fact("Keep the trunk position steady as the band shortens.", { compact: "Pull without rib flare" }), fact("Control the return so tension changes smoothly.")],
    setup: [fact("Attach an intact band to a proven mid-height anchor and face the line of pull."), fact("Take a balanced stance and step back only far enough to create the prescribed tension."), fact("A secure mid-height environmental anchor is required; this is not an anchorless row.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Pull the band toward the torso along the anchor line."), fact("Return the hands under control while keeping the band directed away from the face.", { kind: "safety_boundary" })],
    pattern: "A band row is an environmentally anchored elastic horizontal pull.",
    watchFor: [fact("Watch for the anchor, band, or stance shifting during the set."), fact("Watch for leaning back to create the pull instead of moving the arms.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.standing", "resistance.band-anchored", "anchor.mid"], roles: ["horizontal_pull"], actions: [], stress: [], painTopics: ["shoulder-response-context"], unresolvedClaims: ["Anchor height, stance, and grip alternatives remain unaccepted unless production metadata names them."],
  }),
  entry({
    exerciseId: "dumbbell-shoulder-press", canonicalName: "Dumbbell Shoulder Press",
    legacySummary: "External-load vertical push.",
    focus: fact("Press through a range that remains comfortable and controlled.", { compact: "Press in pain-free range" }),
    cues: [fact("Keep the torso from leaning back to finish the press.", { compact: "Avoid leaning back" }), fact("Balance each dumbbell over the forearm as it moves.")],
    setup: [fact("Stand in stable space with the prescribed dumbbell count controlled at the start position."), fact("Set the stance and press path before the first repetition."), fact("Dumbbells are required; bench support applies only to an approved supported realization.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Press the dumbbells upward without changing the selected torso position."), fact("Lower under control to the prescribed start range.")],
    pattern: "A dumbbell shoulder press is a free-implement vertical push with explicit stance and support.",
    watchFor: [fact("Watch for the trunk leaning farther back as the dumbbells rise."), fact("Watch for one dumbbell drifting into a different path from the other.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [{ id: "seated", realizationId: "seated-bench-supported", facts: [
      { suffix: "setup", category: "setup", statement: "For the seated realization, lock the bench and establish full seat and back support before lifting the dumbbells." },
      { suffix: "during", category: "during", statement: "Stay connected to the bench while following the prescribed dumbbell path." },
    ] }], mechanics: ["support.standing-or-seated", "resistance.free-implement", "path.vertical-press"], roles: ["vertical_push"], actions: [], stress: ["heavy_axial_loading"], painTopics: ["shoulder-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "lat-pulldown", canonicalName: "Lat Pulldown",
    legacySummary: "Machine/cable vertical pull.",
    focus: fact("Drive the elbows downward through the selected pulldown path.", { compact: "Pull elbows down" }),
    cues: [fact("Keep the shoulders from crowding the neck as you pull.", { compact: "Avoid neck tension" }), fact("Control the handle upward without leaving the seat support.")],
    setup: [fact("Adjust the seat and thigh restraint for the exact lat-pulldown machine."), fact("Select the reviewed attachment, load, and start range before sitting."), fact("A lat-pulldown machine with high cable and thigh support is required; behind-neck pulling is excluded.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Pull the attachment in front of the body along the machine path."), fact("Return overhead under control while the thighs remain supported.")],
    pattern: "A lat pulldown is a seated machine or cable vertical pull with explicit thigh support.",
    watchFor: [fact("Watch for the torso swinging to start the pull."), fact("Watch for pulling behind the neck or losing the thigh support.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.seated-machine", "resistance.cable-machine", "path.vertical-pull"], roles: ["vertical_pull"], actions: [], stress: [], painTopics: ["shoulder-response-context"], unresolvedClaims: ["Grip width and attachment alternatives require exact production realization review."],
  }),
  entry({
    exerciseId: "band-lat-pulldown", canonicalName: "Band Lat Pulldown",
    legacySummary: "High-anchor band vertical pull.",
    focus: fact("Verify the high anchor is secure before taking band tension.", { compact: "Use a secure high anchor" }),
    cues: [fact("Keep the trunk organized beneath the high line of pull.", { compact: "Keep ribs stacked" }), fact("Control the hands upward as the band lengthens.")],
    setup: [fact("Attach an intact band to a proven high anchor and face the line of pull."), fact("Use the prescribed stance or kneeling position only when the production realization names it."), fact("A secure high environmental anchor is required; this is not an anchorless substitution.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Pull the band downward along the high anchor line without leaning away."), fact("Return under control while keeping the band path away from the face.", { kind: "safety_boundary" })],
    pattern: "A band lat pulldown is a high-anchored elastic vertical pull, not a cable-load equivalent.",
    watchFor: [fact("Watch for the high anchor or stance shifting under tension."), fact("Watch for turning the pull into a backward trunk lean.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.prescription-specific", "resistance.band-anchored", "anchor.high"], roles: ["vertical_pull"], actions: [], stress: [], painTopics: ["shoulder-response-context"], unresolvedClaims: ["Standing and kneeling alternatives require exact production realization metadata before override admission."],
  }),
]);
