import { defineCuratedEntry, fact } from "./shared";

const entry = defineCuratedEntry;

export const TRUNK_CARRY_SUPPORT_KNOWLEDGE_ENTRIES = Object.freeze([
  entry({
    exerciseId: "pallof-press", canonicalName: "Pallof Press",
    legacySummary: "Anti-rotation core press using cable or anchored band.",
    focus: fact("Resist being turned toward the anchor as the hands move away.", { compact: "Resist rotation" }),
    cues: [fact("Stay upright without letting the trunk open or flare.", { compact: "Stay tall without rib flare" }), fact("Return the hands without losing the selected stance.")],
    setup: [fact("Set a cable or securely anchored band near torso height and stand side-on to it."), fact("Choose the prescribed stance and take the handle at the center of the torso."), fact("The load must come from an explicit cable or anchored-band capability; this is not a chest press.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Press the hands away while keeping the torso oriented forward."), fact("Bring the hands back under control before changing sides or leaving the stance.")],
    pattern: "A Pallof press is a side-on cable or band anti-rotation task in which arm reach lengthens the trunk-control lever.",
    mechanicsFacts: [fact("Moving the hands farther from the torso lengthens the lever while the anchor continues to pull from the side.")],
    watchFor: [fact("Watch for the torso turning toward the anchor as the arms extend."), fact("Watch for the stance shifting to escape the line of pull.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "cable", realizationId: "cable-stack", facts: [
        { suffix: "setup", category: "setup", statement: "For the cable realization, set the anchor height, attachment, and stack load before taking the side-on stance." },
        { suffix: "during", category: "during", statement: "Keep the cable clear of the body as the hands press out and return." },
      ] },
      { id: "band", realizationId: "mid-anchored-band", facts: [
        { suffix: "setup", category: "setup", statement: "For the band realization, inspect the band and verify the mid-height environmental anchor before adding tension." },
        { suffix: "watch", category: "watchFor", statement: "Watch for the band or anchor shifting as the hands move away." },
      ] },
    ], mechanics: ["support.standing", "resistance.cable-or-band-anchored", "trunk.anti-rotation"], roles: ["anti_rotation_core"], actions: [], stress: ["long_lever_core"], painTopics: ["lumbar-response-context"],
  }),
  entry({
    exerciseId: "forearm-plank", canonicalName: "Forearm Plank",
    legacySummary: "Stationary forearm-supported anti-extension trunk exercise.",
    focus: fact("Keep the ribs and pelvis in the selected relationship for the hold.", { compact: "Keep ribs and pelvis organized" }),
    cues: [fact("Press the forearms into the floor throughout the hold.", { compact: "Press through the forearms" }), fact("End the hold when the selected body line can no longer be maintained.")],
    setup: [fact("Place both forearms on the floor and establish the prescribed knee or foot support."), fact("Set the shoulder, trunk, and lower-body line before beginning the timed hold."), fact("Clear floor space is required; support and lever follow the prescribed realization.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Maintain the selected stationary line without turning the hold into repeated movement."), fact("Continue normal comfortable breathing without adding a hidden cadence.")],
    pattern: "A forearm plank is a stationary bodyweight anti-extension hold whose support and lever can be scaled.",
    watchFor: [fact("Watch for the pelvis drifting away from the selected body line."), fact("Watch for the shoulders collapsing toward the floor between the forearms.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [{ id: "knees", realizationId: "knee-supported", facts: [
      { suffix: "setup", category: "setup", statement: "For the knee-supported realization, place the knees comfortably and establish the shortened lever before timing begins." },
      { suffix: "during", category: "during", statement: "Maintain one line from the knees through the trunk and shoulders during the hold." },
    ] }], mechanics: ["support.prone-forearms", "resistance.bodyweight", "trunk.anti-extension"], roles: ["anti_extension_core"], actions: [], stress: ["upper_limb_support_loading", "long_lever_core"], painTopics: ["shoulder-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "forearm-side-plank", canonicalName: "Forearm Side Plank",
    legacySummary: "Forearm-supported side plank for anti-lateral-flexion control.",
    focus: fact("Maintain a long controlled line along the supported side.", { compact: "Keep a long side line" }),
    cues: [fact("Press the supporting forearm into the floor.", { compact: "Press through the forearm" }), fact("Keep the prescribed side facing forward through the hold.")],
    setup: [fact("Lie on the prescribed side and place the forearm securely beneath the shoulder region."), fact("Set the approved foot or bent-knee support before lifting into the hold."), fact("Clear floor space is required; side and support must be prescribed explicitly.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Hold the pelvis and trunk in the selected side-oriented line."), fact("Lower under control before changing sides or ending the set.")],
    pattern: "A forearm side plank is a side-specific bodyweight anti-lateral-flexion hold with approved lever options.",
    watchFor: [fact("Watch for the pelvis rolling forward or backward during the hold."), fact("Watch for the supporting shoulder sinking toward the floor.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [{ id: "bent-knee", realizationId: "bent-knee-supported", facts: [
      { suffix: "setup", category: "setup", statement: "For the bent-knee realization, arrange the knees and lower legs as the shortened side-support base before lifting." },
      { suffix: "during", category: "during", statement: "Maintain the shorter line from the knees through the pelvis and shoulder." },
    ] }], mechanics: ["support.side-forearm", "support.prescription-modifiable", "trunk.anti-lateral-flexion"], roles: ["anti_lateral_flexion_core"], actions: [], stress: ["upper_limb_support_loading", "lateral_trunk_loading", "long_lever_core"], painTopics: ["shoulder-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "machine-abdominal-crunch", canonicalName: "Machine Abdominal Crunch",
    legacySummary: "Machine-guided controlled trunk-flexion exercise.",
    focus: fact("Flex through the trunk while following the machine path.", { compact: "Flex through the trunk with control" }),
    cues: [fact("Control the return without letting the stack drop.", { compact: "Return without dropping the stack" }), fact("Keep the selected pad and handle contacts throughout the repetition.")],
    setup: [fact("Adjust the seat, pads, handles, and start range for the exact abdominal-crunch machine."), fact("Set the load and establish the reviewed contact points before beginning."), fact("An exact abdominal-crunch machine capability is required; machine geometry remains specific.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Use controlled trunk flexion to move the machine through the selected range."), fact("Return to the start without pulling through the neck or dropping the load.")],
    pattern: "A machine abdominal crunch is a supported machine-guided controlled trunk-flexion task.",
    watchFor: [fact("Watch for the neck or arms pulling the machine instead of the trunk movement."), fact("Watch for forceful contact at either end of the machine path.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.seated-machine", "resistance.machine-guided", "trunk.controlled-flexion"], roles: ["trunk_flexion"], actions: [], stress: ["loaded_spinal_flexion"], painTopics: ["lumbar-response-context"],
  }),
  entry({
    exerciseId: "half-kneeling-high-to-low-cable-chop", canonicalName: "Half-Kneeling High-to-Low Cable Chop",
    legacySummary: "Half-kneeling high-cable controlled trunk-rotation exercise.",
    focus: fact("Rotate through the trunk while keeping the half-kneeling base controlled.", { compact: "Rotate through the trunk with control" }),
    cues: [fact("Follow the cable from its high start toward the low endpoint.", { compact: "Follow the high-to-low path" }), fact("Keep the lead side and anchor relationship unchanged during the set.")],
    setup: [fact("Set the cable high and take a half-kneeling stance with the prescribed lead side."), fact("Hold the attachment with enough space to follow the high-to-low path."), fact("A high cable anchor and explicit working side are required; this is not a generic rotation drill.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Guide the cable diagonally across the body through the selected rotation range."), fact("Return along the same path without letting the stack pull the kneeling base out of position.")],
    pattern: "A half-kneeling high-to-low cable chop is a side-specific controlled-rotation task with a diagonal cable path.",
    watchFor: [fact("Watch for the cable pulling the body out of the half-kneeling stance."), fact("Watch for the arms moving alone while the intended trunk rotation disappears.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.half-kneeling", "resistance.cable-anchored", "trunk.controlled-rotation"], roles: ["trunk_rotation"], actions: [], stress: ["loaded_trunk_rotation"], painTopics: ["lumbar-response-context"], unresolvedClaims: ["Alternate anchor heights, stances, and directions are not admitted by this Knowledge entry."],
  }),
  entry({
    exerciseId: "farmer-carry", canonicalName: "Farmer Carry",
    legacySummary: "Bilateral one-implement-per-hand loaded walking carry.",
    focus: fact("Walk with both implements controlled beside the body.", { compact: "Walk tall with quiet implements" }),
    cues: [fact("Use controlled turns and set both loads down deliberately.", { compact: "Use controlled turns and set-downs" }), fact("Keep the walking path clear before starting.")],
    setup: [fact("Place a dumbbell on each side and confirm a clear loaded walking route."), fact("Pick up both dumbbells from a controlled stance before beginning the trip."), fact("A dumbbell pair, stable loaded standing space, and loaded gait space are required.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Walk the prescribed trip while limiting unnecessary implement swing."), fact("Slow before turns and stop fully before setting the dumbbells down.", { kind: "safety_boundary" })],
    pattern: "A farmer carry is a bilateral one-implement-per-hand loaded gait and bracing task.",
    watchFor: [fact("Watch for either dumbbell swinging into the walking path."), fact("Watch for rushed turns or a set-down before the feet are stable.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.loaded-gait", "resistance.free-implement-pair", "trunk.loaded-bracing"], roles: ["carry", "loaded_bracing"], actions: [], stress: ["loaded_gait", "grip_loading", "grip_intensive", "heavy_axial_loading"], painTopics: ["grip-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "suitcase-carry", canonicalName: "Suitcase Carry",
    legacySummary: "Unilateral side-specific loaded walking carry.",
    focus: fact("Stay organized over each step while carrying on the prescribed side.", { compact: "Stay tall over each step" }),
    cues: [fact("Keep the loaded side controlled through the trip.", { compact: "Keep the load side controlled" }), fact("Use a clear route and deliberate turns.")],
    setup: [fact("Place one dumbbell on the prescribed side and confirm a clear loaded walking route."), fact("Pick up the dumbbell from a stable stance before beginning the trip."), fact("One dumbbell and loaded gait space are required; the load side must be explicit.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Walk while keeping the dumbbell controlled beside the loaded side."), fact("Slow before turning and stop before setting the dumbbell down.", { kind: "safety_boundary" })],
    pattern: "A suitcase carry is a unilateral side-specific loaded gait and bracing task.",
    watchFor: [fact("Watch for the dumbbell swinging into the leg or walking path."), fact("Watch for drifting progressively toward or away from the loaded side.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.loaded-gait", "resistance.single-free-implement", "trunk.loaded-bracing"], roles: ["carry", "anti_lateral_flexion_core", "loaded_bracing"], actions: [], stress: ["loaded_gait", "grip_loading", "lateral_trunk_loading", "grip_intensive", "heavy_axial_loading"], painTopics: ["grip-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "wall-supported-suitcase-march", canonicalName: "Wall-Supported Suitcase March",
    legacySummary: "Stationary alternating loaded march with opposite-hand wall support.",
    focus: fact("Use the wall only as light support for the stationary march.", { compact: "Use light wall support" }),
    cues: [fact("March in place without drifting toward the dumbbell.", { compact: "March without drifting toward the load" }), fact("Keep the loaded hand quiet beside the body.")],
    setup: [fact("Stand beside a wall with one dumbbell in the prescribed hand and the opposite hand on the wall."), fact("Clear stable standing space and establish the starting foot position before marching."), fact("A wall, one dumbbell, and stable standing space are required; no walking distance is part of this identity.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Alternate the prescribed marching steps while remaining in place."), fact("Stop the march and settle both feet before releasing the wall or dumbbell.", { kind: "safety_boundary" })],
    pattern: "A wall-supported suitcase march is a stationary alternating loaded-bracing task, not a carry.",
    watchFor: [fact("Watch for the feet traveling forward or sideways instead of marching in place."), fact("Watch for pushing hard into the wall to create the leg lift.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.opposite-hand-wall", "resistance.single-free-implement", "trunk.loaded-bracing"], roles: ["loaded_bracing"], actions: [], stress: ["loaded_march", "grip_loading", "lateral_trunk_loading"], painTopics: ["grip-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "side-lying-hip-adduction", canonicalName: "Side-Lying Hip Adduction",
    legacySummary: "Floor-supported direct hip-adduction accessory exercise.",
    focus: fact("Lift the working leg using the inner-thigh action.", { compact: "Lift with the inner thigh" }),
    cues: [fact("Keep the pelvis stacked as the leg moves.", { compact: "Keep the pelvis stacked" }), fact("Lower the leg back to the same side-lying start.")],
    setup: [fact("Lie on the prescribed side with the trunk and head supported."), fact("Place the non-working leg so the lower working leg has a clear lifting path."), fact("This realization uses bodyweight and floor support; no external load is implied.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Lift the lower leg away from the floor without rolling the pelvis."), fact("Return under control before beginning the next side-specific repetition.")],
    pattern: "Side-lying hip adduction is a floor-supported direct hip-adduction accessory for the lower leg.",
    watchFor: [fact("Watch for the pelvis rolling backward as the leg lifts."), fact("Watch for the upper body moving to create extra leg height.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.side-lying-floor", "resistance.bodyweight", "laterality.prescription-side"], roles: ["accessory"], actions: ["hip_adduction"], stress: [], painTopics: ["hip-response-context"],
  }),
  entry({
    exerciseId: "loop-band-lateral-walk", canonicalName: "Loop-Band Lateral Walk",
    legacySummary: "Standing lateral stepping against unanchored loop-band resistance.",
    focus: fact("Step laterally while keeping each knee aligned with the selected foot path.", { compact: "Step without letting the knees collapse" }),
    cues: [fact("Keep steady tension in the loop band between steps.", { compact: "Keep steady band tension" }), fact("Return to a stable stance before the next step.")],
    setup: [fact("Place an intact loop band at the prescribed reviewed position."), fact("Stand on a clear stable floor with the selected stance and direction."), fact("An unanchored loop band is required; placement changes need explicit realization metadata.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Take controlled lateral steps in the prescribed direction without adding an unrequested squat depth."), fact("Bring the trailing foot in under control while retaining band tension.")],
    pattern: "A loop-band lateral walk is a standing alternating lateral-step accessory against unanchored elastic resistance.",
    watchFor: [fact("Watch for the feet snapping together as the band shortens."), fact("Watch for the knees moving inward away from the selected foot path.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [{ id: "supported", realizationId: "stable-support", facts: [
      { suffix: "setup", category: "setup", statement: "For the supported realization, establish a light hand contact on a stable surface before stepping." },
      { suffix: "during", category: "during", statement: "Use the support for balance while the feet continue to perform the lateral stepping task." },
    ] }], mechanics: ["support.standing", "resistance.band-unanchored", "path.lateral-steps"], roles: ["accessory"], actions: ["hip_abduction"], stress: [], painTopics: ["hip-response-context", "knee-response-context"], unresolvedClaims: ["No alternate band placement is accepted until production realization metadata identifies it."],
  }),
  entry({
    exerciseId: "side-lying-dumbbell-external-rotation", canonicalName: "Side-Lying Dumbbell External Rotation",
    legacySummary: "Supported direct shoulder external-rotation accessory exercise.",
    focus: fact("Rotate from the shoulder through the selected controlled range.", { compact: "Rotate from the shoulder" }),
    cues: [fact("Keep the elbow position quiet as the dumbbell moves.", { compact: "Keep the elbow position quiet" }), fact("Use a load that keeps the rotation smooth.")],
    setup: [fact("Lie on the prescribed side with the head and torso supported on the selected floor or bench surface."), fact("Hold one light dumbbell and place the working elbow in its reviewed support position."), fact("A dumbbell plus explicit floor or bench support is required; no standing cuff path is implied.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Rotate the forearm upward from the shoulder without lifting the elbow away from its position."), fact("Lower the dumbbell under control to the prescribed start range.")],
    pattern: "This is a side-lying supported direct shoulder external-rotation accessory with a free implement.",
    watchFor: [fact("Watch for the elbow drifting to create more range."), fact("Watch for the torso rolling backward with the dumbbell.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "floor", realizationId: "floor-supported", facts: [
        { suffix: "setup", category: "setup", statement: "For floor support, position the whole side of the torso securely on clear floor space." },
      ] },
      { id: "bench", realizationId: "bench-supported", facts: [
        { suffix: "setup", category: "setup", statement: "For bench support, verify the bench is stable and wide enough for the side-lying position before holding the dumbbell." },
        { suffix: "watch", category: "watchFor", statement: "Watch for moving toward the edge of the bench during the set." },
      ] },
    ], mechanics: ["support.side-lying-floor-or-bench", "resistance.free-implement", "action.shoulder-external-rotation"], roles: ["accessory"], actions: ["shoulder_external_rotation"], stress: [], painTopics: ["shoulder-response-context"],
  }),
  entry({
    exerciseId: "supine-hamstring-walkout", canonicalName: "Supine Hamstring Walkout",
    legacySummary: "Floor-supported bridge-position heel walkout for direct hamstring work.",
    focus: fact("Keep the hips controlled as the heels move.", { compact: "Keep the hips controlled" }),
    cues: [fact("Walk the heels only as far as the bridge position stays controlled.", { compact: "Walk only as far as you can own" }), fact("Use deliberate heel steps in both directions.")],
    setup: [fact("Lie on the back with both heels planted and enough clear floor space for the walkout."), fact("Lift to the prescribed bridge start before counting the first heel step."), fact("This bodyweight task requires floor space; sliders or external load are not part of the identity.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Take the prescribed small heel steps away from the body while maintaining the bridge."), fact("Walk the heels back under control before lowering the pelvis.")],
    pattern: "A supine hamstring walkout is a counted-step bridge task that changes the heel lever against bodyweight.",
    watchFor: [fact("Watch for the hips dropping as the heels move farther away."), fact("Watch for steps becoming too large to return under control.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.supine-floor", "resistance.bodyweight", "dose.counted-steps"], roles: ["accessory"], actions: ["knee_flexion", "hip_extension"], stress: [], painTopics: ["hamstring-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "wall-ankle-dorsiflexion-rock", canonicalName: "Wall Ankle Dorsiflexion Rock",
    legacySummary: "Wall-referenced ankle dorsiflexion preparation exercise.",
    focus: fact("Guide the working knee forward over the foot.", { compact: "Guide the knee forward over the foot" }),
    cues: [fact("Keep the working heel in contact with the floor.", { compact: "Keep the heel grounded" }), fact("Use a range that stays smooth rather than forcing the wall target.")],
    setup: [fact("Face the wall in the prescribed split stance with the working foot flat on the floor."), fact("Set the foot distance so the wall can serve as a range reference and optional hand support."), fact("A wall and clear floor space are required for this reference-based preparation task.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Rock the knee forward while the heel remains down."), fact("Return to the start under control before repeating on the prescribed side.")],
    pattern: "A wall ankle dorsiflexion rock is a side-specific unloaded ankle-range preparation task.",
    watchFor: [fact("Watch for the heel lifting to reach farther."), fact("Watch for the foot rolling away from its selected floor contact.")],
    compactCoachingRefs: ["focus", "cue.1"], mechanics: ["support.wall-referenced", "resistance.bodyweight", "action.ankle-dorsiflexion"], roles: ["mobility"], actions: ["ankle_dorsiflexion"], stress: [], painTopics: ["ankle-response-context"],
  }),
  entry({
    exerciseId: "bodyweight-hip-hinge-rehearsal", canonicalName: "Bodyweight Hip-Hinge Rehearsal",
    legacySummary: "Unloaded standing hip-hinge pattern preparation.",
    focus: fact("Send the hips backward to rehearse the hinge.", { compact: "Send the hips back" }),
    cues: [fact("Keep the trunk organized as the hips move.", { compact: "Keep the trunk organized" }), fact("Return to standing without adding an external load.")],
    setup: [fact("Stand in a stable bilateral stance with clear space behind the hips."), fact("Set any approved wall or stable-surface reference before beginning."), fact("This is an unloaded bodyweight rehearsal; setup aids do not make it a loaded hinge.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Move the hips backward while maintaining the selected trunk relationship."), fact("Stand by bringing the hips forward without leaning beyond upright.")],
    pattern: "A bodyweight hip-hinge rehearsal practices the unloaded bilateral hinge before separate loaded identities.",
    watchFor: [fact("Watch for the knees moving forward until the rehearsal becomes a squat."), fact("Watch for reaching farther after the selected trunk position changes.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "wall", realizationId: "wall-target", facts: [
        { suffix: "setup", category: "setup", statement: "For the wall-target realization, stand the prescribed distance in front of the wall with the hips facing it." },
        { suffix: "during", category: "during", statement: "Reach the hips toward the wall without using it to support bodyweight." },
      ] },
      { id: "support", realizationId: "stable-support", facts: [
        { suffix: "setup", category: "setup", statement: "For the supported realization, establish a light hand contact on the approved stable surface." },
        { suffix: "during", category: "during", statement: "Use the contact as a position reference while the hips perform the hinge." },
      ] },
    ], mechanics: ["support.standing", "resistance.bodyweight", "path.hinge-rehearsal"], roles: ["hinge"], actions: ["hip_extension"], stress: [], painTopics: ["hip-response-context", "lumbar-response-context"],
  }),
  entry({
    exerciseId: "single-leg-balance-rehearsal", canonicalName: "Single-Leg Balance Rehearsal",
    legacySummary: "Stationary single-leg stance-control preparation with prescription-modifiable support.",
    focus: fact("Use only the stable support needed for the stationary hold.", { compact: "Use only the support you need" }),
    cues: [fact("Keep the prescribed stance side controlled.", { compact: "Keep the stance side controlled" }), fact("Stay in place rather than turning the hold into a step or reach task.")],
    setup: [fact("Stand beside the approved stable support and identify the prescribed stance side."), fact("Set the support amount before lifting the other foot."), fact("The base task is unloaded stationary single-leg stance; dynamic or loaded tasks are separate identities.", { kind: "equipment_boundary", source: "equipment" })],
    during: [fact("Maintain the stationary stance for the prescribed exposure."), fact("Place the other foot down under control before changing sides or support.")],
    pattern: "A single-leg balance rehearsal is a stationary side-specific preparation hold with prescription-modifiable support.",
    watchFor: [fact("Watch for repeatedly hopping or stepping to continue the hold."), fact("Watch for support pressure increasing until the hand carries the task.")],
    compactCoachingRefs: ["focus", "cue.1"], overrides: [
      { id: "substantial", realizationId: "substantial-support", facts: [
        { suffix: "setup", category: "setup", statement: "For substantial support, establish a secure hand contact before lifting the non-stance foot." },
        { suffix: "during", category: "during", statement: "Keep the stance task stationary while using the prescribed support amount." },
      ] },
      { id: "light-touch", realizationId: "light-touch-support", facts: [
        { suffix: "setup", category: "setup", statement: "For light-touch support, place the fingertips on a stable surface before beginning the hold." },
        { suffix: "watch", category: "watchFor", statement: "Watch for light touch becoming a weight-bearing arm support during the hold." },
      ] },
    ], mechanics: ["support.single-leg", "support.prescription-modifiable", "laterality.prescription-side"], roles: ["single_leg"], actions: ["single_leg_stance_control"], stress: [], painTopics: ["ankle-response-context", "knee-response-context", "hip-response-context"],
  }),
]);
