import {
  CHUNK_E_LEDGER_BEFORE_SHA,
  CHUNK_E_STARTING_COMMIT,
  CURRENT_RENDER_BASELINE_REFERENCE,
  F_HANDOFF_REFERENCE,
  OWNER_SCREENSHOT_CORPUS_REFERENCE,
  PRODUCT_GOAL_CONTEXT_DESIGN_REFERENCE,
  PRODUCT_PROFILE_V2_REFERENCE,
  QUESTIONNAIRE_SIGNATURE_V2_REFERENCE,
  type DesignGuardModel,
  type DriftClassification,
  type GoalOptionState,
  type OwnershipClassification,
} from "./contracts";

const fieldOrderConsumer = Object.freeze([
  "days_per_week",
  "primary_goal",
  "training_mode",
  "pain_areas",
  "training_experience",
  "equipment",
]);

const fieldOrderGyms = Object.freeze([
  "days_per_week",
  "primary_goal",
  "pain_areas",
  "training_experience",
  "equipment_or_locked_environment",
]);

export const ownerScreenshotCorpus = Object.freeze({
  reference: OWNER_SCREENSHOT_CORPUS_REFERENCE,
  source: "owner_supplied_product_visual_context_evidence",
  declaredLogicalImageCount: 13,
  declaredComposition: Object.freeze({ desktopComposites: 5, representativeMobileCrops: 8 }),
  locallyObservedBinaryCount: 8,
  locallyObservedDimensions: "4480x1440 for all eight supplied PNG binaries",
  locallyVerifiedProductCompositeCount: 5,
  locallyVerifiedMobileCropCount: 0,
  localDisposition: Object.freeze({
    productComposites: 5,
    partialProductWithDevelopmentContext: 1,
    unrelatedDevelopmentDesktopContext: 2,
  }),
  discrepancyDisposition:
    "The owner-declared 13-image logical corpus and mobile observations remain Product evidence, while the local eight-binary inventory is recorded separately. No missing image is requested and no mobile screenshot content is invented.",
  screenshotBinariesCommitted: 0,
  personalDataCommitted: 0,
  binaryPolicy: "owner binaries remain untracked and are excluded from architecture documentation",
  sanitizedObservationIds: Object.freeze([
    "global_visual_language",
    "desktop_onboarding",
    "questionnaire_field_order",
    "questionnaire_control_styles",
    "conditional_band_owner_report",
    "mobile_responsive_language_owner_report",
    "global_progressive_disclosure_language",
    "dashboard_and_week_consistency_context",
    "active_session_context",
    "pain_report_context",
    "session_completion_context",
    "progress_history_and_insights_context",
  ]),
  observations: Object.freeze({
    globalVisualLanguage: Object.freeze([
      "full_viewport_photographic_background",
      "translucent_navy_slate_surfaces",
      "thin_low_contrast_borders",
      "white_primary_text_and_slate_secondary_text",
      "cyan_to_blue_primary_cta",
      "sky_ring_selected_surface",
      "compact_uppercase_eyebrow",
      "compact_rounded_rectangular_cards",
      "fixed_information_and_menu_controls",
    ]),
    desktopOnboarding: Object.freeze([
      "centered_constrained_column",
      "step_header_above_one_large_form_panel",
      "back_to_photos_in_header",
      "vertically_stacked_sections",
      "compact_multi_choice_grids",
      "full_width_submit_cta",
    ]),
    currentScreenshotFieldOrder: Object.freeze([
      "days_per_week",
      "primary_goal",
      "current_approach",
      "pain_areas",
      "training_experience",
      "equipment",
      "submit",
    ]),
    screenshotSpecific: Object.freeze({
      kneesVisible: true,
      consumerCurrentApproachCardsVisible: true,
      resistanceBandDetailReportedByOwner: true,
      resistanceBandExpandedStatePhotographed: false,
    }),
    mobileOwnerObservations: Object.freeze([
      "same_responsive_product_language",
      "one_column_stacking",
      "approximately_16_to_24_pixel_gutters",
      "inline_conditional_expansion",
      "fixed_controls_need_bottom_safe_space",
      "no_horizontal_scroll",
    ]),
    globalInteractionLanguage: Object.freeze([
      "view_hide_and_view_details_disclosures",
      "compact_status_pills",
      "gradient_primary_actions",
      "outlined_supporting_actions",
      "progressive_detail_reveal",
      "self_contained_active_workout_information",
    ]),
  }),
  sanitization: Object.freeze({
    omitted: Object.freeze([
      "username",
      "account_identifiers",
      "personal_history_dates",
      "personal_workout_values",
      "browser_account_state",
      "email",
      "photos",
      "personal_notes",
    ]),
    copiedPersonalValues: 0,
    copiedImagePixels: 0,
  }),
  desktopObservationResult: "VERIFIED_FROM_FIVE_PRODUCT_COMPOSITES",
  mobileObservationResult:
    "OWNER_REPORTED_NOT_INDEPENDENTLY_VISIBLE_IN_LOCAL_BINARY_INVENTORY_CURRENT_HEAD_RENDER_USED_FOR_IMPLEMENTATION_REVIEW",
});

type BaselineSeed = {
  app: "consumer" | "gyms";
  state: string;
  width: number;
  height: number;
  hash: string;
  fieldOrder: readonly string[];
  conditionalState: string;
};

const baselineSeeds: readonly BaselineSeed[] = Object.freeze([
  { app: "consumer", state: "questionnaire_default", width: 1440, height: 900,
    hash: "0cb4bebe95ffb6d09d38df6bb6f7b0fefc33228215719a15464d76b63890ba72",
    fieldOrder: fieldOrderConsumer, conditionalState: "none" },
  { app: "consumer", state: "goal_improve_posture", width: 1440, height: 900,
    hash: "0cb4bebe95ffb6d09d38df6bb6f7b0fefc33228215719a15464d76b63890ba72",
    fieldOrder: fieldOrderConsumer, conditionalState: "selected_goal" },
  { app: "consumer", state: "goal_reduce_pain", width: 1440, height: 900,
    hash: "4caa44893895c6ad00994c7a08330af5f875a49028b342032efc96976c45e82b",
    fieldOrder: fieldOrderConsumer, conditionalState: "selected_goal" },
  { app: "consumer", state: "goal_athletic_performance", width: 1440, height: 900,
    hash: "86294e6d62fd64c8e18bd15c26cf1e894097fd8ebc55bda5fee6b9e82ab6186a",
    fieldOrder: fieldOrderConsumer, conditionalState: "selected_goal" },
  { app: "consumer", state: "goal_general_fitness", width: 1440, height: 900,
    hash: "10d61ff4a9a8efea67f3f0ec1fcfa132cb8d43318ca5fdcb9c23109a43bd3927",
    fieldOrder: fieldOrderConsumer, conditionalState: "selected_goal" },
  { app: "consumer", state: "training_mode_build", width: 1440, height: 900,
    hash: "10d61ff4a9a8efea67f3f0ec1fcfa132cb8d43318ca5fdcb9c23109a43bd3927",
    fieldOrder: fieldOrderConsumer, conditionalState: "selected_mode" },
  { app: "consumer", state: "training_mode_maintain", width: 1440, height: 900,
    hash: "d0b4af9c77fb73a915238fb0b1d93e7aad1d05af257a4bf7a2c7dcf683d9d247",
    fieldOrder: fieldOrderConsumer, conditionalState: "selected_mode" },
  { app: "consumer", state: "training_mode_recover", width: 1440, height: 900,
    hash: "4dbe3f9cc4abf9f9bda8641762754d21f2db8e1232cb11c92d5f4df43fba9950",
    fieldOrder: fieldOrderConsumer, conditionalState: "selected_mode" },
  { app: "consumer", state: "equipment_none", width: 1440, height: 900,
    hash: "8102e97fa2d796a94f5b299317be03f895bbbe334c62d09487e3611967a9aad6",
    fieldOrder: fieldOrderConsumer, conditionalState: "equipment_selected_no_detail" },
  { app: "consumer", state: "equipment_bands", width: 1440, height: 900,
    hash: "bed926ee17f78a91c2f281bf413f2155cf77011ea6824bc4d277708cde6a5419",
    fieldOrder: fieldOrderConsumer, conditionalState: "bands_selected_no_detail_present" },
  { app: "consumer", state: "equipment_dumbbells", width: 1440, height: 900,
    hash: "489bb8704c3a45feb8aa130fc905f48685fa762d3c37342b0a9d08e84e4f9a8f",
    fieldOrder: fieldOrderConsumer, conditionalState: "equipment_selected_no_detail" },
  { app: "consumer", state: "equipment_gym", width: 1440, height: 900,
    hash: "505da7063b4e56ff4f69eb5fe0e895e812dcb785fb61a87f8610b332c2a30858",
    fieldOrder: fieldOrderConsumer, conditionalState: "equipment_selected_no_detail" },
  { app: "consumer", state: "questionnaire_responsive", width: 1024, height: 768,
    hash: "fe719e37b37d9968444749815dc429de52d3f7796a7702bc93a6fb2a0c726ae5",
    fieldOrder: fieldOrderConsumer, conditionalState: "none" },
  { app: "consumer", state: "questionnaire_responsive", width: 390, height: 844,
    hash: "cb639faf40810fd1946a420878eace05c220d1a636b6e010a66ed6e416fd734e",
    fieldOrder: fieldOrderConsumer, conditionalState: "one_column" },
  { app: "consumer", state: "questionnaire_responsive", width: 360, height: 800,
    hash: "de180bff2a3b764908be5bcf8e264a9451fec6d4c5164c7f9fb22ad08d18a9b3",
    fieldOrder: fieldOrderConsumer, conditionalState: "one_column" },
  { app: "consumer", state: "questionnaire_responsive", width: 320, height: 800,
    hash: "c230ea4ac1916af8c8052ea3ff7d3001e43d0743efdcd167e21056cf80606a87",
    fieldOrder: fieldOrderConsumer, conditionalState: "one_column" },
  { app: "consumer", state: "dirty_state_confirmation", width: 390, height: 844,
    hash: "65cf39838d7e9cf612c724b0b689fd8b7cf51d62cafc9003807c839d9debf9dc",
    fieldOrder: fieldOrderConsumer, conditionalState: "confirmation_dialog" },
  { app: "consumer", state: "active_session_warning", width: 390, height: 844,
    hash: "8f2f420b271473e069d456148b7d250294c37754feee2cb5c6736bd058eceea5",
    fieldOrder: fieldOrderConsumer, conditionalState: "confirmation_dialog_with_active_session_warning" },
  { app: "gyms", state: "questionnaire_default", width: 1440, height: 900,
    hash: "d4831cacd8d9f44734992c0278e7e70a380339c81d47a1ef2495c18000f1b6b6",
    fieldOrder: fieldOrderGyms, conditionalState: "training_mode_absent" },
  { app: "gyms", state: "questionnaire_default", width: 390, height: 844,
    hash: "2f7e39aa9ccc6c5c9d1545a1b26da1617826019d05c710a3a3729dab36fb6e85",
    fieldOrder: fieldOrderGyms, conditionalState: "training_mode_absent_one_column" },
  { app: "gyms", state: "buyer_demo_locked_equipment", width: 1440, height: 900,
    hash: "8c4bee623669204abed9daca4f3c3046b18845dee8fc54708812c4a60a1d6045",
    fieldOrder: fieldOrderGyms, conditionalState: "equipment_locked_by_gym_owner" },
  { app: "gyms", state: "buyer_demo_locked_equipment", width: 390, height: 844,
    hash: "abeb5e428a1cecaf5aa7749718658e10b87f7269a4bc07de7a58b7736728c817",
    fieldOrder: fieldOrderGyms, conditionalState: "equipment_locked_by_gym_owner_one_column" },
]);

export const currentRenderBaseline = Object.freeze({
  reference: CURRENT_RENDER_BASELINE_REFERENCE,
  branch: "engine-v2/candidate-intelligence",
  commit: CHUNK_E_STARTING_COMMIT,
  syntheticDataOnly: true,
  binaryDisposition: "ignored Playwright artifacts under each app test-results directory",
  semanticVerdictDoesNotDependOnPixelEquality: true,
  backgroundCropExcludedFromSemanticFailure: true,
  entries: Object.freeze(baselineSeeds.map((seed) => Object.freeze({
    route: seed.app === "consumer" ? "/questionnaire" :
      seed.state.includes("buyer_demo") ? "/questionnaire?demo=buyer" : "/questionnaire",
    appSurface: seed.app,
    viewport: Object.freeze({ width: seed.width, height: seed.height }),
    syntheticState: seed.state,
    artifactReference:
      `${seed.app}/test-results/product-goal-context-design/${seed.app}/${seed.state.replaceAll("_", "-")}-${seed.width}x${seed.height}.png`,
    artifactSha256: seed.hash,
    renderedFieldOrder: seed.fieldOrder,
    visibleGoalOptions: Object.freeze([
      "Improve posture",
      "Reduce pain",
      "Athletic performance",
      "General fitness",
    ]),
    conditionalState: seed.conditionalState,
    horizontalOverflow: false,
    fixedControlOverlap: false,
    accessibilityObservations: Object.freeze([
      "interactive_surfaces_render_at_or_above_44px",
      "native_select_present",
      "current_group_controls_lack_fieldset_legend",
      "current_primary_goal_select_lacks_programmatic_label_association",
    ]),
    sourceProvenance: "current_branch_playwright_synthetic_local_state",
  }))),
  consumerResult: "18_CURRENT_HEAD_STATES_RENDERED",
  gymsResult: "4_CURRENT_HEAD_STATES_RENDERED",
  desktopResult: "NO_HORIZONTAL_OVERFLOW_OR_FIXED_CONTROL_COLLISION",
  mobileResult: "NO_HORIZONTAL_OVERFLOW_OR_FIXED_CONTROL_COLLISION_AT_320_360_390",
  currentAccessibilityLimitations: Object.freeze([
    "grouped_choices_are_not_fieldsets_with_legends",
    "primary_goal_select_has_no_associated_label",
    "selection_state_is_not_explicitly_exposed_with_aria_pressed",
    "gyms_buyer_demo_unselected_experience_labels_have_low_visible_contrast_in_capture",
  ]),
});

const drift = (
  id: string,
  evidence: string,
  classifications: readonly DriftClassification[],
  disposition: string,
  materialToE: boolean,
) => Object.freeze({ id, evidence, classifications: Object.freeze(classifications), disposition,
  materialToChunkE: materialToE });

export const driftAudit = Object.freeze({
  rows: Object.freeze([
    drift("global_visual_language", "Five Product composites and current renders share photo, dark glass, sky selection, and gradient CTA language",
      ["screenshot_matches_current_branch"], "preserve", true),
    drift("consumer_field_order", "Owner screenshot and consumer branch both order days, goal, mode, pain, experience, equipment",
      ["screenshot_matches_current_branch"], "record_current_order_but_design_goal_first_target", true),
    drift("knees_pain_choice", "Owner screenshot includes Knees; both current QuestionnaireForm sources stop at Hips",
      ["screenshot_matches_deployed_but_not_branch", "stale_build_possible", "requires_owner_review"],
      "do_not_add_in_E_or_F_without_separate_decision", false),
    drift("resistance_band_detail", "Owner reports a conditional detail state; no subtype, anchor, or band-detail branch code/render exists",
      ["conditional_state_not_captured", "owner_observation_unverified", "stale_build_possible", "requires_owner_review"],
      "design_progressive_disclosure_without_claiming_current_implementation", true),
    drift("consumer_training_mode", "Consumer renders Build, Maintain, Recover cards and matches the screenshot",
      ["screenshot_matches_current_branch"], "preserve_current_runtime_in_E_and_F", true),
    drift("gyms_training_mode", "Gyms schema accepts trainingIntent but its QuestionnaireForm renders no mode picker",
      ["consumer_gyms_difference", "current_branch_only"], "record_parity_gap_keep_gyms_runtime_unchanged", true),
    drift("mobile_owner_crops", "Owner declares eight mobile crops, but no independently identifiable mobile crop exists in the local eight-binary inventory",
      ["owner_observation_unverified", "not_material_to_Chunk_E"],
      "use_owner_observation_as_evidence_and_current_head_mobile_renders_for_branch_verification", false),
    drift("binary_inventory", "Owner declares 13 logical images while eight 4480x1440 binaries are locally present; three include partial or unrelated desktop context",
      ["requires_owner_review", "not_material_to_Chunk_E"], "record_without_requesting_images_again", false),
    drift("training_intent_signature", "trainingIntent is persisted and consumed by engine/shadow mapping but omitted from buildQuestionnaireSignature",
      ["historical_compatibility_behavior", "future_architecture_difference"], "signature_v2_design_required_before_activation", true),
    drift("legacy_gym_expansion", "normalizeEquipmentSelection expands gym to dumbbells, barbell, kettlebell, cables, machines, and bench",
      ["historical_compatibility_behavior", "future_architecture_difference"], "preserve_legacy_replay_but_do_not_copy_into_v2_profile", true),
    drift("gyms_buyer_demo_equipment", "Buyer demo replaces equipment checkboxes with a gym-owner configured environment panel",
      ["current_branch_only", "consumer_gyms_difference"], "gym_owner_lock_remains_authoritative", true),
    drift("movement_profile_title", "Screenshot and branch title both say Build your Praxis movement profile",
      ["screenshot_matches_current_branch", "future_architecture_difference"],
      "later_copy_target_broadens_to_training_profile_F_may_preserve_current", true),
  ]),
  unresolvedCount: 4,
  topClassificationStillEarnable: true,
  rationale: "The unresolved discrepancies are documented and do not prevent selecting or specifying the one consumer surface.",
});

const ownershipRow = (
  field: string,
  classifications: readonly OwnershipClassification[],
  currentBehavior: string,
  futureDisposition: string,
) => Object.freeze({ field, classifications: Object.freeze(classifications), currentBehavior, futureDisposition });

export const currentOwnership = Object.freeze({
  rows: Object.freeze([
    ownershipRow("goals", ["legacy_Product_authority", "current_UI_only", "current_engine_input",
      "current_signature_input", "current_shadow_mapping_input", "duplicated_consumer_gyms"],
      "select label persists, regenerates legacy Program, signs change identity, and enters shadow mapping",
      "migrate explicitly to canonical primaryGoal ID"),
    ownershipRow("painAreas", ["legacy_Product_authority", "current_engine_input", "current_signature_input",
      "current_shadow_mapping_input", "context_only", "duplicated_consumer_gyms"],
      "checkbox regions persist, influence legacy generation, sign identity, and map as context",
      "retain as optional programmingContexts without outcome ownership"),
    ownershipRow("experience", ["legacy_Product_authority", "current_engine_input", "current_signature_input",
      "current_shadow_mapping_input", "duplicated_consumer_gyms"],
      "coarse label persists and enters legacy generation/signature/shadow",
      "retain as coarseExperience; calibration owns exact realization"),
    ownershipRow("equipment", ["legacy_Product_authority", "current_engine_input", "current_signature_input",
      "current_shadow_mapping_input", "duplicated_consumer_gyms"],
      "top-level labels persist; legacy gym expands capability; shadow records presence only",
      "separate environment from exact capabilities"),
    ownershipRow("daysPerWeek", ["legacy_Product_authority", "current_engine_input", "current_signature_input",
      "current_shadow_mapping_input", "duplicated_consumer_gyms"],
      "3/4/5 persists, shapes generation/signature, and maps opportunity count",
      "retain as opportunity count without weekday or duration inference"),
    ownershipRow("trainingIntent", ["legacy_Product_authority", "current_UI_only", "current_engine_input",
      "current_shadow_mapping_input", "duplicated_consumer_gyms"],
      "consumer renders it; gyms schema accepts it but does not render it; engine defaults absent to build; signature omits it",
      "versioned trainingMode semantic input before activation"),
    ownershipRow("questionnaire_storage", ["legacy_Product_authority"],
      "localStorage plus server training snapshot patch", "old profiles remain readable; no migration on read"),
    ownershipRow("questionnaire_signature_v1", ["legacy_Product_authority", "migration_required"],
      "JSON identity over goals, painAreas, experience, equipment, daysPerWeek", "freeze V1 and add explicit V2"),
    ownershipRow("gym_equipment_lock", ["current_UI_only", "locked_by_gym_owner"],
      "buyer-demo presentation normalizes and overwrites equipment with configured gym profile",
      "surface-specific presentation over a future shared schema"),
    ownershipRow("band_subtype", ["unresolved", "future_structured_input"],
      "owner-reported but absent from branch", "conditional capability only when legality requires"),
    ownershipRow("goalFocus", ["future_structured_input"], "not captured", "required for broad goals"),
    ownershipRow("secondaryGoal", ["future_structured_input"], "not captured", "optional, collapsed, at most one"),
    ownershipRow("sessionMinutes", ["future_structured_input"], "not captured", "required for exact fit claims"),
    ownershipRow("equipmentCapabilities", ["future_structured_input"], "not captured", "minimal conditional legality facts"),
    ownershipRow("page_title_and_helper", ["display_only", "duplicated_consumer_gyms"],
      "consumer and ordinary gyms share current copy; buyer demo diverges", "future consumer training-profile copy"),
    ownershipRow("assessment_photos", ["context_only"], "separate Step 1 local assessment input",
      "no upload requirement for pain/context migration"),
  ]),
  auditAnswers: Object.freeze({
    legacyProgramRegenerationFields: Object.freeze(["goals", "painAreas", "experience", "equipment", "daysPerWeek", "trainingIntent"]),
    currentSignatureFields: Object.freeze(["goals", "painAreas", "experience", "equipment", "daysPerWeek"]),
    currentShadowMappingFields: Object.freeze(["goals", "painAreas", "experience", "equipment", "daysPerWeek", "trainingIntent"]),
    trainingIntentParticipatesInChangeIdentity: false,
    consumerAndGymsSchemasIdentical: true,
    schemaParityQualification: "duplicated structural types are currently equivalent, but presentation and option ownership differ",
    gymModeLockLayer: "presentation_and_normalization_layer_not_schema",
    futureCanonicalContractLocation:
      "a new inert Product-owned contract module, separate from QuestionnaireForm and engine generation, before activation",
    fCanAddInactiveOptionWithoutRouteChange: true,
    fCanAvoidLegacyGenerateProgram: true,
    existingConfirmationCanRemainExact: true,
    currentStoredValuesRemainReadable: true,
    newSchemaVersionRequiredBeforeActivation: true,
    legacyGymOverstatesCapability: true,
    reportedBandSubtypePresentInBranch: false,
    kneesPresentInBranchQuestionnaire: false,
    deploymentDrift: Object.freeze(["knees_pain_choice", "resistance_band_detail", "owner_declared_mobile_crop_inventory"]),
    eTopClassificationCanBeEarnedWithRecordedDrift: true,
  }),
});

export const dEvidenceConsequences = Object.freeze({
  currentProductStrictlyCompletePrograms: 0,
  currentProductHonestIncompleteCases: 54,
  futureCalibrationComplete: Object.freeze({
    getStronger: 496,
    buildMuscle: 108,
    fitnessAndStamina: 75,
    postureAndMovement: 108,
    athleticPerformance: 0,
  }),
  bindingPriorities: Object.freeze([
    "primary_goal_and_follow_up",
    "goal_specific_purpose_or_focus",
    "pain_context_separation",
    "exact_equipment_capability_when_legality_requires",
  ]),
  minutesRequiredForExactFeasibility: true,
  exactLoadAlwaysRequired: false,
  calibrationCanSubstituteExactLoadWhenLegal: true,
  completedPerformanceAndResponseOwner: "Longitudinal_only",
});

export const visualInvariants = Object.freeze({
  preserve: Object.freeze([
    { invariant: "photographic_background", source: "BackgroundShell app-bg and --hero-image" },
    { invariant: "dark_glass_panel", source: "ui-card / praxis-panel-strong" },
    { invariant: "constrained_page_rhythm", source: "ui-shell max-width and responsive padding" },
    { invariant: "header_relationship", source: "ui-page-heading plus OnImage" },
    { invariant: "selected_surface", source: "sky border/ring or praxis-selected-surface" },
    { invariant: "primary_action", source: "linear-gradient #38BDF8 to #2563EB" },
    { invariant: "typography", source: "Space Grotesk headings and Manrope body" },
    { invariant: "compact_cards", source: "0.5rem shared card radius" },
    { invariant: "responsive_grids", source: "single column base with sm grid expansion" },
    { invariant: "back_to_photos", source: "questionnaire page header action" },
    { invariant: "guide_and_menu", source: "fixed onboarding guide and AppMenu controls" },
  ]),
  hardCodedNewColorsRequired: false,
  newDesignSystemRequired: false,
  screenshotMatch: "MATERIAL_VISUAL_LANGUAGE_MATCH",
});

export const informationArchitecture = Object.freeze({
  direction: "ONE_SURFACE_PROGRESSIVE_DISCLOSURE_UNDER_60_SECONDS",
  selectedSurface: Object.freeze({
    app: "consumer",
    route: "/questionnaire",
    component: "apps/consumer/src/components/QuestionnaireForm.tsx",
    pageTitle: "Build your Praxis movement profile",
  }),
  eventualOrder: Object.freeze([
    "primary_goal",
    "conditional_goal_focus",
    "optional_secondary_goal_disclosure",
    "pain_or_limitations_context",
    "training_mode",
    "days_per_week",
    "session_minutes_when_exact_feasibility_required",
    "coarse_experience",
    "equipment_environment",
    "conditional_equipment_capability",
    "submit",
  ]),
  sections: Object.freeze([
    { id: "goal", fields: Object.freeze(["primary_goal", "conditional_goal_focus", "optional_secondary_goal_disclosure"]) },
    { id: "train_around_context", fields: Object.freeze(["pain_or_limitations_context", "minimal_legality_context"]) },
    { id: "training_mode", fields: Object.freeze(["develop", "maintain", "return_or_rebuild"]) },
    { id: "schedule", fields: Object.freeze(["days_per_week", "conditional_session_minutes"]) },
    { id: "experience", fields: Object.freeze(["coarse_experience"]) },
    { id: "equipment", fields: Object.freeze(["equipment_environment", "conditional_capability"]) },
  ]),
  ordinarySupportedPathTargetSeconds: 60,
  giantQuestionnaire: false,
  multiPageWizard: false,
  fReordersCurrentFields: false,
});

type GoalOption = {
  id: string;
  displayLabel: string;
  canonicalOutcome: string | null;
  states: readonly GoalOptionState[];
  requiredFollowUp: string | null;
  compatibleContexts: readonly string[];
  supportedPolicyScope: string;
  productMappingProfile: string;
  legacyMappingBehavior: string;
  submissionBehavior: string;
  provenance: string;
};

const goal = (value: GoalOption) => Object.freeze({ ...value, states: Object.freeze(value.states),
  compatibleContexts: Object.freeze(value.compatibleContexts) });

export const goalOptionPolicy = Object.freeze({
  stateVocabulary: Object.freeze<GoalOptionState[]>([
    "legacy_active", "future_inactive_internal", "future_shadow_only", "owner_account_only",
    "generally_available", "follow_up_required", "policy_required", "deprecated_legacy", "unsupported",
  ]),
  options: Object.freeze([
    goal({ id: "improve_posture_legacy", displayLabel: "Improve posture",
      canonicalOutcome: "posture_and_movement_quality", states: ["legacy_active"], requiredFollowUp: null,
      compatibleContexts: ["pain_aware_return"], supportedPolicyScope: "legacy_product_plus_bounded_shadow_mapping",
      productMappingProfile: "current_and_B1_B4_shadow", legacyMappingBehavior: "unchanged",
      submissionBehavior: "legacy_generateProgram", provenance: "current_consumer_and_gyms" }),
    goal({ id: "reduce_pain_legacy", displayLabel: "Reduce pain", canonicalOutcome: null,
      states: ["legacy_active", "deprecated_legacy", "follow_up_required"], requiredFollowUp: "primary_outcome",
      compatibleContexts: ["pain_aware_return"], supportedPolicyScope: "legacy_only_context_in_future",
      productMappingProfile: "context_only", legacyMappingBehavior: "unchanged_until_confirmed_migration",
      submissionBehavior: "legacy_generateProgram_only", provenance: "current_consumer_and_gyms" }),
    goal({ id: "athletic_performance_legacy", displayLabel: "Athletic performance", canonicalOutcome: null,
      states: ["legacy_active", "follow_up_required", "policy_required"], requiredFollowUp: "performance_focus",
      compatibleContexts: [], supportedPolicyScope: "strength_and_local_endurance_only_when_explicit",
      productMappingProfile: "follow_up_required", legacyMappingBehavior: "unchanged",
      submissionBehavior: "legacy_generateProgram_only", provenance: "current_consumer_and_gyms" }),
    goal({ id: "general_fitness_legacy", displayLabel: "General fitness", canonicalOutcome: "general_fitness",
      states: ["legacy_active", "follow_up_required"], requiredFollowUp: "fitness_focus",
      compatibleContexts: ["pain_aware_return"], supportedPolicyScope: "reviewed_purpose_bundle_required",
      productMappingProfile: "follow_up_required", legacyMappingBehavior: "unchanged",
      submissionBehavior: "legacy_generateProgram_only", provenance: "current_consumer_and_gyms" }),
    goal({ id: "get_stronger", displayLabel: "Get stronger", canonicalOutcome: "strength",
      states: ["future_inactive_internal"], requiredFollowUp: null, compatibleContexts: ["pain_aware_return"],
      supportedPolicyScope: "bounded_strength_supported_core", productMappingProfile: "B1_B4_explicit_only",
      legacyMappingBehavior: "none", submissionBehavior: "preview_only_fail_closed", provenance: "owner_selected_F" }),
    goal({ id: "build_muscle", displayLabel: "Build muscle", canonicalOutcome: "hypertrophy",
      states: ["future_shadow_only"], requiredFollowUp: null, compatibleContexts: ["pain_aware_return"],
      supportedPolicyScope: "bounded_hypertrophy_supported_core_no_body_composition_claim",
      productMappingProfile: "B1_B4_explicit_only", legacyMappingBehavior: "none",
      submissionBehavior: "unavailable", provenance: "owner_approved_eventual_vocabulary" }),
    goal({ id: "improve_fitness_and_stamina", displayLabel: "Improve fitness and stamina",
      canonicalOutcome: "general_fitness", states: ["future_shadow_only", "follow_up_required", "policy_required"],
      requiredFollowUp: "fitness_focus", compatibleContexts: ["pain_aware_return"],
      supportedPolicyScope: "local_muscular_endurance_only_systemic_conditioning_unsupported",
      productMappingProfile: "B1_B4_explicit_only", legacyMappingBehavior: "none",
      submissionBehavior: "unavailable", provenance: "owner_approved_eventual_vocabulary" }),
    goal({ id: "improve_posture_and_movement", displayLabel: "Improve posture and movement",
      canonicalOutcome: "posture_and_movement_quality", states: ["future_shadow_only"], requiredFollowUp: null,
      compatibleContexts: ["pain_aware_return"], supportedPolicyScope: "bounded_movement_quality_no_clinical_claim",
      productMappingProfile: "B1_B4_explicit_only", legacyMappingBehavior: "explicit_future_migration",
      submissionBehavior: "unavailable", provenance: "owner_approved_eventual_vocabulary" }),
    goal({ id: "improve_athletic_performance", displayLabel: "Improve athletic performance", canonicalOutcome: null,
      states: ["future_shadow_only", "follow_up_required", "policy_required"], requiredFollowUp: "performance_focus",
      compatibleContexts: ["pain_aware_return"],
      supportedPolicyScope: "strength_or_local_endurance_only_when_explicit_power_conditioning_sport_specific_unsupported",
      productMappingProfile: "B1_B4_explicit_only", legacyMappingBehavior: "none",
      submissionBehavior: "unavailable", provenance: "owner_approved_eventual_vocabulary" }),
  ]),
  selectedImmediateOption: "get_stronger",
});

export const primaryGoalDesign = Object.freeze({
  selectedControl: "native_or_equivalently_accessible_compact_select",
  fieldLabel: "What do you want to work toward?",
  compactLabel: "Primary goal",
  canonicalValueUsesStableId: true,
  closedRegistry: true,
  fuzzyMatching: false,
  arbitraryStringBehavior: false,
});

export const followUpDesign = Object.freeze({
  placement: "inline_directly_below_primary_goal",
  modal: false,
  separateRoute: false,
  generalFitness: Object.freeze({
    prompt: "What matters most right now?",
    options: Object.freeze(["mixed_general_fitness", "local_muscular_endurance", "systemic_conditioning", "reviewed_combination"]),
    systemicConditioningDisposition: "policy_required_not_remapped",
  }),
  fitnessAndStamina: Object.freeze({
    prompt: "What matters most right now?",
    options: Object.freeze(["mixed_general_fitness", "local_muscular_endurance", "systemic_conditioning", "reviewed_combination"]),
    systemicConditioningDisposition: "policy_required_not_remapped",
  }),
  athleticPerformance: Object.freeze({
    prompt: "What kind of performance are you training for?",
    options: Object.freeze(["strength", "power_explosiveness", "muscular_endurance", "conditioning",
      "sport_activity_specific_preparation", "reviewed_combination"]),
    unsupportedDisposition: "visibly_unavailable_or_follow_up_required",
  }),
  noRequiredFollowUp: Object.freeze(["get_stronger", "build_muscle", "improve_posture_and_movement"]),
});

export const painContextDesign = Object.freeze({
  label: "Anything Praxis should train around?",
  helper: "Pain or limitations change how the plan is realized. They do not replace your goal.",
  alternativeHelper:
    "Praxis will use this to adjust exercise selection and setup - not to diagnose you.",
  optional: true,
  futureNoneState: "No current pain or limitations",
  mutuallyExclusiveNone: true,
  diagnosisInferenceCount: 0,
  severityInferenceCount: 0,
  permanentExerciseBlockCount: 0,
  genericCorrectiveCircuitCount: 0,
  safetyEscalationFromRegionAloneCount: 0,
  photoUploadRequired: false,
  kneesDisposition: "OWNER_REVIEW_REQUIRED_NO_E_OR_F_CODE_CHANGE",
});

export const reducePainMigration = Object.freeze({
  trigger: "existing_legacy_goal_reduce_pain",
  display: "Your previous focus was \"Reduce pain.\"",
  prompt:
    "What would you like to work toward while Praxis trains around your pain or limitations?",
  preserveCurrentProgramUntilConfirm: true,
  preservePainRegions: true,
  requirePrimaryOutcome: true,
  silentlyChoosePosture: false,
  regenerateOnRead: false,
  migrateOnRead: false,
  preserveHistory: true,
  implementedInF: false,
});

export const trainingModeDesign = Object.freeze({
  label: "How should Praxis approach your training right now?",
  modes: Object.freeze([
    { id: "develop", label: "Develop", copy: "Build from your current level." },
    { id: "maintain", label: "Maintain", copy: "Keep your current training level and routine." },
    { id: "return_or_rebuild", label: "Return or rebuild", copy: "Ease back after time away or changed tolerance." },
  ]),
  currentBuildCopyIssue: "Build strength and skill week to week conflates developmental mode with the strength outcome",
  separateFromOutcome: true,
  fPolicyActivationCount: 0,
});

export const secondaryGoalDesign = Object.freeze({
  disclosureLabel: "Add a secondary goal",
  collapsedByDefault: true,
  maximumCount: 1,
  mayEqualPrimary: false,
  mayOverridePrimary: false,
  removable: true,
  inline: true,
  implementedInF: false,
});

export const scheduleExperienceEquipmentDesign = Object.freeze({
  days: Object.freeze({ label: "How many days can you train most weeks?", currentOptions: Object.freeze([3, 4, 5]),
    inferWeekdays: false, inferDates: false, inferSpacing: false, inferTwoADays: false, inferMinutes: false }),
  minutes: Object.freeze({ label: "How long can most sessions be?", includeNotSure: true,
    evidenceCandidates: Object.freeze([25, 30, 45, 60, 70]),
    finalOptionDisposition: "OWNER_REVIEW_REQUIRED_BEFORE_IMPLEMENTATION",
    missingMeansExactFit: false, implementedInF: false }),
  experience: Object.freeze({ options: Object.freeze(["Beginner", "Intermediate", "Advanced"]),
    helper: "This helps Praxis choose a starting approach. It does not assume your exact loads or familiarity with every exercise.",
    trainingYearsInF: false, exactLoadInference: false, exactVolumeInference: false,
    exerciseFamiliarityInference: false, recoveryInference: false }),
  equipment: Object.freeze({
    topLevel: Object.freeze(["No equipment", "Resistance bands", "Dumbbells", "Gym"]),
    separation: Object.freeze(["environment", "capability", "exact_load_realization"]),
    strategy: "smallest_truthful_hybrid_upfront_environment_plus_material_inline_capability",
    bands: Object.freeze(["long_resistance_band", "loop_miniband", "both", "stable_anchor_available",
      "anchor_unavailable", "not_sure"]),
    dumbbells: Object.freeze(["pair_available", "adjustable_or_fixed", "adjustable_bench_available",
      "heaviest_available", "smallest_increment", "not_sure"]),
    gym: Object.freeze(["dumbbells", "cable_station", "strength_machines", "barbell_and_rack",
      "adjustable_bench", "pull_up_or_assisted_pull_up_station"]),
    none: Object.freeze(["floor_space", "wall", "stable_chair_table_or_support", "pull_up_bar"]),
    allDetailsInitiallyVisible: false,
    kilogramEquivalenceForBands: false,
    universalGymInferenceCount: 0,
    exactLoadInitialRequirement: false,
    calibrationMaySubstituteWhenBaseLegalityKnown: true,
  }),
});

export const responsiveAccessibility = Object.freeze({
  desktop: Object.freeze({
    constrainedColumn: true,
    sidePanelRequired: false,
    conditionalFollowUpWithinGoalSection: true,
    twoColumnChecksWhereLabelsFit: true,
    ctaFullWidth: true,
    horizontalOverflowAllowed: false,
  }),
  mobile: Object.freeze({
    widths: Object.freeze([320, 360, 390]),
    columns: 1,
    minimumTouchTargetPx: 44,
    inlineFollowUp: true,
    hoverOnlyBehavior: false,
    horizontalScrollAllowed: false,
    fixedCta: false,
    bottomSafeSpaceRequired: true,
    screenReaderOrderMatchesVisual: true,
    reducedMotionRequired: true,
  }),
  accessibilityContract: Object.freeze([
    "semantic_form",
    "fieldsets_and_legends_for_grouped_choices",
    "programmatic_label_association",
    "aria_describedby_for_helper_and_error",
    "keyboard_selection",
    "visible_focus",
    "selection_not_color_only",
    "44_by_44_touch_target",
    "sufficient_contrast",
    "inline_errors",
    "explained_disabled_options",
    "reduced_motion",
    "native_select_or_equivalent_semantics",
    "stable_tab_order",
    "no_unexpected_navigation_on_selection",
  ]),
  reviewMatrix: Object.freeze([
    "keyboard", "screen_reader_semantics", "focus_order", "focus_visibility", "touch_target",
    "text_scaling", "200_percent_zoom", "320px", "360px", "390px", "768px", "1024px",
    "1440px", "reduced_motion", "high_contrast_where_feasible", "fixed_info_menu_overlap",
    "long_translated_labels_future_risk",
  ]),
  wcagConformanceClaimed: false,
  currentRenderResult: "NO_OVERFLOW_OR_FIXED_CONTROL_OVERLAP_IN_CAPTURED_MATRIX",
});

export const copyMatrix = Object.freeze([
  { surface: "page", fieldId: "page_intro", owner: "Product", label: "Build your Praxis training profile",
    helper: "Choose what you're working toward, what Praxis should train around, and the equipment you can use. You can update this later.",
    optionLabels: [], statusCopy: null, validationCopy: null, unsupportedCopy: null, migrationCopy: null,
    mobileNotes: "wrap title naturally", accessibilityDescription: "h1 plus supporting paragraph", fRelevance: "may_preserve_current", laterRelevance: "target" },
  { surface: "questionnaire", fieldId: "primary_goal", owner: "Product", label: "What do you want to work toward?",
    helper: "Choose one primary outcome.", optionLabels: goalOptionPolicy.options.map((option) => option.displayLabel),
    statusCopy: "Unavailable in your current plan", validationCopy: "Choose a primary goal.",
    unsupportedCopy: "This goal needs another choice before Praxis can build a plan.", migrationCopy: null,
    mobileNotes: "full_width_native_select", accessibilityDescription: "labelled select with helper and status description", fRelevance: "get_stronger_preview", laterRelevance: "target" },
  { surface: "questionnaire", fieldId: "fitness_focus", owner: "Product", label: "What matters most right now?",
    helper: "Choose the focus that best matches your goal.", optionLabels: followUpDesign.generalFitness.options,
    statusCopy: null, validationCopy: "Choose a fitness focus.", unsupportedCopy: "Conditioning needs a separately supported policy.", migrationCopy: null,
    mobileNotes: "inline_below_goal", accessibilityDescription: "fieldset and legend", fRelevance: "none", laterRelevance: "required_for_broad_goal" },
  { surface: "questionnaire", fieldId: "performance_focus", owner: "Product", label: "What kind of performance are you training for?",
    helper: "Choose the performance quality you want to develop.", optionLabels: followUpDesign.athleticPerformance.options,
    statusCopy: null, validationCopy: "Choose a performance focus.", unsupportedCopy: "This focus is not yet available for plan generation.", migrationCopy: null,
    mobileNotes: "inline_below_goal", accessibilityDescription: "fieldset and legend", fRelevance: "none", laterRelevance: "required_for_athletic" },
  { surface: "questionnaire", fieldId: "pain_context", owner: "Product", label: painContextDesign.label,
    helper: painContextDesign.helper, optionLabels: ["No current pain or limitations", "Neck", "Upper back", "Lower back", "Shoulders", "Hips"],
    statusCopy: null, validationCopy: null, unsupportedCopy: null, migrationCopy: null,
    mobileNotes: "one_column_when_needed", accessibilityDescription: "optional checkbox fieldset with exclusive none option", fRelevance: "unchanged", laterRelevance: "target" },
  { surface: "migration", fieldId: "reduce_pain_migration", owner: "Product", label: reducePainMigration.display,
    helper: reducePainMigration.prompt, optionLabels: [], statusCopy: "Your current plan stays active until you confirm.",
    validationCopy: "Choose a primary goal to continue.", unsupportedCopy: null, migrationCopy: reducePainMigration.prompt,
    mobileNotes: "inline_not_modal_for_choice", accessibilityDescription: "status then labelled primary goal control", fRelevance: "none", laterRelevance: "required" },
  { surface: "questionnaire", fieldId: "training_mode", owner: "Product", label: trainingModeDesign.label,
    helper: "Choose the approach that fits your current training state.", optionLabels: trainingModeDesign.modes.map((mode) => mode.label),
    statusCopy: null, validationCopy: "Choose a training approach.", unsupportedCopy: "This mode needs additional policy before activation.", migrationCopy: null,
    mobileNotes: "stack_cards", accessibilityDescription: "fieldset with radio semantics and descriptions", fRelevance: "unchanged", laterRelevance: "target" },
  { surface: "questionnaire", fieldId: "secondary_goal", owner: "Product", label: "Add a secondary goal",
    helper: "Optional. Your primary goal remains in charge.", optionLabels: [], statusCopy: null,
    validationCopy: "Choose a goal different from your primary goal.", unsupportedCopy: "This combination is not yet supported.", migrationCopy: null,
    mobileNotes: "collapsed_disclosure", accessibilityDescription: "button with expanded state and labelled region", fRelevance: "none", laterRelevance: "optional" },
  { surface: "questionnaire", fieldId: "days_per_week", owner: "Product", label: scheduleExperienceEquipmentDesign.days.label,
    helper: "Choose 3, 4, or 5 days.", optionLabels: ["3 days", "4 days", "5 days"], statusCopy: null,
    validationCopy: "Choose how many days you can train.", unsupportedCopy: null, migrationCopy: null,
    mobileNotes: "three_compact_buttons", accessibilityDescription: "fieldset with radio semantics", fRelevance: "unchanged", laterRelevance: "target" },
  { surface: "questionnaire", fieldId: "session_minutes", owner: "Product", label: scheduleExperienceEquipmentDesign.minutes.label,
    helper: "Choose a typical session length or Not sure.", optionLabels: ["25 minutes", "30 minutes", "45 minutes", "60 minutes", "70 minutes", "Not sure"],
    statusCopy: "Duration unknown", validationCopy: null, unsupportedCopy: null, migrationCopy: null,
    mobileNotes: "compact_select_or_wrapping_buttons", accessibilityDescription: "labelled control with duration-unknown description", fRelevance: "none", laterRelevance: "owner_review_required" },
  { surface: "questionnaire", fieldId: "experience", owner: "Product", label: "Training experience",
    helper: scheduleExperienceEquipmentDesign.experience.helper, optionLabels: scheduleExperienceEquipmentDesign.experience.options,
    statusCopy: null, validationCopy: "Choose your current experience level.", unsupportedCopy: null, migrationCopy: null,
    mobileNotes: "stack_at_narrow_width", accessibilityDescription: "fieldset with radio semantics", fRelevance: "unchanged", laterRelevance: "target" },
  { surface: "questionnaire", fieldId: "equipment_environment", owner: "Product", label: "Equipment",
    helper: "Choose the equipment environment you can use.", optionLabels: scheduleExperienceEquipmentDesign.equipment.topLevel,
    statusCopy: null, validationCopy: "Choose an equipment environment.", unsupportedCopy: null, migrationCopy: null,
    mobileNotes: "one_column_when_labels_need", accessibilityDescription: "fieldset with checkbox or exclusive environment semantics", fRelevance: "unchanged", laterRelevance: "target" },
  { surface: "questionnaire", fieldId: "band_detail", owner: "Product", label: "Which resistance bands can you use?",
    helper: "Choose only what you know is available.", optionLabels: scheduleExperienceEquipmentDesign.equipment.bands,
    statusCopy: "More detail is needed for a legal exercise choice.", validationCopy: "Choose a band type or Not sure.",
    unsupportedCopy: null, migrationCopy: null, mobileNotes: "inline_below_bands", accessibilityDescription: "conditional fieldset announced after expansion", fRelevance: "none", laterRelevance: "conditional" },
  { surface: "questionnaire", fieldId: "submit", owner: "Product", label: "Build my Praxis plan",
    helper: "", optionLabels: [], statusCopy: "Plan generation is unavailable for this preview option.",
    validationCopy: "Review the highlighted fields.", unsupportedCopy: "This selection cannot generate a plan yet.", migrationCopy: null,
    mobileNotes: "full_width_not_fixed", accessibilityDescription: "submit button with busy and disabled explanation", fRelevance: "preview_must_fail_closed", laterRelevance: "target" },
]);

export const stateMachine = Object.freeze({
  states: Object.freeze([
    "pristine", "loaded_legacy_profile", "editing", "conditional_follow_up_open",
    "optional_secondary_open", "incomplete", "unsupported_focus", "equipment_detail_required",
    "equipment_detail_unresolved", "inactive_preview_selected", "dirty_current_profile",
    "confirmation_required", "active_session_warning", "submitting_legacy",
    "future_submission_unavailable", "migration_required", "cancel_revert",
  ]),
  transitions: Object.freeze([
    ["pristine", "editing", "edit_current_field"],
    ["loaded_legacy_profile", "editing", "edit_current_field"],
    ["loaded_legacy_profile", "migration_required", "legacy_reduce_pain_detected"],
    ["editing", "conditional_follow_up_open", "select_broad_goal"],
    ["editing", "optional_secondary_open", "open_secondary_disclosure"],
    ["editing", "dirty_current_profile", "change_signed_legacy_field"],
    ["conditional_follow_up_open", "unsupported_focus", "select_unsupported_focus"],
    ["conditional_follow_up_open", "editing", "select_supported_focus"],
    ["editing", "equipment_detail_required", "select_equipment_requiring_legality_fact"],
    ["equipment_detail_required", "equipment_detail_unresolved", "leave_required_detail_unknown"],
    ["equipment_detail_required", "editing", "resolve_required_detail"],
    ["editing", "inactive_preview_selected", "select_explicit_preview_get_stronger"],
    ["inactive_preview_selected", "future_submission_unavailable", "attempt_submit"],
    ["unsupported_focus", "future_submission_unavailable", "attempt_submit"],
    ["equipment_detail_unresolved", "incomplete", "attempt_submit"],
    ["dirty_current_profile", "confirmation_required", "submit_current_legacy_profile"],
    ["confirmation_required", "active_session_warning", "active_session_exists"],
    ["confirmation_required", "submitting_legacy", "confirm_without_active_session"],
    ["active_session_warning", "submitting_legacy", "confirm_current_legacy_change"],
    ["confirmation_required", "cancel_revert", "cancel"],
    ["active_session_warning", "cancel_revert", "cancel"],
    ["cancel_revert", "loaded_legacy_profile", "restore_exact_committed_state"],
    ["migration_required", "cancel_revert", "cancel_migration"],
  ].map(([from, to, event]) => Object.freeze({ from, to, event }))),
  prohibitedTransitions: Object.freeze([
    "inactive_preview_selected_to_submitting_legacy",
    "unsupported_focus_to_submitting_legacy",
    "equipment_detail_unresolved_to_submitting_legacy",
    "selection_to_persistence_without_confirmation",
  ]),
  previewReachesLegacyGeneration: false,
  unsupportedReachesGeneration: false,
  silentStoredProfileChange: false,
  cancelRestoresExactCommittedState: true,
  currentLegacyFlowRepresentable: true,
});

export const signatureV2Design = Object.freeze({
  reference: QUESTIONNAIRE_SIGNATURE_V2_REFERENCE,
  implemented: false,
  canonicalIdsNotLabels: true,
  semanticInputs: Object.freeze([
    { field: "primaryGoal", ownership: "program_affecting" },
    { field: "secondaryGoal", ownership: "program_affecting_optional" },
    { field: "goalFocus", ownership: "program_affecting" },
    { field: "programmingContexts", ownership: "realization_affecting" },
    { field: "trainingMode", ownership: "program_affecting" },
    { field: "daysPerWeek", ownership: "program_affecting" },
    { field: "sessionMinutes", ownership: "realization_affecting" },
    { field: "coarseExperience", ownership: "realization_affecting" },
    { field: "equipmentEnvironment", ownership: "realization_affecting" },
    { field: "materialEquipmentCapabilities", ownership: "realization_affecting" },
  ]),
  excludedClasses: Object.freeze(["Longitudinal_only", "display_only", "migration_only"]),
  currentTrainingIntentAbsentFromV1Signature: true,
  currentSignatureChangedInE: false,
});

export const productProfileV2Design = Object.freeze({
  reference: PRODUCT_PROFILE_V2_REFERENCE,
  typeName: "ProductTrainingProfileV2",
  implemented: false,
  fields: Object.freeze([
    "contractVersion", "primaryGoal", "optionalSecondaryGoal", "goalFocus", "programmingContexts",
    "trainingMode", "daysPerWeek", "sessionMinutes", "coarseExperience", "equipmentEnvironment",
    "equipmentCapabilities", "source", "reviewState", "legacyProjection", "provenance",
  ]),
  prohibitedFields: Object.freeze(["exercise", "dose", "Program", "diagnosis", "freeTextParsedIntent"]),
  runtimeExportCount: 0,
  recommendedOwner: "future_Product_profile_contract_module",
});

export const legacyCompatibility = Object.freeze({
  goals: Object.freeze(["Improve posture", "Reduce pain", "Athletic performance", "General fitness"]),
  modes: Object.freeze(["build", "maintain", "rehab", "absent_defaults_to_build"]),
  equipment: Object.freeze(["none", "bands", "dumbbells", "gym"]),
  experience: Object.freeze(["Beginner", "Intermediate", "Advanced"]),
  oldProfilesLoad: true,
  oldProgramsRemainValid: true,
  migrationOnReadCount: 0,
  regenerationOnReadCount: 0,
  silentGoalRewriteCount: 0,
  explicitConfirmationBeforeMigration: true,
  historicalShadowReplayExact: true,
  currentRouteExact: true,
});

export const consumerGymsParity = Object.freeze({
  schemaStructureCurrentlyEquivalent: true,
  schemaDefinitionsDuplicated: true,
  optionRegistriesDuplicated: true,
  routeOwnership: Object.freeze({ consumer: "apps/consumer/src/app/questionnaire/page.tsx",
    gyms: "apps/gyms/src/app/questionnaire/page.tsx" }),
  visualDifferences: Object.freeze(["consumer_ui_card_vs_gyms_praxis_panel_tokens", "buyer_demo_copy_and_equipment_panel"]),
  trainingModeVisibility: Object.freeze({ consumer: true, gyms: false }),
  lockedEquipmentBehavior: "buyer_demo_gym_owner_configuration_replaces_equipment_picker",
  buyerDemoBehavior: "alternate page copy locked gym equipment and demo results URL",
  browserTests: Object.freeze(["consumer_current_render", "gyms_current_render", "both_shadow_invariance"]),
  futureDirection: "one canonical Product input schema and option registry with surface-specific presentation",
  fScope: "consumer_inactive_preview_only_unless_shared_inert_registry_is_proven_safer",
  gymsRuntimeChangesInE: 0,
});

export const designRisks = Object.freeze([
  { id: "form_height", severity: "high", owner: "Product", evidence: "single page is already long on 390px",
    mitigation: "conditional disclosure and collapsed secondary goal", fRelevance: "low", laterRelevance: "high" },
  { id: "fixed_control_overlap", severity: "high", owner: "Frontend", evidence: "Info and Menu are fixed near final CTA",
    mitigation: "retain ui-shell bottom safe space and automated overlap checks", fRelevance: "medium", laterRelevance: "high" },
  { id: "secondary_text_contrast", severity: "medium", owner: "Design system", evidence: "small slate copy overlays photographic background",
    mitigation: "contrast audit against actual glass surfaces", fRelevance: "medium", laterRelevance: "high" },
  { id: "gyms_experience_contrast", severity: "medium", owner: "Gyms frontend", evidence: "unselected labels are faint in buyer-demo mobile render",
    mitigation: "separate later parity/contrast fix; no E runtime mutation", fRelevance: "none", laterRelevance: "medium" },
  { id: "native_select_explanation", severity: "medium", owner: "Product", evidence: "native options cannot carry rich descriptions consistently",
    mitigation: "concise helper/status below select", fRelevance: "medium", laterRelevance: "medium" },
  { id: "repeated_dark_panels", severity: "low", owner: "Design", evidence: "dense dark surfaces can flatten hierarchy",
    mitigation: "section ownership, spacing, and disclosure rather than new card layers", fRelevance: "low", laterRelevance: "medium" },
  { id: "build_copy_conflation", severity: "high", owner: "Product", evidence: "Build copy says strength while mode is not outcome",
    mitigation: "future Develop copy", fRelevance: "record_only", laterRelevance: "high" },
  { id: "reduce_pain_conflation", severity: "high", owner: "Product", evidence: "current goal makes context look like outcome",
    mitigation: "explicit confirmed migration", fRelevance: "none", laterRelevance: "high" },
  { id: "broad_goal_follow_up", severity: "high", owner: "Product policy", evidence: "General fitness and Athletic performance are underspecified",
    mitigation: "inline required focus and fail closed", fRelevance: "none", laterRelevance: "high" },
  { id: "equipment_overclaim", severity: "high", owner: "Product and engine", evidence: "labels do not prove capabilities",
    mitigation: "minimal conditional capability plus calibration", fRelevance: "none", laterRelevance: "high" },
  { id: "consumer_gyms_drift", severity: "medium", owner: "Product platform", evidence: "duplicated forms already differ on training mode and lock behavior",
    mitigation: "future shared canonical inert registry", fRelevance: "medium", laterRelevance: "high" },
  { id: "deployment_drift", severity: "medium", owner: "Release", evidence: "Knees and reported band detail differ from branch",
    mitigation: "explicit drift record and owner review before implementation", fRelevance: "low", laterRelevance: "medium" },
  { id: "legacy_regeneration", severity: "high", owner: "Product persistence", evidence: "signed changes regenerate and can end active session",
    mitigation: "inactive preview cannot dirty persist or submit", fRelevance: "critical", laterRelevance: "high" },
]);

export const designOptions = Object.freeze({
  compared: Object.freeze([
    { id: "A", label: "Keep current select plus inline follow-up", advantages: Object.freeze(["lowest_churn", "compact", "mobile_friendly", "native_accessibility", "ideal_for_F"]),
      risks: Object.freeze(["less_explanatory", "broad_goals_need_helper"]) },
    { id: "B", label: "Goal cards", advantages: Object.freeze(["expressive", "helper_copy", "comparison"]),
      risks: Object.freeze(["taller", "more_implementation", "mobile_scroll", "excessive_for_one_inactive_option"]) },
    { id: "C", label: "Separate goal step", advantages: Object.freeze(["focused_decision"]),
      risks: Object.freeze(["violates_one_surface", "slower", "navigation_and_migration_complexity"]) },
  ]),
  selected: "A",
  cardsDisposition: "optional_later_redesign",
});

export const fHandoff = Object.freeze({
  reference: F_HANDOFF_REFERENCE,
  option: Object.freeze({ id: "get_stronger", displayLabel: "Get stronger", canonicalOutcome: "strength",
    state: "future_inactive_internal" }),
  likelyAffectedFiles: Object.freeze([
    "apps/consumer/src/components/QuestionnaireForm.tsx",
    "apps/consumer/src/components/questionnaire/productGoalOptionRegistry.ts",
    "apps/consumer/tests/unit/inactiveGetStrongerOption.test.tsx",
    "apps/consumer/tests/e2e/inactiveGetStrongerPreview.spec.ts",
  ]),
  prohibitedFilesAndAreas: Object.freeze([
    "apps/consumer/src/app/questionnaire/page.tsx current route invocation",
    "apps/gyms runtime source",
    "packages/engine/src/questionnaireSignature.ts",
    "packages/engine/src/engine/engine.ts",
    "packages/engine/src/engine/engineAdapter.ts",
    "Product persistence and training sync",
    "Product Shadow trigger or current-route integration",
  ]),
  previewInjection: Object.freeze({
    mechanism: "explicit internal preview prop or isolated component harness",
    currentRoutesSupplyProp: false,
    environmentVariableDefault: false,
    ordinaryQueryStringActivation: false,
  }),
  visibility: Object.freeze({ consumerOrdinary: false, gymsOrdinary: false, buyerDemo: false }),
  behavior: Object.freeze({ render: true, select: true, exposeStructuredValue: true,
    persist: false, generateProgram: false, currentRouteShadow: false, returnV2Output: false,
    nonPreviewSubmit: "fail_closed", previewSubmit: "future_submission_unavailable" }),
  responsive: Object.freeze({ 360: "required", 390: "required", 1440: "required", noOverflow: true }),
  accessibility: Object.freeze({ nativeSelectSemantics: true, availabilityExplained: true,
    disabledWithoutExplanation: false, keyboard: true, visibleFocus: true }),
  testIds: Object.freeze(["goal-option-get-stronger", "goal-option-get-stronger-status",
    "inactive-goal-preview", "inactive-goal-submit-blocked"]),
  activationGuards: Object.freeze(["current_route_absent", "gyms_absent", "no_persistence",
    "no_signature_change", "no_generateProgram", "no_shadow_call", "no_v2_output"]),
  rollback: "remove preview registry option prop harness and F tests; current route remains byte-for-byte behaviorally unchanged",
  expectedClassification: "ONE_INACTIVE_PRODUCT_GOAL_OPTION_V1_READY_FOR_OWNER_ACCOUNT_GOAL_DELIVERY_DESIGN_AUTHORIZATION",
});

export const inputNecessityProjection = Object.freeze({
  firstSurface: Object.freeze(["primary_goal_or_follow_up", "goal_specific_purpose_or_focus",
    "pain_context_separation", "exact_equipment_capabilities_when_legality_requires_them"]),
  rows: Object.freeze([
    { fact: "primary_goal", initialSurface: "required", calibrationCanSubstitute: false },
    { fact: "general_fitness_purpose_bundle", initialSurface: "conditional_required", calibrationCanSubstitute: false },
    { fact: "athletic_performance_follow_up", initialSurface: "conditional_policy_required", calibrationCanSubstitute: false },
    { fact: "pain_context", initialSurface: "required_separate_ownership", calibrationCanSubstitute: false },
    { fact: "secondary_goal", initialSurface: "optional_later", calibrationCanSubstitute: false },
    { fact: "session_minutes", initialSurface: "conditional_exact_feasibility", calibrationCanSubstitute: false },
    { fact: "exact_equipment_capabilities", initialSurface: "conditional_legality_required", calibrationCanSubstitute: false },
    { fact: "coarse_experience", initialSurface: "preserve_current", calibrationCanSubstitute: true },
    { fact: "exact_load_history", initialSurface: "not_required_initially", calibrationCanSubstitute: true },
    { fact: "completed_performance_response", initialSurface: "Longitudinal_only", calibrationCanSubstitute: false },
  ]),
});

export const activationGuards = Object.freeze({
  consumerQuestionnaireFormRuntimeChanges: 0,
  gymsQuestionnaireFormRuntimeChanges: 0,
  questionnairePageRuntimeChanges: 0,
  productOptionChanges: 0,
  productCopyChanges: 0,
  painOptionChanges: 0,
  equipmentOptionChanges: 0,
  bandDetailImplementationChanges: 0,
  questionnaireDataChanges: 0,
  questionnaireSignatureChanges: 0,
  productPersistenceChanges: 0,
  generateProgramChanges: 0,
  currentRouteChanges: 0,
  currentTriggerChanges: 0,
  rolloutChanges: 0,
  productShadowCurrentRouteCalls: 0,
  v2OutputsReturned: 0,
  productMutations: 0,
  applications: 0,
  productActivations: 0,
  ownerScreenshotBinariesCommitted: 0,
  ownerPersonalDataCommitted: 0,
  fImplementationCount: 0,
  ledgerFinalStateChangedToCompleted: 0,
});

export const baseDesignGuardModel: DesignGuardModel = Object.freeze({
  surfaceCount: 1,
  targetOrder: informationArchitecture.eventualOrder,
  allFutureFieldsVisible: false,
  multiPageWizard: false,
  ordinaryFollowUpModal: false,
  painOwner: "context",
  diagnosisInferenceCount: 0,
  genericCorrectiveCircuitCount: 0,
  reducePainFuturePrimary: false,
  buildModeMapsToStrength: false,
  generalFitnessSilentDefault: null,
  athleticPerformanceSilentDefault: null,
  gymUniversalCapabilityInferenceCount: 0,
  dumbbellCapabilityInferenceCount: 0,
  bandCapabilityInferenceCount: 0,
  advancedExactLoadInferenceCount: 0,
  secondaryOverridesPrimary: false,
  fCurrentRouteVisible: false,
  fCallsGenerateProgram: false,
  fPersistsQuestionnaire: false,
  fCallsCurrentRouteShadow: false,
  currentSignatureChanged: false,
  screenshotPersonalDataCopied: false,
  consumerScreenshotProvesGymsParity: false,
  screenshotKneesAddedToCode: false,
  reportedBandDetailInvented: false,
  eCompletedBeforeEvidence: false,
  fCompleted: false,
  ledgerFinalCompleted: false,
});

export const closureProjection = Object.freeze({
  ledgerBeforeSha: CHUNK_E_LEDGER_BEFORE_SHA,
  chunkEStatus: "completed_and_proven",
  chunkFStatus: "open",
  chunkGStatus: "open",
  chunkHStatus: "open",
  finalState: "INCOMPLETE_FUTURE_WORK_REMAINS",
  nextDependency: "ONE_INACTIVE_PRODUCT_GOAL_OPTION_V1_IMPLEMENTATION_AUTHORIZATION",
});

export const chunkEReadiness = Object.freeze({
  reference: PRODUCT_GOAL_CONTEXT_DESIGN_REFERENCE,
  combinedStatus: "SCREENSHOT_GUIDED_PRODUCT_GOAL_AND_CONTEXT_INPUT_DESIGN_V1_COMPLETED_NO_UI_CHANGE",
  classification: "SCREENSHOT_GUIDED_PRODUCT_GOAL_AND_CONTEXT_INPUT_DESIGN_V1_READY_FOR_ONE_INACTIVE_PRODUCT_GOAL_OPTION_AUTHORIZATION",
  selectedSurface: informationArchitecture.selectedSurface,
  selectedOption: "A",
  firstInactiveOption: "get_stronger",
  runtimeChangeCount: 0,
  productOutputCount: 0,
  activationCount: 0,
  unresolvedDrift: Object.freeze(["knees", "reported_band_detail", "owner_mobile_binary_inventory", "gyms_training_mode_parity"]),
  unsupportedPolicyGaps: Object.freeze(["power", "systemic_conditioning", "sport_specific_preparation",
    "maintenance_week_and_longitudinal", "broader_return_rebuild_delivery"]),
  nextDependency: "ONE_INACTIVE_PRODUCT_GOAL_OPTION_V1_IMPLEMENTATION_AUTHORIZATION",
});

export const designEvidence = Object.freeze({
  reference: PRODUCT_GOAL_CONTEXT_DESIGN_REFERENCE,
  ownerScreenshotCorpus,
  currentRenderBaseline,
  driftAudit,
  currentOwnership,
  dEvidenceConsequences,
  visualInvariants,
  informationArchitecture,
  goalOptionPolicy,
  primaryGoalDesign,
  followUpDesign,
  painContextDesign,
  reducePainMigration,
  trainingModeDesign,
  secondaryGoalDesign,
  scheduleExperienceEquipmentDesign,
  responsiveAccessibility,
  copyMatrix,
  stateMachine,
  signatureV2Design,
  productProfileV2Design,
  legacyCompatibility,
  consumerGymsParity,
  designRisks,
  designOptions,
  fHandoff,
  inputNecessityProjection,
  activationGuards,
  closureProjection,
  chunkEReadiness,
});
