import type {
  PreparationEvidenceReference,
  PreparationTaxonomyEntry,
} from "./contracts";

export const PREPARATION_EVIDENCE_REFERENCES: readonly PreparationEvidenceReference[] = Object.freeze([
  {
    referenceId: "warmup-performance-fradkin-2010",
    classification: "supported_evidence",
    citation: "Fradkin AJ, Zazryn TR, Smoliga JM. J Strength Cond Res. 2010;24(1):140-148. PMID: 19996770.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/19996770/",
    finding: "Adequate warm-up improved most performance criteria studied, although randomized evidence was limited.",
    boundary: "This supports preparation as a category, not a universal exercise list or injury-prevention claim.",
  },
  {
    referenceId: "dynamic-warmup-li-2023",
    classification: "supported_evidence",
    citation: "Li H et al. BMC Sports Sci Med Rehabil. 2023. PMID: 37644585.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/37644585/",
    finding: "Dynamic and combined static-plus-dynamic warm-up improved selected lower-limb explosive outcomes relative to control.",
    boundary: "Effects were heterogeneous and do not establish one best drill or a universal duration.",
  },
  {
    referenceId: "dynamic-stretching-opplert-2018",
    classification: "supported_evidence",
    citation: "Opplert J, Babault N. Sports Med. 2018;48(2):299-325. PMID: 29063454.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/29063454/",
    finding: "Controlled dynamic stretching can increase acute range of motion while preserving or improving subsequent performance.",
    boundary: "Procedure, duration, amplitude, and velocity matter; ballistic or fatiguing work is not inferred to be beneficial.",
  },
  {
    referenceId: "static-stretching-simic-2013",
    classification: "supported_evidence",
    citation: "Simic L, Sarabon N, Markovic G. Scand J Med Sci Sports. 2013;23(2):131-148. PMID: 22316148.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/22316148/",
    finding: "Static stretching used alone can impair subsequent strength, power, and speed, with larger effects at longer durations.",
    boundary: "Short, need-owned static range work is not prohibited, but must precede dynamic or task-specific preparation.",
  },
  {
    referenceId: "upper-body-warmup-mccrary-2015",
    classification: "supported_evidence",
    citation: "McCrary JM, Ackermann BJ, Halaki M. Br J Sports Med. 2015;49(14):935-942. PMID: 25694615.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/25694615/",
    finding: "Dynamic upper-body warm-up can support strength or power, while evidence did not establish injury prevention.",
    boundary: "The review does not justify generic shoulder correction or one universal activation exercise.",
  },
  {
    referenceId: "specific-warmup-abad-2011",
    classification: "supported_evidence",
    citation: "Abad CCC et al. J Strength Cond Res. 2011;25(8):2242-2245. PMID: 21544000.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/21544000/",
    finding: "A randomized leg-press study supports progressive exercise-specific sets before maximal strength performance.",
    boundary: "Its exact loads, repetitions, and long general warm-up are not universal prescription defaults.",
  },
  {
    referenceId: "pape-fatigue-xu-2025",
    classification: "supported_evidence",
    citation: "Xu Y et al. Front Physiol. 2025. PMID: 39853660.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/39853660/",
    finding: "Post-activation performance enhancement is heterogeneous and depends on conditioning dose, recovery, and person factors.",
    boundary: "Activation is not automatically potentiating and must not create fatigue that compromises main work.",
  },
  {
    referenceId: "inspiratory-warmup-cirino-2023",
    classification: "insufficient_evidence",
    citation: "Cirino C et al. Biology (Basel). 2023;12(2):333. PMID: 36829608.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/36829608/",
    finding: "Loaded inspiratory-muscle warm-up has mixed performance evidence across exercise contexts.",
    boundary: "It does not establish that unloaded 90/90 breathing universally improves strength or corrects posture.",
  },
  {
    referenceId: "cooldown-van-hooren-2018",
    classification: "supported_evidence",
    citation: "Van Hooren B, Peake JM. Sports Med. 2018;48(7):1575-1595. PMID: 29663142.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/29663142/",
    finding: "Active cooldown has little consistent evidence for improving same-day or next-day performance, soreness, or injury outcomes.",
    boundary: "Cooldown may own a comfortable downshift or range responsibility, without recovery guarantees.",
  },
  {
    referenceId: "postexercise-stretch-afonso-2021",
    classification: "supported_evidence",
    citation: "Afonso J et al. Front Physiol. 2021;12:677581. PMID: 34025459.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/34025459/",
    finding: "Post-exercise stretching did not outperform passive recovery for strength recovery or delayed soreness in the pooled evidence.",
    boundary: "Stretching must not claim reliable DOMS prevention or accelerated recovery.",
  },
  {
    referenceId: "praxis-causal-preparation-doctrine-v1",
    classification: "praxis_coaching_doctrine",
    citation: "Praxis owner decision: causal preparation foundation v1.",
    sourceUrl: "owner-decision:preparation-intelligence-v1",
    finding: "Use the smallest legal preparation set owned by typed person, session, mechanics, equipment, and time facts.",
    boundary: "No section filler, exercise-name inference, diagnosis, developmental credit, or fixed body-part template.",
  },
  {
    referenceId: "praxis-drill-mechanics-inference-v1",
    classification: "reasonable_biomechanical_inference",
    citation: "Praxis human exercise-science review: preparation drill mechanics v1.",
    sourceUrl: "human-review:preparation-intelligence-v1",
    finding: "A drill may serve a typed range, control, position, or rehearsal need when its reviewed mechanics match that need.",
    boundary: "Mechanical fit is not proof of a clinical diagnosis, correction, injury prevention, or global superiority.",
  },
]);

export const PREPARATION_TAXONOMY: readonly PreparationTaxonomyEntry[] = Object.freeze([
  { category: "general_readiness", order: 10, intendedSections: ["warmup"], developmentalCredit: false, purpose: "Raise general readiness when an explicit policy or person/session fact owns it.", ownershipBoundary: "May be shared; never automatic filler." },
  { category: "breathing_position", order: 20, intendedSections: ["warmup", "cooldown"], developmentalCredit: false, purpose: "Support an explicit breathing, ribcage/pelvis position, or downshift responsibility.", ownershipBoundary: "Shared when the same supported position serves the session; no universal strength claim." },
  { category: "dynamic_mobility", order: 30, intendedSections: ["warmup"], developmentalCredit: false, purpose: "Explore a required range dynamically before the task that needs it.", ownershipBoundary: "Shared by equivalent range needs and omitted without typed range evidence." },
  { category: "range_access", order: 40, intendedSections: ["warmup", "cooldown"], developmentalCredit: false, purpose: "Address a reviewed range requirement with an appropriate dynamic or bounded static exposure.", ownershipBoundary: "Static exposure before main work must be brief, need-owned, and followed by dynamic or task-specific preparation." },
  { category: "activation_control", order: 50, intendedSections: ["activation"], developmentalCredit: false, purpose: "Practice a required low-fatigue stabilizer or control capability.", ownershipBoundary: "Shared when dependencies are equivalent; fatigue may not impair main work." },
  { category: "movement_rehearsal", order: 60, intendedSections: ["warmup", "activation"], developmentalCredit: false, purpose: "Rehearse relevant movement mechanics without replacing developmental work.", ownershipBoundary: "May be shared across matching mechanics; no exercise-name matching." },
  { category: "exercise_acclimation", order: 70, intendedSections: ["main"], developmentalCredit: false, purpose: "Progressively acclimate to the exact selected exercise, setup, and load path.", ownershipBoundary: "Always local to one developmental assignment and distinct from separate preparation exercises." },
  { category: "cooldown_downshift", order: 90, intendedSections: ["cooldown"], developmentalCredit: false, purpose: "Own an optional comfortable downshift or range responsibility after developmental work.", ownershipBoundary: "Optional, removable before required main work, and carries no recovery guarantee." },
]);
