import {
  CONTROLLED_PRODUCT_SHADOW_COMPARISON_V1_1_REFERENCE,
  CONTROLLED_PRODUCT_SHADOW_GOAL_REALIZATION_MAPPING_REFERENCE,
  CONTROLLED_PRODUCT_SHADOW_PIPELINE_PROFILE_B1_B4_REFERENCE,
  CONTROLLED_PRODUCT_SHADOW_RUN_V1_1_REFERENCE,
  PRODUCT_AVAILABILITY_HORIZON_SHADOW_MAPPING_REFERENCE,
  PRODUCT_EQUIPMENT_REALIZATION_SHADOW_MAPPING_REFERENCE,
  PRODUCT_EXPERIENCE_REALIZATION_SHADOW_MAPPING_REFERENCE,
  PRODUCT_GOAL_ARCHITECTURE_SHADOW_MAPPING_V2_REFERENCE,
  PRODUCT_GOAL_REALIZATION_MAPPING_BUNDLE_REFERENCE,
  PRODUCT_GOAL_TO_PLANNING_BRIEF_SHADOW_POLICY_V1_REFERENCE,
  PRODUCT_LEGACY_HISTORY_AUTHORITY_PROJECTION_REFERENCE,
  PRODUCT_PREFERENCE_CONTINUITY_SHADOW_MAPPING_REFERENCE,
  PRODUCT_TRAINING_MODE_SHADOW_MAPPING_V2_REFERENCE,
} from "@praxis/training-engine-v2";
import type { ControlledProductShadowGoalRealizationProfileV1 } from "./contracts";

export const CONTROLLED_PRODUCT_SHADOW_GOAL_REALIZATION_PROFILE_V1_B1_B4 = Object.freeze({
  profileId: "CONTROLLED_PRODUCT_SHADOW_GOAL_REALIZATION_PROFILE_V1_B1_B4",
  reference: CONTROLLED_PRODUCT_SHADOW_GOAL_REALIZATION_MAPPING_REFERENCE,
  mappingContractReferences: Object.freeze([
    PRODUCT_GOAL_ARCHITECTURE_SHADOW_MAPPING_V2_REFERENCE,
    PRODUCT_GOAL_TO_PLANNING_BRIEF_SHADOW_POLICY_V1_REFERENCE,
    PRODUCT_TRAINING_MODE_SHADOW_MAPPING_V2_REFERENCE,
    PRODUCT_EXPERIENCE_REALIZATION_SHADOW_MAPPING_REFERENCE,
    PRODUCT_EQUIPMENT_REALIZATION_SHADOW_MAPPING_REFERENCE,
    PRODUCT_AVAILABILITY_HORIZON_SHADOW_MAPPING_REFERENCE,
    PRODUCT_PREFERENCE_CONTINUITY_SHADOW_MAPPING_REFERENCE,
    PRODUCT_LEGACY_HISTORY_AUTHORITY_PROJECTION_REFERENCE,
    PRODUCT_GOAL_REALIZATION_MAPPING_BUNDLE_REFERENCE,
  ]),
  goalPlanningBriefPolicyReference: PRODUCT_GOAL_TO_PLANNING_BRIEF_SHADOW_POLICY_V1_REFERENCE,
  b1B4References: Object.freeze([
    { contractId: "PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_V1_LAYERED_PURPOSE_FIRST",
      contractVersion: "1.0.0" },
    { contractId: "PURPOSE_FIRST_GOAL_SPECIFIC_PRESCRIPTION_RESOLVER", contractVersion: "1.0.0" },
    { contractId: "SUPPORTED_GOAL_AND_LOCAL_PURPOSE_POLICY", contractVersion: "1.0.0" },
    { contractId: "EXPERIENCE_CONTEXT_PRESCRIPTION_REALIZATION_POLICY_V1", contractVersion: "1.0.0" },
  ]),
  pipelineProfileReference: CONTROLLED_PRODUCT_SHADOW_PIPELINE_PROFILE_B1_B4_REFERENCE,
  comparisonReference: CONTROLLED_PRODUCT_SHADOW_COMPARISON_V1_1_REFERENCE,
  runReference: CONTROLLED_PRODUCT_SHADOW_RUN_V1_1_REFERENCE,
  defaultSelected: false,
  productAuthority: "LEGACY_PRODUCT_OUTPUT_ONLY",
  activationState: "NOT_ACTIVATED",
  counterfactualOnly: true,
  provenance: Object.freeze(["canonical-ledger:chunk-c", "explicit-profile-selection-only",
    "historical-product-shadow-v1-frozen"]),
} as const satisfies ControlledProductShadowGoalRealizationProfileV1);

export function validateControlledProductShadowGoalRealizationProfile(
  profile: ControlledProductShadowGoalRealizationProfileV1,
): readonly string[] {
  const reasons: string[] = [];
  if (profile.profileId !== "CONTROLLED_PRODUCT_SHADOW_GOAL_REALIZATION_PROFILE_V1_B1_B4") {
    reasons.push("CONTROLLED_PRODUCT_SHADOW_MAPPING_PROFILE_VERSION_UNAVAILABLE");
  }
  if (profile.defaultSelected || !profile.counterfactualOnly || profile.activationState !== "NOT_ACTIVATED") {
    reasons.push("CONTROLLED_PRODUCT_SHADOW_PROFILE_ACTIVATION_REJECTED");
  }
  if (profile.productAuthority !== "LEGACY_PRODUCT_OUTPUT_ONLY") {
    reasons.push("CONTROLLED_PRODUCT_SHADOW_PRODUCT_AUTHORITY_INVALID");
  }
  return Object.freeze(reasons);
}
