import {
  KNOWLEDGE_CORE_CONTRACT,
  PRODUCTION_64_KNOWLEDGE_REGISTRY_CONTRACT,
  PRODUCTION_69_KNOWLEDGE_REGISTRY_CONTRACT,
  PRODUCTION_KNOWLEDGE_REGISTRY_CONTRACT,
} from "./contracts";
import { PACKAGE_R_KNOWLEDGE_ENTRIES } from "./entries";
import { LOWER_BODY_ACCESSORY_KNOWLEDGE_ENTRIES } from "./entries/lowerBodyAndAccessories";
import { PREPARATION_PRESSING_PULLING_KNOWLEDGE_ENTRIES } from "./entries/preparationPressingPulling";
import { TRUNK_CARRY_SUPPORT_KNOWLEDGE_ENTRIES } from "./entries/trunkCarriesAndSupport";
import { PACKAGE_S_KNOWLEDGE_ENTRIES } from "./entries/standardGymFoundations";
import { PREPARATION_FOUNDATION_KNOWLEDGE_ENTRIES } from "./entries/preparationFoundation";

export const ORIGINAL_45_KNOWLEDGE_ENTRIES = Object.freeze([
  ...PREPARATION_PRESSING_PULLING_KNOWLEDGE_ENTRIES,
  ...LOWER_BODY_ACCESSORY_KNOWLEDGE_ENTRIES,
  ...TRUNK_CARRY_SUPPORT_KNOWLEDGE_ENTRIES,
]);

export const ORIGINAL_45_KNOWLEDGE_IDS = Object.freeze(
  ORIGINAL_45_KNOWLEDGE_ENTRIES.map((entry) => entry.exerciseId),
);

export const PRODUCTION_53_KNOWLEDGE_ENTRIES = Object.freeze([
  ...ORIGINAL_45_KNOWLEDGE_ENTRIES,
  ...PACKAGE_R_KNOWLEDGE_ENTRIES,
]);

export const PRODUCTION_53_KNOWLEDGE_REGISTRY = Object.freeze({
  contract: PRODUCTION_KNOWLEDGE_REGISTRY_CONTRACT,
  entries: PRODUCTION_53_KNOWLEDGE_ENTRIES,
});

export const PRODUCTION_53_KNOWLEDGE_CORE = Object.freeze({
  contract: KNOWLEDGE_CORE_CONTRACT,
  entries: PRODUCTION_53_KNOWLEDGE_ENTRIES,
});

export const PRODUCTION_64_KNOWLEDGE_ENTRIES = Object.freeze([
  ...PRODUCTION_53_KNOWLEDGE_ENTRIES,
  ...PACKAGE_S_KNOWLEDGE_ENTRIES,
]);

export const PRODUCTION_64_KNOWLEDGE_REGISTRY = Object.freeze({
  contract: PRODUCTION_64_KNOWLEDGE_REGISTRY_CONTRACT,
  entries: PRODUCTION_64_KNOWLEDGE_ENTRIES,
});

export const PRODUCTION_64_KNOWLEDGE_CORE = Object.freeze({
  contract: KNOWLEDGE_CORE_CONTRACT,
  entries: PRODUCTION_64_KNOWLEDGE_ENTRIES,
});

export const PRODUCTION_69_KNOWLEDGE_ENTRIES = Object.freeze([
  ...PRODUCTION_64_KNOWLEDGE_ENTRIES,
  ...PREPARATION_FOUNDATION_KNOWLEDGE_ENTRIES,
]);

export const PRODUCTION_69_KNOWLEDGE_REGISTRY = Object.freeze({
  contract: PRODUCTION_69_KNOWLEDGE_REGISTRY_CONTRACT,
  entries: PRODUCTION_69_KNOWLEDGE_ENTRIES,
});

export const PRODUCTION_69_KNOWLEDGE_CORE = Object.freeze({
  contract: KNOWLEDGE_CORE_CONTRACT,
  entries: PRODUCTION_69_KNOWLEDGE_ENTRIES,
});

export const PRODUCTION_KNOWLEDGE_REGISTRY = PRODUCTION_69_KNOWLEDGE_REGISTRY;
