import { KNOWLEDGE_CORE_CONTRACT, PRODUCTION_KNOWLEDGE_REGISTRY_CONTRACT } from "./contracts";
import { PACKAGE_R_KNOWLEDGE_ENTRIES } from "./entries";
import { LOWER_BODY_ACCESSORY_KNOWLEDGE_ENTRIES } from "./entries/lowerBodyAndAccessories";
import { PREPARATION_PRESSING_PULLING_KNOWLEDGE_ENTRIES } from "./entries/preparationPressingPulling";
import { TRUNK_CARRY_SUPPORT_KNOWLEDGE_ENTRIES } from "./entries/trunkCarriesAndSupport";

export const ORIGINAL_45_KNOWLEDGE_ENTRIES = Object.freeze([
  ...PREPARATION_PRESSING_PULLING_KNOWLEDGE_ENTRIES,
  ...LOWER_BODY_ACCESSORY_KNOWLEDGE_ENTRIES,
  ...TRUNK_CARRY_SUPPORT_KNOWLEDGE_ENTRIES,
]);

export const ORIGINAL_45_KNOWLEDGE_IDS = Object.freeze(
  ORIGINAL_45_KNOWLEDGE_ENTRIES.map((entry) => entry.exerciseId),
);

export const PRODUCTION_53_KNOWLEDGE_ENTRIES = Object.freeze([
  ...ORIGINAL_45_KNOWLEDGE_ENTRIES,
  ...PACKAGE_R_KNOWLEDGE_ENTRIES,
]);

export const PRODUCTION_53_KNOWLEDGE_REGISTRY = Object.freeze({
  contract: PRODUCTION_KNOWLEDGE_REGISTRY_CONTRACT,
  entries: PRODUCTION_53_KNOWLEDGE_ENTRIES,
});

export const PRODUCTION_53_KNOWLEDGE_CORE = Object.freeze({
  contract: KNOWLEDGE_CORE_CONTRACT,
  entries: PRODUCTION_53_KNOWLEDGE_ENTRIES,
});
