export const REASON_CODES = [
  "EQUIPMENT_UNAVAILABLE",
  "SETUP_IMPOSSIBLE",
  "PERSONAL_BLOCK",
  "HARD_CONTRAINDICATION",
  "CAPABILITY_MISSING",
  "ROLE_MISMATCH",
  "TRAINING_NEED_MISMATCH",
  "SECTION_MISMATCH",
  "MOVEMENT_ROLE_MISMATCH",
  "TARGET_MUSCLE_MISMATCH",
  "PAIN_REQUIRES_REVIEW",
  "ASSESSMENT_PRIORITY_SUPPORTED",
  "ASSESSMENT_PRIORITY_CONFLICT",
  "ASSESSMENT_ROLE_RELEVANT",
  "ASSESSMENT_MOVEMENT_RELEVANT",
  "ASSESSMENT_STABILITY_RELEVANT",
  "ASSESSMENT_JOINT_RELEVANT",
  "ASSESSMENT_NOT_RELEVANT",
  "ASSESSMENT_SUPPORTS_CONTROL",
  "ASSESSMENT_REDUCES_EXCESS_DEMAND",
  "ASSESSMENT_APPROPRIATE_EXPOSURE",
  "ASSESSMENT_DEVELOPS_PRIORITY",
  "ASSESSMENT_UNDER_CHALLENGES_DEVELOPMENT",
  "ASSESSMENT_EXCEEDS_CAPABILITY",
  "ASSESSMENT_NEUTRAL_RELATIONSHIP",
  "ALIGNMENT_PRIORITY_SUPPORTED",
  "ALIGNMENT_PRIORITY_CONFLICT",
  "CONTINUITY_FAVORED",
  "PROGRESSION_AVAILABLE",
  "REPLACEMENT_JUSTIFIED",
  "PIPELINE_STAGE_RECORDED",
  "SCORE_NEUTRAL",
  "ROLE_MATCH",
  "GOAL_MATCH",
  "SESSION_INTENT_MATCH",
  "MUSCLE_TARGET_MATCH",
  "PAIN_SUITABLE",
  "EXPERIENCE_APPROPRIATE",
  "PHASE_DEVELOPMENT_FIT",
  "STABILITY_APPROPRIATE",
  "SKILL_APPROPRIATE",
  "LOADABILITY_MATCH",
  "STIMULUS_MATCH",
  "FATIGUE_COST_ACCEPTABLE",
  "JOINT_COST_ACCEPTABLE",
  "EQUIPMENT_PRACTICAL",
] as const;

export type ReasonCode = (typeof REASON_CODES)[number];

export type ReasonSource =
  | "equipment"
  | "setup"
  | "athlete_preference"
  | "pain_injury"
  | "exercise_schema"
  | "session_intent"
  | "assessment"
  | "alignment"
  | "phase"
  | "history"
  | "optimizer"
  | "prescription"
  | "progression"
  | "validation";

export interface DecisionReason {
  readonly code: ReasonCode;
  readonly source: ReasonSource;
  readonly message: string;
  readonly evidence: readonly string[];
}

export function isReasonCode(value: string): value is ReasonCode {
  return REASON_CODES.includes(value as ReasonCode);
}
