// Generated by dev/generateExerciseCoachingFallbacks.ts. Do not edit by hand.
// Canonical source: @praxis/knowledge-core accepted Package R facts.

export interface GeneratedExerciseCoachingFallback {
  readonly summary: string;
  readonly coachingFocus: readonly string[];
  readonly sourceFactIds: readonly string[];
}

export const GENERATED_EXERCISE_COACHING_FALLBACKS: Readonly<Record<string, GeneratedExerciseCoachingFallback>> = Object.freeze(
{
  "band-biceps-curl": {
    "summary": "Self-anchored band elbow-flexion accessory.",
    "coachingFocus": [
      "Bend the elbows with steady upper arms",
      "Keep the band secure underfoot"
    ],
    "sourceFactIds": [
      "band-biceps-curl.pattern.anchorless-curl",
      "band-biceps-curl.focus.elbow-flexion",
      "band-biceps-curl.cue.stand-on-band"
    ]
  },
  "bent-over-dumbbell-reverse-fly": {
    "summary": "Bent-over rear-delt horizontal-abduction accessory, not a row.",
    "coachingFocus": [
      "Sweep the arms outward without rowing",
      "Keep a soft fixed elbow"
    ],
    "sourceFactIds": [
      "bent-over-dumbbell-reverse-fly.pattern.rear-delt-accessory",
      "bent-over-dumbbell-reverse-fly.focus.rear-delt-arc",
      "bent-over-dumbbell-reverse-fly.cue.soft-elbows"
    ]
  },
  "bird-dog": {
    "summary": "Quadruped contralateral trunk-control task.",
    "coachingFocus": [
      "Reach opposite limbs without shifting the trunk",
      "Press the support points down"
    ],
    "sourceFactIds": [
      "bird-dog.pattern.contralateral-trunk",
      "bird-dog.focus.contralateral-reach",
      "bird-dog.cue.push-floor"
    ]
  },
  "dumbbell-floor-press": {
    "summary": "Floor-supported horizontal press with a bounded lowering range.",
    "coachingFocus": [
      "Press up from a floor-bounded bottom position",
      "Stack wrists over elbows"
    ],
    "sourceFactIds": [
      "dumbbell-floor-press.pattern.horizontal-press",
      "dumbbell-floor-press.focus.floor-bounded-press",
      "dumbbell-floor-press.cue.wrist-over-elbow"
    ]
  },
  "dumbbell-triceps-extension": {
    "summary": "Direct elbow-extension accessory using one overhead dumbbell.",
    "coachingFocus": [
      "Extend at the elbows with a steady upper-arm path",
      "Keep a secure two-hand grip"
    ],
    "sourceFactIds": [
      "dumbbell-triceps-extension.pattern.direct-extension",
      "dumbbell-triceps-extension.focus.elbow-extension",
      "dumbbell-triceps-extension.cue.secure-grip"
    ]
  },
  "machine-leg-extension": {
    "summary": "Supported direct knee-extension accessory, not a squat.",
    "coachingFocus": [
      "Extend the knees from a stable machine setup",
      "Stay connected to the seat"
    ],
    "sourceFactIds": [
      "machine-leg-extension.pattern.direct-knee-extension",
      "machine-leg-extension.focus.knee-extension",
      "machine-leg-extension.cue.seat-contact"
    ]
  },
  "machine-shoulder-press": {
    "summary": "Supported machine-guided vertical push.",
    "coachingFocus": [
      "Press through the guided path from a stable setup",
      "Stay connected to the back support"
    ],
    "sourceFactIds": [
      "machine-shoulder-press.pattern.supported-vertical-push",
      "machine-shoulder-press.focus.guided-press",
      "machine-shoulder-press.cue.back-supported"
    ]
  },
  "side-lying-hip-abduction": {
    "summary": "Floor-supported bodyweight hip abduction for the top leg.",
    "coachingFocus": [
      "Lift from the hip with the pelvis stacked",
      "Keep the top leg long"
    ],
    "sourceFactIds": [
      "side-lying-hip-abduction.pattern.floor-abduction",
      "side-lying-hip-abduction.focus.lateral-lift",
      "side-lying-hip-abduction.cue.long-leg"
    ]
  }
}
);
