import { TRAINING_OUTCOME_GOALS } from "../domain/sessionPlanningDirective";
import {
  PRODUCT_GOAL_ARCHITECTURE_ACTIVATION_STATES,
  PRODUCT_GOAL_ARCHITECTURE_CHUNK_STATES,
  PRODUCT_GOAL_ARCHITECTURE_MAPPING_STATES,
  PRODUCT_GOAL_ARCHITECTURE_NEXT_DEPENDENCY,
  PRODUCT_GOAL_ARCHITECTURE_PRIORITIES,
  PRODUCT_GOAL_ARCHITECTURE_PRODUCT_LABELS,
  PRODUCT_GOAL_ARCHITECTURE_PURPOSE_FIRST_ORDER,
  PRODUCT_GOAL_ARCHITECTURE_PURPOSE_LANES,
  PRODUCT_GOAL_ARCHITECTURE_PURPOSE_POLICY_STATES,
  PRODUCT_GOAL_ARCHITECTURE_TRAINING_MODES,
  PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_ID,
  PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_REFERENCE,
  PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_STATUS,
  PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_VERSION,
  type ProductGoalArchitectureLabelDirection,
} from "./contracts";

const productVocabulary: readonly ProductGoalArchitectureLabelDirection[] = Object.freeze([
  Object.freeze({ label: "get_stronger", displayDirection: "Get stronger",
    candidateOutcome: "strength", mappingState: "exact_candidate_mapping",
    currentProductOption: false, runtimeMappingImplemented: false, activationState: "not_implemented" }),
  Object.freeze({ label: "build_muscle", displayDirection: "Build muscle",
    candidateOutcome: "hypertrophy", mappingState: "exact_candidate_mapping",
    currentProductOption: false, runtimeMappingImplemented: false, activationState: "not_implemented" }),
  Object.freeze({ label: "improve_fitness_and_stamina", displayDirection: "Improve fitness and stamina",
    candidateOutcome: null, mappingState: "owner_policy_required",
    currentProductOption: false, runtimeMappingImplemented: false, activationState: "not_implemented" }),
  Object.freeze({ label: "improve_posture_and_movement", displayDirection: "Improve posture and movement",
    candidateOutcome: "posture_and_movement_quality", mappingState: "exact_candidate_mapping",
    currentProductOption: false, runtimeMappingImplemented: false, activationState: "not_implemented" }),
  Object.freeze({ label: "improve_athletic_performance", displayDirection: "Improve athletic performance",
    candidateOutcome: null, mappingState: "structured_follow_up_required",
    currentProductOption: false, runtimeMappingImplemented: false, activationState: "not_implemented" }),
]);

const stagedImplementation = Object.freeze([
  Object.freeze({ chunk: "B1", scope: "canonical_owner_policy_contracts", state: "completed_inert" }),
  Object.freeze({ chunk: "B2", scope: "purpose_first_prescription_resolver", state: "future_authorization_required" }),
  Object.freeze({ chunk: "B3", scope: "supported_goal_and_purpose_policies", state: "future_owner_policy_required" }),
  Object.freeze({ chunk: "B4", scope: "equipment_experience_context_realization", state: "future_evidence_required" }),
  Object.freeze({ chunk: "C", scope: "controlled_product_shadow_mapping", state: "future_default_off_only" }),
  Object.freeze({ chunk: "D", scope: "goal_specific_shadow_evidence", state: "future_counterfactual_only" }),
  Object.freeze({ chunk: "E", scope: "owner_screenshot_surface_review", state: "future_owner_input_required" }),
  Object.freeze({ chunk: "F", scope: "one_inactive_product_option", state: "future_authorization_required" }),
  Object.freeze({ chunk: "G", scope: "owner_account_delivery", state: "separate_authorization_required" }),
  Object.freeze({ chunk: "H", scope: "broader_product_activation", state: "separate_authorization_required" }),
]);

export const PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_V1 = Object.freeze({
  policyReference: Object.freeze({
    contractId: PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_ID,
    contractVersion: PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_VERSION,
    contractReference: PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_REFERENCE,
  }),
  status: PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_STATUS,
  executable: false,
  canonicalLedger: "docs/training-engine-v2/PRAXIS_PRODUCT_GOAL_ARCHITECTURE_LEDGER.md",
  authority: "OWNER_APPROVED_ARCHITECTURE_ENCODED_INERTLY",
  canonicalOutcomeGoals: TRAINING_OUTCOME_GOALS,
  closedVocabularies: Object.freeze({
    productLabels: PRODUCT_GOAL_ARCHITECTURE_PRODUCT_LABELS,
    goalPriorities: PRODUCT_GOAL_ARCHITECTURE_PRIORITIES,
    trainingModes: PRODUCT_GOAL_ARCHITECTURE_TRAINING_MODES,
    mappingStates: PRODUCT_GOAL_ARCHITECTURE_MAPPING_STATES,
    purposePolicyStates: PRODUCT_GOAL_ARCHITECTURE_PURPOSE_POLICY_STATES,
    activationStates: PRODUCT_GOAL_ARCHITECTURE_ACTIVATION_STATES,
    chunkStates: PRODUCT_GOAL_ARCHITECTURE_CHUNK_STATES,
  }),
  productVocabulary,
  goalPriority: Object.freeze({
    primaryGoalCount: 1,
    secondaryGoalMinimum: 0,
    secondaryGoalMaximum: 1,
    ordered: true,
    sameGoalMayOccupyBothPriorities: false,
    equalPriorityBagAllowed: false,
  }),
  programmingContext: Object.freeze({
    separateFromOutcome: true,
    painAwareReturnIsContextOnly: true,
    painIsDiagnostic: false,
    examples: Object.freeze(["pain_aware_return", "return_after_absence",
      "explicit_restriction", "successful_re_exposure"]),
  }),
  trainingMode: Object.freeze({
    separateFromOutcome: true,
    values: PRODUCT_GOAL_ARCHITECTURE_TRAINING_MODES,
    currentBuildMeaning: "developmental_progression_not_outcome",
    maintainPolicyState: "future_policy_required",
    returnOrRebuildPolicyState: "future_policy_required",
  }),
  prescriptionResolution: Object.freeze({
    selectedArchitecture: "G4_PURPOSE_FIRST_PLUS_G1_FAIL_CLOSED",
    purposeFirstOrder: PRODUCT_GOAL_ARCHITECTURE_PURPOSE_FIRST_ORDER,
    outcomeGoalRole: "bounded_context_after_local_ownership_and_realization",
    missingPolicyBehavior: "fail_closed",
    missingPolicyResults: Object.freeze(["POLICY_REQUIRED", "UNSUPPORTED_SCOPE"]),
    strengthFallthroughAllowed: false,
    executableResolverImplemented: false,
  }),
  purposeLanes: Object.freeze({
    values: PRODUCT_GOAL_ARCHITECTURE_PURPOSE_LANES,
    currentlyReviewed: Object.freeze(["strength_development", "hypertrophy_development",
      "local_capacity", "preparation", "activation", "recovery"]),
    futurePolicyRequired: Object.freeze(["power_development", "muscular_endurance",
      "systemic_conditioning", "movement_quality", "technique"]),
  }),
  strengthBoundary: Object.freeze({
    mayFavor: Object.freeze(["sufficiently_loadable_main_work", "stable_repeatable_movement_skill",
      "lower_repetitions_where_truthful", "longer_rest_where_required",
      "evidence_led_legal_progression", "main_work_early"]),
    mustNotForce: Object.freeze(["universal_3_to_6_repetitions", "low_reps_for_unsuitable_identities",
      "barbell_only_selection", "beginner_maximal_loading", "pain_aware_maximal_loading",
      "identical_equipment_prescriptions", "automatic_progression"]),
  }),
  hypertrophyBoundary: Object.freeze({
    mayFavor: Object.freeze(["sufficient_developmental_volume", "broad_legal_repetition_ranges",
      "sufficient_effort", "enough_rest_to_preserve_useful_work", "stable_target_ownership",
      "unique_value_direct_or_accessory_work"]),
    doesNotRequire: Object.freeze(["only_8_to_12_repetitions", "short_rest", "failure",
      "mandatory_slow_tempo", "soreness", "exercise_churn"]),
  }),
  adjacentBoundaries: Object.freeze({
    generalFitness: "coherent_responsibility_bundle_not_universal_rep_range",
    muscularEndurance: "local_fatigue_resistance_not_systemic_conditioning",
    conditioning: "systemic_or_broader_work_capacity_future_policy_required",
    power: "explicit_future_developmental_purpose_and_policy_required",
    athleticPerformance: "structured_product_follow_up_required_no_silent_mapping",
  }),
  toningLanguage: Object.freeze({
    canonicalOutcome: false,
    initialState: "T0_INTENTIONALLY_NOT_EXPOSED",
    futurePreferredState: "T2_STRUCTURED_CLARIFICATION",
    clarificationOptions: Object.freeze(["more_muscle", "lower_body_fat", "greater_endurance", "combination"]),
    directHighRepsShortRestResolutionAllowed: false,
  }),
  bodyComposition: Object.freeze({
    owner: "SEPARATE_PRODUCT_OR_PROFILE_OWNER_REQUIRED",
    prescriptionOwnerAllowed: false,
    intentExamples: Object.freeze(["lose_body_fat", "build_or_preserve_muscle", "both"]),
  }),
  nutrition: Object.freeze({
    owner: "SEPARATE_NUTRITION_OWNER_REQUIRED",
    prescriptionOwnerAllowed: false,
    fatLossPromiseFromRepRangeAllowed: false,
  }),
  activation: Object.freeze({
    productMappingChanged: false,
    productUiChanged: false,
    shadowMappingChanged: false,
    shadowRolloutChanged: false,
    v2Activated: false,
    publicProductApiChanged: false,
    currentState: "not_implemented",
  }),
  stagedImplementation,
  nextDependency: PRODUCT_GOAL_ARCHITECTURE_NEXT_DEPENDENCY,
});

export type ProductTrainingGoalArchitecturePolicyV1 =
  typeof PRODUCT_TRAINING_GOAL_ARCHITECTURE_POLICY_V1;
