import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  PRODUCTION_64_KNOWLEDGE_ENTRIES,
  projectCompactFallbacks,
} from "../../praxis-knowledge-core/src";

const packageRoot = process.cwd().endsWith("packages/training-engine-v2")
  ? process.cwd()
  : resolve(process.cwd(), "packages/training-engine-v2");

export const generatedFallbackPath = resolve(
  packageRoot,
  "src/data/generatedExerciseCoachingFallbacks.ts",
);

export function renderGeneratedExerciseCoachingFallbacks(): string {
  const rows = projectCompactFallbacks(PRODUCTION_64_KNOWLEDGE_ENTRIES);
  const registry = Object.fromEntries(rows.map((row) => [row.exerciseId, {
    summary: row.summary,
    coachingFocus: row.coachingFocus,
    sourceFactIds: row.sourceFactIds,
  }]));
  return [
    "// Generated by dev/generateExerciseCoachingFallbacks.ts. Do not edit by hand.",
    "// Canonical source: @praxis/knowledge-core accepted production facts.",
    "",
    "export interface GeneratedExerciseCoachingFallback {",
    "  readonly summary: string;",
    "  readonly coachingFocus: readonly string[];",
    "  readonly sourceFactIds: readonly string[];",
    "}",
    "",
    "export const GENERATED_EXERCISE_COACHING_FALLBACKS: Readonly<Record<string, GeneratedExerciseCoachingFallback>> = Object.freeze(",
    JSON.stringify(registry, null, 2),
    ");",
    "",
  ].join("\n");
}

export function generatedExerciseCoachingFallbackStatus(): {
  readonly path: string;
  readonly exists: boolean;
  readonly stale: boolean;
} {
  const expected = renderGeneratedExerciseCoachingFallbacks();
  const exists = existsSync(generatedFallbackPath);
  return {
    path: generatedFallbackPath,
    exists,
    stale: !exists || readFileSync(generatedFallbackPath, "utf8") !== expected,
  };
}

if (resolve(process.argv[1] ?? "") === resolve(fileURLToPath(import.meta.url))) {
  const mode = process.argv[2] ?? "--print";
  if (mode === "--write") {
    writeFileSync(generatedFallbackPath, renderGeneratedExerciseCoachingFallbacks(), "utf8");
    process.stdout.write(`${generatedFallbackPath}\n`);
  } else if (mode === "--check") {
    const status = generatedExerciseCoachingFallbackStatus();
    if (status.stale) throw new Error(`GENERATED_EXERCISE_COACHING_FALLBACK_STALE:${status.path}`);
    process.stdout.write("generated exercise coaching fallbacks are current\n");
  } else if (mode === "--print") {
    process.stdout.write(renderGeneratedExerciseCoachingFallbacks());
  } else {
    throw new Error(`UNKNOWN_GENERATION_MODE:${mode}`);
  }
}
